### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getPath' of undefined

### ISSUE THREAD

**Issue by mdotasia** [yongkangchen/remote-sync#101]
Has anyone managed to get this plugin to work on Windows?

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.187.0
**System**: Microsoft Windows 7 Enterprise 
**Thrown From**: [remote-sync](https://github.com/yongkangchen/remote-sync) package, v2.4.0

### Stack Trace

Uncaught TypeError: Cannot read property 'getPath' of undefined

```
At C:\Users\Thilo.Maier\.atom\packages\remote-sync\lib\RemoteSync.coffee:239

TypeError: Cannot read property 'getPath' of undefined
  at getEventPath (C:\Users\Thilo.Maier\.atom\packages\remote-sync\lib\RemoteSync.coffee:239:9)
  at atom-workspace.<anonymous> (C:\Users\Thilo.Maier\.atom\packages\remote-sync\lib\RemoteSync.coffee:52:18)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Thilo.Maier\AppData\Local\atom\app-0.187.0\resources\app\src\command-registry.js:246:29)
  at C:\Users\Thilo.Maier\AppData\Local\atom\app-0.187.0\resources\app\src\command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (C:\Users\Thilo.Maier\AppData\Local\atom\app-0.187.0\resources\app\node_modules\command-palette\lib\command-palette-view.js:120:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (C:\Users\Thilo.Maier\AppData\Local\atom\app-0.187.0\resources\app\node_modules\atom-space-pen-views\lib\select-list-view.js:338:21)
  at space-pen-li.<anonymous> (C:\Users\Thilo.Maier\AppData\Local\atom\app-0.187.0\resources\app\node_modules\atom-space-pen-views\lib\select-list-view.js:139:19)
  at HTMLOListElement.jQuery.event.dispatch (C:\Users\Thilo.Maier\AppData\Local\atom\app-0.187.0\resources\app\node_modules\jquery\dist\jquery.js:4430:9)
  at HTMLOListElement.elemData.handle (C:\Users\Thilo.Maier\AppData\Local\atom\app-0.187.0\resources\app\node_modules\jquery\dist\jquery.js:4116:28)

```

### Commands

```
     -1:01.6 command-palette:toggle (atom-pane.pane.active)
  6x -0:55.7 core:move-down (atom-text-editor.editor.mini)
     -0:54.1 core:confirm (atom-text-editor.editor.mini)
     -0:54.1 remote-sync:reload-config (atom-pane.pane.active)
     -0:48.3 remote-sync:configure (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-atom-dark-ui)
     -0:28.0 command-palette:toggle (atom-pane.pane.active)
  5x -0:23.4 core:backspace (atom-text-editor.editor.mini)
  3x -0:19.5 core:move-down (atom-text-editor.editor.mini)
     -0:08.0 remote-sync:upload-folder (atom-pane.pane.active)
```

### Config

```json
{
  "core": {
    "excludeVcsIgnoredPaths": false,
    "disabledPackages": [
      "log-console"
    ]
  },
  "remote-sync": {}
}
```

### Installed Packages

```coffee
# User
angularjs, v0.1.0
autocomplete-plus, v2.4.2
compare-files, v0.4.1
cucumber, v0.4.1
editorconfig, v0.3.0
file-icons, v1.5.1
git-diff-details, v0.6.0
git-log, v0.3.0
git-tab-status, v1.5.3
highlight-line, v0.10.1
language-gitignore, v0.1.1
language-liquid, v0.2.0
linter, v0.12.0
linter-csslint, v0.0.11
linter-htmlhint, v0.0.8
linter-js-yaml, v1.0.0
linter-jshint, v0.1.0
linter-rubocop, v0.2.2
linter-scss-lint, v0.0.14
remote-sync, v2.4.0
rsense, v0.6.0
sync-settings, v0.2.2

# Dev
No dev packages
```

**Comment by yongkangchen** [comment]
Fixed in V3.0
