### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getPath' of undefined

### ISSUE THREAD

**Issue by dmnBrest** [yongkangchen/remote-sync#103]
1. CTRL+SHIFT+P 
2. upload file/folder 

**Atom Version**: 0.187.0
**System**: Unknown Windows Version
**Thrown From**: [remote-sync](https://github.com/yongkangchen/remote-sync) package, v2.4.0

### Stack Trace

Uncaught TypeError: Cannot read property 'getPath' of undefined

```
At C:\Users\dmn\.atom\packages\remote-sync\lib\RemoteSync.coffee:239

TypeError: Cannot read property 'getPath' of undefined
    at getEventPath (C:\Users\dmn\.atom\packages\remote-sync\lib\RemoteSync.coffee:363:18)
    at atom-workspace.<anonymous> (C:\Users\dmn\.atom\packages\remote-sync\lib\RemoteSync.coffee:71:27)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\dmn\AppData\Local\atom\app-0.187.0\resources\app\src\command-registry.js:246:29)
    at C:\Users\dmn\AppData\Local\atom\app-0.187.0\resources\app\src\command-registry.js:3:61
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (C:\Users\dmn\AppData\Local\atom\app-0.187.0\resources\app\node_modules\command-palette\lib\command-palette-view.js:120:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (C:\Users\dmn\AppData\Local\atom\app-0.187.0\resources\app\node_modules\atom-space-pen-views\lib\select-list-view.js:338:21)
    at space-pen-div.atom.commands.add.core:confirm (C:\Users\dmn\AppData\Local\atom\app-0.187.0\resources\app\node_modules\atom-space-pen-views\lib\select-list-view.js:109:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\dmn\AppData\Local\atom\app-0.187.0\resources\app\src\command-registry.js:246:29)
    at C:\Users\dmn\AppData\Local\atom\app-0.187.0\resources\app\src\command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\dmn\AppData\Local\atom\app-0.187.0\resources\app\node_modules\atom-keymap\lib\keymap-manager.js:558:16)
```

### Commands

```
     -0:22.2 pane:reopen-closed-item (ul.list-inline.tab-bar.inset-panel)
     -0:11.9 command-palette:toggle (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  5x -0:08.8 core:move-down (atom-text-editor.editor.mini)
     -0:05.7 core:confirm (atom-text-editor.editor.mini)
     -0:05.6 remote-sync:upload-folder (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "remote-edit"
    ],
    "themes": [
      "atom-light-ui",
      "atom-dark-syntax"
    ]
  },
  "remote-sync": {
    "difftoolCommand": "c:\\KDiff3\\kdiff3.exe",
    "logToConsole": true
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-plus, v2.6.0
go-plus, v3.3.1
remote-sync, v2.4.0

# Dev
No dev packages
```

**Comment by yongkangchen** [comment]
Fixed in V3.0
