### ISSUE TITLE
Uncaught TypeError: Cannot read property 'uploadFolder' of undefined

### ISSUE THREAD

**Issue by jysperm** [yongkangchen/remote-sync#142]
1. Create a `.remote-sync.json` in a new project.
2. Rigth click on tree-view, click `Upload Folder`, then will throw this error

If I restart Atom, this problem will be solved.

**Atom Version**: 0.201.0
**System**: Unknown Windows Version
**Thrown From**: [remote-sync](https://github.com/yongkangchen/remote-sync) package, v3.1.1

### Stack Trace

Uncaught TypeError: Cannot read property 'uploadFolder' of undefined

```
At C:\Users\jysperm\.atom\packages\remote-sync\index.coffee:64

TypeError: Cannot read property 'uploadFolder' of undefined
  at handleEvent (C:\Users\jysperm\.atom\packages\remote-sync\index.coffee:64:29)
  at atom-workspace.disposables.add.atom.commands.add.remote-sync:upload-folder (C:\Users\jysperm\.atom\packages\remote-sync\index.coffee:75:42)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\jysperm\AppData\Local\atom\app-0.201.0\resources\app.asar\src\command-registry.js:238:29)
  at CommandRegistry.handleCommandEvent (C:\Users\jysperm\AppData\Local\atom\app-0.201.0\resources\app.asar\src\command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\jysperm\AppData\Local\atom\app-0.201.0\resources\app.asar\src\command-registry.js:153:19)
  at [object Object].jQuery.fn.trigger (C:\Users\jysperm\AppData\Local\atom\app-0.201.0\resources\app.asar\src\space-pen-extensions.js:64:23)
  at EventEmitter.<anonymous> (C:\Users\jysperm\AppData\Local\atom\app-0.201.0\resources\app.asar\src\window-event-handler.js:76:67)
  at emitTwo (events.js:87:13)
  at EventEmitter.emit (events.js:169:7)
  at EventEmitter.ipc.sendSync (C:\Users\jysperm\AppData\Local\atom\app-0.201.0\resources\atom.asar\renderer\api\lib\ipc.js:21:31)
  at BrowserWindow.RemoteMemberFunction [as emit] (C:\Users\jysperm\AppData\Local\atom\app-0.201.0\resources\atom.asar\renderer\api\lib\remote.js:110:29)
  at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (C:\Users\jysperm\AppData\Local\atom\app-0.201.0\resources\app.asar\src\context-menu-manager.js:170:31)
  at HTMLDocument.<anonymous> (C:\Users\jysperm\AppData\Local\atom\app-0.201.0\resources\app.asar\src\window-event-handler.js:149:33)
  at HTMLDocument.handler (C:\Users\jysperm\AppData\Local\atom\app-0.201.0\resources\app.asar\src\space-pen-extensions.js:112:34)
  at HTMLDocument.jQuery.event.dispatch (C:\Users\jysperm\AppData\Local\atom\app-0.201.0\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4681:9)
  at HTMLDocument.elemData.handle (C:\Users\jysperm\AppData\Local\atom\app-0.201.0\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4359:46)

```

### Commands

```
     -0:30.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:21.6.0 core:paste (atom-text-editor.editor.is-focused)
     -0:20.3.0 core:save (atom-text-editor.editor.is-focused)
  6x -0:16.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:11.1.0 core:save (atom-text-editor.editor.is-focused)
     -0:07.4.0 core:close (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "projectHome": "C:\\Users\\jysperm\\Git",
    "disabledPackages": [
      "react"
    ]
  },
  "remote-sync": {}
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.27.6
atom-ternjs, v0.6.2
file-icons, v1.5.5
git-projects, v1.14.1
language-jade, v0.4.0
linter, v0.12.6
linter-coffeelint, v0.2.3
remote-sync, v3.1.1
wakatime, v4.0.9

# Dev
No dev packages
```

**Comment by yongkangchen** [comment]
It is the issue of v2.x. so we can only ignore it. Thanks anyway
