### ISSUE TITLE
Uncaught TypeError: Cannot read property 'dispose' of undefined

### ISSUE THREAD

**Issue by ktrhn** [yongkangchen/remote-sync#143]
1. Right click on project folder (multiple projects are open)
2. Click on Remove Project Folder

**Atom Version**: 0.201.0
**System**: Mac OS X 10.10.3
**Thrown From**: [remote-sync](https://github.com/yongkangchen/remote-sync) package, v3.1.1

### Stack Trace

Uncaught TypeError: Cannot read property 'dispose' of undefined

```
At /Users/sh/.atom/packages/remote-sync/index.coffee:26

TypeError: Cannot read property 'dispose' of undefined
  at initProject (/Users/sh/.atom/packages/remote-sync/index.coffee:26:29)
  at /Users/sh/.atom/packages/remote-sync/index.coffee:86:7
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Project.module.exports.Project.removePath (/Applications/Atom.app/Contents/Resources/app.asar/src/project.js:306:22)
  at TreeView.module.exports.TreeView.removeProjectFolder (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tree-view/lib/tree-view.js:1013:31)
  at space-pen-div.atom.commands.add.tree-view:remove-project-folder (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tree-view/lib/tree-view.js:313:26)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:153:19)
  at [object Object].jQuery.fn.trigger (/Applications/Atom.app/Contents/Resources/app.asar/src/space-pen-extensions.js:64:23)
  at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:76:67)
  at emitTwo (events.js:87:13)
  at EventEmitter.emit (events.js:169:7)
  at EventEmitter.ipc.sendSync (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/ipc.js:21:31)
  at BrowserWindow.RemoteMemberFunction [as emit] (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:110:29)
  at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/context-menu-manager.js:170:31)
  at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:149:33)
  at HTMLDocument.handler (/Applications/Atom.app/Contents/Resources/app.asar/src/space-pen-extensions.js:112:34)
  at HTMLDocument.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/space-pen/vendor/jquery.js:4681:9)
  at HTMLDocument.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/space-pen/vendor/jquery.js:4359:46)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "feedback",
      "deprecation-cop",
      "atom-lint",
      "linter-jshint"
    ],
    "themes": [
      "seti-ui",
      "seti-monokai"
    ],
    "projectHome": "/Users/sh/Developer",
    "excludeVcsIgnoredPaths": false
  }
}
```

### Installed Packages

```coffee
# User
autoclose-html, v0.16.2
better-handlebars, v0.1.1
docblockr, v0.7.2
editorconfig, v1.0.0
highlight-line, v0.10.2
language-ember-script, v0.1.0
language-volt, v0.2.2
linter, v0.12.6
linter-csslint, v0.0.13
linter-eslint, v0.5.8
linter-handlebars, v0.1.1
linter-less, v0.4.0
linter-php, v0.0.15
linter-phpcs, v0.0.15
linter-phpmd, v0.0.11
linter-scss-lint, v1.0.4
remember-session, v0.5.1
remote-sync, v3.1.1
seti-monokai, v0.3.1
seti-ui, v0.7.1
tabs-to-spaces, v0.11.0
zentabs, v0.8.4

# Dev
No dev packages
```

**Comment by roelofr** [comment]
This error also shows in case there is just one project open.

**Comment by Joegameplay** [comment]
This error is very hit and miss, sometimes it will occur with multiple projects open but will definitely occur if I only have a single project open.

**Comment by DFallas** [comment]
Hi regarding the one proyect question, yes it does, happen to me with just one project open

**Comment by sniffarte** [comment]
Same issue on Windows.

**Comment by AndrewLosev** [comment]
The same issue on Windows 10.

**Comment by ramumb** [comment]
Yep. I've get it on both Windows 7 and Windows 10.

**Comment by Maelstrome26** [comment]
Can confirm on Windows 10 and Mac OS X Mavericks.

**Comment by drawcard** [comment]
Mac OS X Yosemite +1

**Comment by calvinpy** [comment]
The same issue.

It occurs only when I try to save/sync a file and this file has a parent directory that was created with "Add Project Folder" option.

When I try to delete this *project folder* I get the same trace.

```sh
Uncaught TypeError: Cannot read property 'dispose' of undefined

:path/.atom/packages/remote-sync/index.coffee:26
Hide Stack Trace
TypeError: Cannot read property 'dispose' of undefined
    at initProject (:path/.atom/packages/remote-sync/index.coffee:26:29)
    at :path/.atom/packages/remote-sync/index.coffee:86:7
...
```

**Comment by ErmanSayin** [comment]
Same issue on Windows 10, really annoying.
