### ISSUE TITLE
Uncaught TypeError: Cannot read property 'uploadFile' of undefined

### ISSUE THREAD

**Issue by laffan** [yongkangchen/remote-sync#147]
[Enter steps to reproduce below:]

1. Right click : 'Upload File' (worked before most recent update)

**Atom Version**: 0.201.0
**System**: Mac OS X 10.10.3
**Thrown From**: [remote-sync](https://github.com/yongkangchen/remote-sync) package, v3.1.1

### Stack Trace

Uncaught TypeError: Cannot read property 'uploadFile' of undefined

```
At /Users/paddy/.atom/packages/remote-sync/index.coffee:64

TypeError: Cannot read property 'uploadFile' of undefined
  at handleEvent (/Users/paddy/.atom/packages/remote-sync/index.coffee:64:29)
  at atom-workspace.disposables.add.atom.commands.add.remote-sync:upload-file (/Users/paddy/.atom/packages/remote-sync/index.coffee:76:40)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:153:19)
  at [object Object].jQuery.fn.trigger (/Applications/Atom.app/Contents/Resources/app.asar/src/space-pen-extensions.js:64:23)
  at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:76:67)
  at emitTwo (events.js:87:13)
  at EventEmitter.emit (events.js:169:7)
  at EventEmitter.ipc.sendSync (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/ipc.js:21:31)
  at BrowserWindow.RemoteMemberFunction [as emit] (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:110:29)
  at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/context-menu-manager.js:170:31)
  at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:149:33)
  at HTMLDocument.handler (/Applications/Atom.app/Contents/Resources/app.asar/src/space-pen-extensions.js:112:34)
  at HTMLDocument.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/space-pen/vendor/jquery.js:4681:9)
  at HTMLDocument.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/space-pen/vendor/jquery.js:4359:46)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "one-light-ui",
      "tomorrow-night-eighties-syntax"
    ],
    "disabledPackages": [
      "autocomplete-css"
    ]
  },
  "remote-sync": {}
}
```

### Installed Packages

```coffee
# User
autocomplete-php, v0.3.6
emmet, v2.3.10
highlight-line, v0.10.2
project-manager, v1.15.7
remote-sync, v3.1.1
synced-sidebar, v0.2.3
tomorrow-night-eighties-syntax, v0.6.1

# Dev
No dev packages
```

**Comment by adamclaxon** [comment]
Same issue here.

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.209.0
**System**: Mac OS X 10.10.3
**Thrown From**: [remote-sync](https://github.com/yongkangchen/remote-sync) package, v3.1.2


### Stack Trace

Uncaught TypeError: Cannot read property 'uploadFile' of undefined

```
At /Users/adam/Dropbox (Personal)/Application Support/.atom/packages/remote-sync/index.coffee:64

TypeError: Cannot read property 'uploadFile' of undefined
  at handleEvent (/Users/adam/Dropbox (Personal)/Application Support/.atom/packages/remote-sync/index.coffee:64:29)
  at atom-workspace.disposables.add.atom.commands.add.remote-sync:upload-file (/Users/adam/Dropbox (Personal)/Application Support/.atom/packages/remote-sync/index.coffee:76:40)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:153:19)
  at [object Object].jQuery.fn.trigger (/Applications/Atom.app/Contents/Resources/app.asar/src/space-pen-extensions.js:64:23)
  at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:75:67)
  at emitTwo (events.js:87:13)
  at EventEmitter.emit (events.js:169:7)
  at EventEmitter.ipc.sendSync (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/ipc.js:21:31)
  at BrowserWindow.RemoteMemberFunction [as emit] (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:110:29)
  at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/context-menu-manager.js:170:31)
  at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:148:33)
  at HTMLDocument.handler (/Applications/Atom.app/Contents/Resources/app.asar/src/space-pen-extensions.js:112:34)
  at HTMLDocument.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/space-pen/vendor/jquery.js:4681:9)
  at HTMLDocument.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/space-pen/vendor/jquery.js:4359:46)

```

### Commands

```
     -1:40.6.0 editor:select-to-end-of-line (atom-text-editor.editor.is-focused)
  2x -1:39.7.0 core:select-down (atom-text-editor.editor.is-focused)
     -1:39.1.0 core:copy (atom-text-editor.editor.is-focused)
 10x -1:38.5.0 core:move-up (atom-text-editor.editor.is-focused)
     -1:36.9.0 core:paste (atom-text-editor.editor.is-focused)
  2x -1:35.8.0 core:move-down (atom-text-editor.editor.is-focused)
     -1:34.6.0 editor:select-to-end-of-line (atom-text-editor.editor.is-focused)
     -1:34.2.0 core:select-to-bottom (atom-text-editor.editor.is-focused)
  2x -1:33.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:32.3.0 core:save (atom-text-editor.editor.is-focused)
     -1:31 core:close (atom-text-editor.editor.is-focused)
     -1:12.9.0 command-palette:toggle (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:52.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -0:45.9.0 project-manager:toggle (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:44.3.0 command-palette:toggle (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-oceanic-reef-syntax.theme-one-dark-ui)
     -0:36.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "wrap-guide",
      "welcome",
      "Zen",
      "background-tips",
      "autoclose-html",
      "editor-stats",
      "language-liquid",
      "css-color-highlighting"
    ],
    "audioBeep": false,
    "themes": [
      "one-dark-ui",
      "oceanic-reef-syntax"
    ]
  },
  "remote-sync": {}
}
```

### Installed Packages

```coffee
# User
atomatigit, v1.5.3
emmet, v2.3.10
file-icons, v1.5.7
flex-tool-bar, v0.4.2
foldingtext-for-atom, v0.4.4
minimap, v4.9.4
oceanic-reef-syntax, v0.6.0
project-manager, v1.15.10
remote-sync, v3.1.2
tool-bar, v0.1.7
tool-bar-main, v0.0.8
webbox-color, v0.5.7

# Dev
No dev packages
```

**Comment by elvismdev** [comment]
Same here, tried setting `"uploadOnSave": true` like @aaronmoodie did on https://github.com/yongkangchen/remote-sync/issues/169#issuecomment-116735527 but didn't work either. 

Any other fix/solution to this?

**Comment by n0mad01** [comment]
I had this issue after installing remote-sync and restarting Atom then adding the .remote-sync.json file and trying to upload/sync.

After another restart of Atom everything is fine.

**Comment by hassanmian** [comment]
@n0mad01 Same here. Just restarted Atom and now it works!

**Comment by moosmaa** [comment]
I've had this issue for the past month. I've restarted over and over and even tried reinstalling the package, but it still isn't working...

**Comment by yongkangchen** [comment]
sorry for the issue, this error means that upload file does not belong to the project or the project not configure with remote-sync yet.

**Comment by yongkangchen** [comment]
You can update this package to the latest and check config, then try again

**Comment by daverogers** [comment]
Restarting Atom fixed this error for me, cheers.

**Comment by jirsbek** [comment]
Also having this issue. Restarting Atom unfortunately doesn't help. Upload of the file in root where .remote-sync.json is works fine. Files in other directories won't upload.

**Comment by jirsbek** [comment]
It seems that problem occurs after adding multiple project folders to the project (via Project Manager package).

**Comment by daverogers** [comment]
If that's true, just another reason to support Project Manager configuration (issue #225) ;)

**Comment by gvvsnreddy** [comment]
Hi @yongkangchen 

Recently I have installed remote-sync in my atom editor.  I got the below error when I try to upload a file to server. Can you please check the below issues and help me on this? 


TypeError: Cannot read property 'uploadFile' of undefined
    at handleEvent (file:///C:/Users/John/.atom/packages/remote-sync/index.coffee:45:28)
    at HTMLElement.remote-sync:upload-file (file:///C:/Users/John/.atom/packages/remote-sync/index.coffee:100:40)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\John\AppData\Local\atom\app-1.19.2\resources\app\src\command-registry.js:265:35)
    at CommandRegistry.handleCommandEvent (C:\Users\John\AppData\Local\atom\app-1.19.2\resources\app\src\command-registry.js:3:65)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\John\AppData\Local\atom\app-1.19.2\resources\app\src\command-registry.js:166:25)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (C:\Users\John\AppData\Local\atom\app-1.19.2\resources\app\src\atom-environment.js:1344:34)
    at EventEmitter.outerCallback (C:\Users\John\AppData\Local\atom\app-1.19.2\resources\app\src\application-delegate.js:347:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)


Below is my .remote-sync.json 

{
  "uploadOnSave": true,
  "useAtomicWrites": false,
  "deleteLocal": false,
  "hostname": "75.101.109.113",
  "port": "22",
  "target": "/dev01_testing/",
  "ignore": [
    ".remote-sync.json",
    ".git/**"
  ],
  "username": "JohnDev",
  "password": "Test!87*",
  "watch": [],
  "transport": "scp"
}

Thanks in Advance.

**Comment by 1v3ry** [comment]
This error also occurred to me, when i accidentally added a subfolder of a project folder as a project folder itself. it can be solved by removing the subfolder from the project folders.

**Comment by hobbit44** [comment]
I found a fix, i think. i copy the configuration file between projects and get this issue. i just found that if i just open the configuration panel and save it started working.

**Comment by mrthebob** [comment]
@Hobbit44 - that fix didn't work for me. I'm also sporadically having files that won't upload on save (while others will), but I get this same error when Right clicking > Upload

**Comment by wdecoster** [comment]
It might just help someone who made the same ridiculous mistake as I did: you also get this error if you make a typo in the `.remote-sync.json` filename, such as using an underscore instead of a dash...
