### ISSUE TITLE
after 3.1.1 update remote-sync doesn't work anymore

### ISSUE THREAD

**Issue by 0x746f6d** [yongkangchen/remote-sync#148]
remote-sync worked perfectly for me but after the 3.1.1 update it doesn't do anything anymore. no error message, nothing. it doesn't sync any files.

i know this bug report probably isn't very helpful but i don't know where to start looking for more details about the issue. :)

**Comment by yongkangchen** [comment]
you can try to add `console.log` code to coffeescript files in ~/.atom/package/remote-sync, to debug where it stops.

**Comment by 0x746f6d** [comment]
i have added console.log() to every method in RemoteSync.coffee.
hm... the constructor and initIgnore get called but afterwards no method gets called anymore (of course i tried saving some files in my project).

**Comment by LordZepto** [comment]
I've been having the same problem, on save, nothing happens. Today I tried to force an upload of a folder or a file (in the tree view, right click, Remote Sync, upload folder, or upload file) and i get an error _Uncaught TypeError: Cannot read property 'uploadFile' of undefined_. 

If there is something I can try, just let me know.

**Comment by yongkangchen** [comment]
@LordZepto can you give the stack trace of `Uncaught TypeError: Cannot read property 'uploadFile' of undefined` ?

**Comment by yongkangchen** [comment]
@0x746f6d can you try as @LordZepto said?
> tried to force an upload of a folder or a file (in the tree view, right click, Remote Sync, upload folder, or upload file)

**Comment by LordZepto** [comment]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.204.0
**System**: Mac OS X 10.10.4
**Thrown From**: [remote-sync](https://github.com/yongkangchen/remote-sync) package, v3.1.1


### Stack Trace

Uncaught TypeError: Cannot read property 'uploadFolder' of undefined

```
At /Users/tomassolerramirez/.atom/packages/remote-sync/index.coffee:66

TypeError: Cannot read property 'uploadFolder' of undefined
  at handleEvent (/Users/tomassolerramirez/.atom/packages/remote-sync/index.coffee:66:29)
  at atom-workspace.disposables.add.atom.commands.add.remote-sync:upload-folder (/Users/tomassolerramirez/.atom/packages/remote-sync/index.coffee:78:42)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:153:19)
  at [object Object].jQuery.fn.trigger (/Applications/Atom.app/Contents/Resources/app.asar/src/space-pen-extensions.js:64:23)
  at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:76:67)
  at emitTwo (events.js:87:13)
  at EventEmitter.emit (events.js:169:7)
  at EventEmitter.ipc.sendSync (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/ipc.js:21:31)
  at BrowserWindow.RemoteMemberFunction [as emit] (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:110:29)
  at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/context-menu-manager.js:170:31)
  at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:149:33)
  at HTMLDocument.handler (/Applications/Atom.app/Contents/Resources/app.asar/src/space-pen-extensions.js:112:34)
  at HTMLDocument.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/space-pen/vendor/jquery.js:4681:9)
  at HTMLDocument.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/space-pen/vendor/jquery.js:4359:46)

```

### Commands

```
     -1:06.2.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-atom-dark-ui)
     -0:21.7.0 tree-view:toggle (ul.list-inline.tab-bar.inset-panel)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "disabledPackages": [
      "linter-jshint",
      "linter-jscs"
    ]
  },
  "remote-sync": {}
}
```

### Installed Packages

```coffee
# User
aligner-scss, v1.0.1
docblockr, v0.7.2
emmet, v2.3.10
language-SCSS, v0.4.0
language-smarty, v1.0.0
linter, v0.12.6
linter-csslint, v0.0.13
linter-php, v0.0.15
linter-scss-lint, v1.0.4
linter-tidy, v1.0.1
remote-sync, v3.1.1
tabs-to-spaces, v0.11.0

# Dev
No dev packages
```

**Comment by LordZepto** [comment]
BTW @yongkangchen atom redirects me to #142 when the error pops up.

**Comment by LordZepto** [comment]
Keeps failing with v3.1.2
This is the stack trace of "upload file"
[Enter steps to reproduce below:]

1. Right button over file
2. Remote Sync > Upload File

**Atom Version**: 0.204.0
**System**: Mac OS X 10.10.4
**Thrown From**: [remote-sync](https://github.com/yongkangchen/remote-sync) package, v3.1.2


### Stack Trace

Uncaught TypeError: Cannot read property 'uploadFile' of undefined

```
At /Users/tomassolerramirez/.atom/packages/remote-sync/index.coffee:64

TypeError: Cannot read property 'uploadFile' of undefined
  at handleEvent (/Users/tomassolerramirez/.atom/packages/remote-sync/index.coffee:64:29)
  at atom-workspace.disposables.add.atom.commands.add.remote-sync:upload-file (/Users/tomassolerramirez/.atom/packages/remote-sync/index.coffee:76:40)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:153:19)
  at [object Object].jQuery.fn.trigger (/Applications/Atom.app/Contents/Resources/app.asar/src/space-pen-extensions.js:64:23)
  at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:76:67)
  at emitTwo (events.js:87:13)
  at EventEmitter.emit (events.js:169:7)
  at EventEmitter.ipc.sendSync (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/ipc.js:21:31)
  at BrowserWindow.RemoteMemberFunction [as emit] (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:110:29)
  at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/context-menu-manager.js:170:31)
  at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:149:33)
  at HTMLDocument.handler (/Applications/Atom.app/Contents/Resources/app.asar/src/space-pen-extensions.js:112:34)
  at HTMLDocument.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/space-pen/vendor/jquery.js:4681:9)
  at HTMLDocument.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/space-pen/vendor/jquery.js:4359:46)

```

### Commands

```
     -0:56.1.0 editor:select-to-end-of-line (atom-text-editor.editor.is-focused)
     -0:55.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:43.7.0 core:move-down (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:43.4.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:43.4.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:42.9.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:42 core:move-down (atom-text-editor.editor.is-focused)
     -0:41.2.0 editor:select-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -0:40.7.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:40 core:move-up (atom-text-editor.editor.is-focused)
     -0:39.7.0 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
 10x -0:39.3.0 core:select-down (atom-text-editor.editor.is-focused)
     -0:37.6.0 editor:select-to-end-of-line (atom-text-editor.editor.is-focused)
     -0:36.9.0 emmet:toggle-comment (atom-text-editor.editor.is-focused)
     -0:36.9.0 editor:toggle-line-comments (atom-text-editor.editor.is-focused)
 16x -0:36.5.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "disabledPackages": [
      "linter-jshint",
      "linter-jscs"
    ]
  },
  "remote-sync": {}
}
```

### Installed Packages

```coffee
# User
aligner-scss, v1.0.1
docblockr, v0.7.2
emmet, v2.3.10
language-SCSS, v0.4.0
language-smarty, v1.0.0
linter, v0.12.6
linter-csslint, v0.0.13
linter-php, v0.0.15
linter-scss-lint, v1.0.4
linter-tidy, v1.0.1
remote-sync, v3.1.2
tabs-to-spaces, v0.11.0

# Dev
No dev packages
```

**Comment by 0x746f6d** [comment]
no, i don't get any errors. nothing happens if i force an upload in the tree view.

> @0x746f6d can you try as @LordZepto said?
>
> tried to force an upload of a folder or a file (in the tree view, right click, Remote Sync, upload folder, or upload file)

**Comment by yongkangchen** [comment]
sorry for the issue, this error means that upload file does not belong to the project or the project not configure with remote-sync yet.

**Comment by yongkangchen** [comment]
You can update this package to the latest and check config, then try again
