### ISSUE TITLE
Uncaught Error: Encrypted private key detected, but no passphrase given

### ISSUE THREAD

**Issue by swarajban** [yongkangchen/remote-sync#155]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.207.0
**System**: Mac OS X 10.10.3
**Thrown From**: [remote-sync](https://github.com/yongkangchen/remote-sync) package, v3.1.2

### Stack Trace

Uncaught Error: Encrypted private key detected, but no passphrase given

```
At /Users/swaraj/.atom/packages/remote-sync/node_modules/ssh2/lib/Connection.js:279

Error: Encrypted private key detected, but no passphrase given
    at Connection.connect (/Users/swaraj/.atom/packages/remote-sync/node_modules/ssh2/lib/Connection.js:279:15)
    at ScpTransport.module.exports.ScpTransport._getConnection (/Users/swaraj/.atom/packages/remote-sync/lib/transports/ScpTransport.coffee:172:18)
    at ScpTransport.module.exports.ScpTransport.upload (/Users/swaraj/.atom/packages/remote-sync/lib/transports/ScpTransport.coffee:35:19)
    at UploadListener.module.exports.UploadListener.uploadFile (/Users/swaraj/.atom/packages/remote-sync/lib/UploadListener.coffee:27:24)
    at q.process (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/async/lib/async.js:769:21)
    at process._tickCallback (node.js:357:13)
```

### Commands

```
     -1:08.3.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -1:02.4.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -1:00.7.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -1:00.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:00.3.0 remote-sync:configure (atom-text-editor.editor)
  2x -0:54.6.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:53.1.0 core:delete (atom-text-editor.editor.is-focused)
     -0:51.9.0 core:save (atom-text-editor.editor.is-focused)
     -0:35.7.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:33.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:33.5.0 remote-sync:configure (atom-text-editor.editor)
  2x -0:13 core:paste (atom-text-editor.editor.mini.is-focused)
  2x -0:05.4.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:03.8.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:03.7.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -0:01.4.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {},
  "remote-sync": {}
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.0
autocomplete-paths, v1.0.2
language-chef, v0.4.0
php-twig, v4.0.0
project-manager, v1.15.10
remote-sync, v3.1.2
symbols-tree-view, v0.9.3
synced-sidebar, v0.4.0

# Dev
No dev packages
```

**Comment by Babelfisch** [comment]
Is there a fix available for this bug?

**Comment by yongkangchen** [comment]
@Babelfisch it is not a bug. It means that you must config passphrase  for Encrypted private key.
see "passphrase -- Passphrase for the SSH key (only used for SCP)" in https://github.com/yongkangchen/remote-sync#usage

**Comment by RangerGH** [comment]
Can we have an option to be prompted.  I really don't want my passphrase in a file.

**Comment by DavBE** [comment]
Hi, I just noticed there's an option to use an agent. That might be the best way to go for password protected key files.
