### ISSUE TITLE
ignore pattern on "uploadMirrors" doesn't work

### ISSUE THREAD

**Issue by maxnowack** [yongkangchen/remote-sync#156]
**Atom Version**: 0.208.0
**System**: Mac OS X 10.10.3
**Thrown From**: [remote-sync](https://github.com/yongkangchen/remote-sync) package, v3.1.2

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:759

TypeError: undefined is not a function
  at RemoteSync.initIgnore (/Users/maxnowack/.atom/packages/remote-sync/lib/RemoteSync.coffee:33:27)
  at RemoteSync.getUploadMirrors (/Users/maxnowack/.atom/packages/remote-sync/lib/RemoteSync.coffee:118:10)
  at RemoteSync.uploadFile (/Users/maxnowack/.atom/packages/remote-sync/lib/RemoteSync.coffee:71:5)
  at /Users/maxnowack/.atom/packages/remote-sync/index.coffee:101:20
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1016:20)
  at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:998:19)
  at TextEditor.module.exports.TextEditor.save (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:579:26)
  at Pane.module.exports.Pane.saveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:523:18)
  at Pane.module.exports.Pane.saveActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:506:19)
  at Workspace.module.exports.Workspace.saveActivePaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:585:35)
  at atom-workspace.atom.commands.add.core:save (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace-element.js:317:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:177:20)

```

### Commands

```
     -0:02.4.0 core:move-to-top (atom-text-editor.editor.is-focused)
     -0:01.7.0 core:delete (atom-text-editor.editor.is-focused)
     -0:01.2.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "metrics",
      "atom-beautify",
      "minimap",
      "Dyslexia",
      "auto-update-packages"
    ],
    "themes": [
      "one-dark-ui",
      "one-dark-syntax"
    ],
    "audioBeep": false
  },
  "remote-sync": {}
}
```

### Installed Packages

```coffee
# User
Stylus, v1.0.0
atom-color-highlight, v3.0.9
autoclose-html, v0.17.1
color-picker, v2.0.4
css-snippets, v0.8.0
file-icons, v1.5.7
language-smarty-php, v0.5.0
linter, v0.12.7
linter-coffeelint, v0.3.2
linter-php, v0.0.15
project-palette-finder, v2.4.17
remote-sync, v3.1.2
terminal-status, v1.6.8
underscorejs-snippets, v0.2.2
word-jumper, v0.3.0

# Dev
No dev packages
```

**Comment by yongkangchen** [comment]
uploadMirrors dose not share ignore, see README, you should config ignore for each one?
