### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '~/.ssh/id_rsa'

### ISSUE THREAD

**Issue by lisi1987** [yongkangchen/remote-sync#161]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.210.0
**System**: Mac OS X 10.10.3
**Thrown From**: [remote-sync](https://github.com/yongkangchen/remote-sync) package, v3.1.2

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '~/.ssh/id_rsa'

```
At fs.js:519

Error: ENOENT: no such file or directory, open '~/.ssh/id_rsa'
  at Error (native)
  at Object.fs.openSync (fs.js:544:18)
  at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:118:20)
  at Object.fs.readFileSync (fs.js:396:15)
  at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:369:29)
  at ScpTransport.module.exports.ScpTransport._getConnection (/Users/Kevin/.atom/packages/remote-sync/lib/transports/ScpTransport.coffee:121:23)
  at ScpTransport.module.exports.ScpTransport.download (/Users/Kevin/.atom/packages/remote-sync/lib/transports/ScpTransport.coffee:53:6)
  at RemoteSync.diffFile (/Users/Kevin/.atom/packages/remote-sync/lib/RemoteSync.coffee:129:21)
  at handleEvent (/Users/Kevin/.atom/packages/remote-sync/index.coffee:38:14)
  at atom-workspace.disposables.add.atom.commands.add.remote-sync:diff-file (/Users/Kevin/.atom/packages/remote-sync/index.coffee:79:38)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:159:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
  at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:180:20)

```

### Commands

```
     -1:08.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  3x -1:07.9.0 core:move-down (atom-text-editor.editor.mini.is-focused)
  2x -1:06.7.0 core:move-up (atom-text-editor.editor.mini.is-focused)
     -1:06.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -1:05.5.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -1:04.1.0 core:move-up (atom-text-editor.editor.mini.is-focused)
     -1:02.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:18 vim-mode:insert-after (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:17.6.0 core:move-left (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
  2x -0:16.9.0 core:backspace (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:14.7.0 core:save (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:10 command-palette:toggle (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:06.6.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:04.7.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:04.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:04.3.0 remote-sync:diff-file (atom-text-editor.editor.vim-mode.insert-mode)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "atom-color-highlight",
      "preview-tabs",
      "git-control",
      "terminal-status",
      "tool-bar"
    ],
    "themes": [
      "one-dark-ui",
      "spacegray-dark-syntax"
    ]
  },
  "remote-sync": {}
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.27.12
autoclose-html, v0.17.1
autocomplete-clang, v0.7.0
autocomplete-paths, v1.0.2
color-picker, v2.0.4
file-icons, v1.5.7
flex-tool-bar, v0.4.2
highlight-line, v0.10.2
linter, v0.12.6
linter-clang, v2.26.0
linter-csslint, v0.0.13
linter-htmlhint, v0.0.16
linter-jshint, v0.1.6
linter-jsxhint, v0.1.2
markdown-preview-plus, v1.5.0
minimap, v4.9.4
minimap-highlight-selected, v4.3.0
pretty-json, v0.3.3
project-manager, v1.15.10
react, v0.12.0
remote-edit, v1.8.2
remote-sync, v3.1.2
spacegray-dark-syntax, v0.2.0
tool-bar-main, v0.0.8
vim-mode, v0.51.0

# Dev
No dev packages
```

**Comment by yongkangchen** [comment]
please use absolute path of key file, and try again

**Comment by providen-rob** [comment]
I have the same problem.  Absolute path for the key file made no difference.
