### ISSUE TITLE
Uncaught Error: Unable to parse given privateKey value

### ISSUE THREAD

**Issue by jegra** [yongkangchen/remote-sync#163]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.210.0
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [remote-sync](https://github.com/yongkangchen/remote-sync) package, v3.1.2

### Stack Trace

Uncaught Error: Unable to parse given privateKey value

```
At C:\Users\Joe\.atom\packages\remote-sync\node_modules\ssh2\lib\Connection.js:274

Error: Unable to parse given privateKey value
  at Connection.connect (C:\Users\Joe\.atom\packages\remote-sync\node_modules\ssh2\lib\Connection.js:274:13)
  at ScpTransport.module.exports.ScpTransport._getConnection (C:\Users\Joe\.atom\packages\remote-sync\lib\transports\ScpTransport.coffee:125:16)
  at ScpTransport.module.exports.ScpTransport.upload (C:\Users\Joe\.atom\packages\remote-sync\lib\transports\ScpTransport.coffee:24:6)
  at UploadListener.module.exports.UploadListener.uploadFile (C:\Users\Joe\.atom\packages\remote-sync\lib\UploadListener.coffee:18:15)
  at q.process (C:\Users\Joe\AppData\Local\atom\app-0.210.0\resources\app.asar\node_modules\async\lib\async.js:769:21)
  at process._tickCallback (node.js:357:13)
  at EventEmitter.ipc.sendSync (C:\Users\Joe\AppData\Local\atom\app-0.210.0\resources\atom.asar\renderer\api\lib\ipc.js:21:31)
  at BrowserWindow.RemoteMemberFunction [as emit] (C:\Users\Joe\AppData\Local\atom\app-0.210.0\resources\atom.asar\renderer\api\lib\remote.js:110:29)
  at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (C:\Users\Joe\AppData\Local\atom\app-0.210.0\resources\app.asar\src\context-menu-manager.js:170:31)
  at HTMLDocument.<anonymous> (C:\Users\Joe\AppData\Local\atom\app-0.210.0\resources\app.asar\src\window-event-handler.js:150:33)
  at HTMLDocument.handler (C:\Users\Joe\AppData\Local\atom\app-0.210.0\resources\app.asar\src\space-pen-extensions.js:112:34)
  at HTMLDocument.jQuery.event.dispatch (C:\Users\Joe\AppData\Local\atom\app-0.210.0\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4681:9)
  at HTMLDocument.elemData.handle (C:\Users\Joe\AppData\Local\atom\app-0.210.0\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4359:46)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "SFTP-deployment"
    ]
  },
  "remote-sync": {}
}
```

### Installed Packages

```coffee
# User
color-picker, v2.0.6
language-blade, v0.14.0
linter, v0.12.7
linter-jshint, v0.1.6
linter-php, v0.0.15
minimap, v4.10.0
remote-sync, v3.1.2
tabs-to-spaces, v0.11.0

# Dev
No dev packages
```

**Comment by jegra** [comment]
Converting key to alternate format resolved the issue.

**Comment by hull-aaron** [comment]
@jegra what do you mean by alternate format.

**Comment by DerPapst** [comment]
@hull-aaron: openssl format
