### ISSUE TITLE
Uncaught Error: Cannot find module 'fs-plus'

### ISSUE THREAD

**Issue by romannmk** [yongkangchen/remote-sync#165]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.210.0
**System**: Mac OS X 10.10.3
**Thrown From**: [remote-sync](https://github.com/yongkangchen/remote-sync) package, v3.1.2

### Stack Trace

Uncaught Error: Cannot find module 'fs-plus'

```
At module.js:330

Error: Cannot find module 'fs-plus'
    at Module._resolveFilename (module.js:328:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.<anonymous> (/Users/krd/.atom/packages/remote-sync-master/lib/RemoteSync.coffee:6:8)
    at Object.<anonymous> (/Users/krd/.atom/packages/remote-sync-master/lib/RemoteSync.coffee:282:4)
    at Module._compile (module.js:452:26)
    at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
    at Module.load (module.js:347:32)
```

### Commands

```
     -2:37.3.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  5x -2:31.8.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -2:28 core:move-up (atom-text-editor.editor.mini.is-focused)
  2x -2:27.1.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -2:25 core:confirm (atom-text-editor.editor.mini.is-focused)
     -2:25 settings-view:view-installed-packages (atom-text-editor.editor)
  2x -2:11 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {},
  "remote-sync": {}
}
```

### Installed Packages

```coffee
# User
Remote-FTP, v0.7.1
emmet, v2.3.10
minimap, v4.10.0
remote-sync, v3.1.2

# Dev
No dev packages
```

**Comment by yongkangchen** [comment]
How did you install remote-sync package?

**Comment by d-griffin-dev** [comment]
[Enter steps to reproduce below:]

1. I installed this package by downloading and extracting the zip file to .atom/packages/ on my Windows 7 computer.

**Atom Version**: 1.0.0
**System**: Microsoft Windows 7 Enterprise 
**Thrown From**: [remote-sync-master](https://github.com/yongkangchen/remote-sync) package, vundefined


### Stack Trace

Failed to activate the remote-sync package

```
At Cannot find module 'fs-plus'

Error: Cannot find module 'fs-plus'
    at Module._resolveFilename (module.js:328:15)
    at Function.Module._resolveFilename (C:\Users\daniel.griffin\AppData\Local\atom\app-1.0.0\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.<anonymous> (/C:/Users/daniel.griffin/.atom/packages/remote-sync-master/lib/RemoteSync.coffee:6:8)
    at Object.<anonymous> (/C:/Users/daniel.griffin/.atom/packages/remote-sync-master/lib/RemoteSync.coffee:282:4)
    at Module._compile (module.js:452:26)
    at Object.requireCoffeeScript (C:\Users\daniel.griffin\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\coffee-cash\lib\coffee-cash.js:85:19)
    at Module.load (module.js:347:32)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "seti-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-alignment, v0.12.1
emmet, v2.3.10
jshint, v1.3.7
remote-edit, v1.8.2
seti-syntax, v0.4.0
seti-ui, v0.7.1

# Dev
No dev packages
```

**Comment by yongkangchen** [comment]
you should run `apm install` at `.atom/packages/remote-sync/` to install dependencies
