### ISSUE TITLE
Uncaught Error: [remote-sync] invalid transport: undefined in 

### ISSUE THREAD

**Issue by danibai** [yongkangchen/remote-sync#166]
[Enter steps to reproduce below:]

1. Download from Server

**Atom Version**: 0.211.0
**System**: Mac OS X 10.10.4
**Thrown From**: [remote-sync](https://github.com/yongkangchen/remote-sync) package, v3.1.2

### Stack Trace

Uncaught Error: [remote-sync] invalid transport: undefined in /Users/dba/Documents/macmac/Workspace/Baier/live/.remote-sync.json

```
At /Users/dba/.atom/packages/remote-sync/lib/RemoteSync.coffee:104

Error: [remote-sync] invalid transport: undefined in /Users/dba/Documents/macmac/Workspace/Baier/live/.remote-sync.json
  at RemoteSync.createTransport (/Users/dba/.atom/packages/remote-sync/lib/RemoteSync.coffee:104:17)
  at RemoteSync.getTransport (/Users/dba/.atom/packages/remote-sync/lib/RemoteSync.coffee:110:19)
  at RemoteSync.uploadFile (/Users/dba/.atom/packages/remote-sync/lib/RemoteSync.coffee:70:37)
  at /Users/dba/.atom/packages/remote-sync/lib/RemoteSync.coffee:93:8
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/fs-plus/lib/fs-plus.js:399:17
  at FSReqWrap.oncomplete (fs.js:77:15)
  at EventEmitter.ipc.sendSync (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/ipc.js:21:31)
  at BrowserWindow.RemoteMemberFunction [as emit] (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:110:29)
  at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/context-menu-manager.js:170:31)
  at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:150:33)
  at HTMLDocument.handler (/Applications/Atom.app/Contents/Resources/app.asar/src/space-pen-extensions.js:112:34)
  at HTMLDocument.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/space-pen/vendor/jquery.js:4681:9)
  at HTMLDocument.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/space-pen/vendor/jquery.js:4359:46)

```

### Commands

```
     -4:27.8.0 core:paste (atom-text-editor.editor.is-focused)
     -4:19.8.0 core:save (atom-text-editor.editor.is-focused)
     -4:07.5.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  3x -4:03.9.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -3:49.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -3:49.8.0 atom-sync:upload-file (atom-text-editor.editor)
     -3:38 command-palette:toggle (atom-text-editor.editor.is-focused)
     -3:35.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -3:35.1.0 atom-sync:upload-file (atom-text-editor.editor)
  2x -1:08.1.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:27.4.0 core:copy (atom-text-editor.editor.is-focused)
     -0:26.3.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:26.1.0 core:paste (atom-text-editor.editor.is-focused)
     -0:19.3.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:16.6.0 core:paste (atom-text-editor.editor.is-focused)
     -0:10 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "newton-dark-ui",
      "newton-dark-syntax"
    ]
  },
  "remote-sync": {}
}
```

### Installed Packages

```coffee
# User
file-icons, v1.5.7
git-log, v0.4.1
minimap, v4.10.0
newton-dark-syntax, v1.1.5
newton-dark-ui, v1.0.5
project-view, v0.1.2
remote-sync, v3.1.2
save-session, v0.15.5
tree-view-git-projects, v0.5.0
tree-view-git-status, v0.1.1

# Dev
No dev packages
```

**Comment by yongkangchen** [comment]
please check `transport ` in your .remote-sync config, should be `scp` or `ftp`
