### ISSUE TITLE
Uncaught TypeError: Cannot read property 'downloadFolder' of undefined

### ISSUE THREAD

**Issue by dinoDachi** [yongkangchen/remote-sync#167]
[Enter steps to reproduce below:]

1. Right click folder > download folder
2. ...

**Atom Version**: 0.211.0
**System**: Mac OS X 10.10.3
**Thrown From**: [remote-sync](https://github.com/yongkangchen/remote-sync) package, v3.1.2

### Stack Trace

Uncaught TypeError: Cannot read property 'downloadFolder' of undefined

```
At /Users/Dave/.atom/packages/remote-sync/index.coffee:64

TypeError: Cannot read property 'downloadFolder' of undefined
  at handleEvent (/Users/Dave/.atom/packages/remote-sync/index.coffee:64:29)
  at atom-workspace.disposables.add.atom.commands.add.remote-sync:download-folder (/Users/Dave/.atom/packages/remote-sync/index.coffee:78:44)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:156:19)
  at [object Object].jQuery.fn.trigger (/Applications/Atom.app/Contents/Resources/app.asar/src/space-pen-extensions.js:64:23)
  at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:75:67)
  at emitTwo (events.js:87:13)
  at EventEmitter.emit (events.js:169:7)
  at EventEmitter.ipc.sendSync (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/ipc.js:21:31)
  at BrowserWindow.RemoteMemberFunction [as emit] (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:110:29)
  at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/context-menu-manager.js:170:31)
  at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:150:33)
  at HTMLDocument.handler (/Applications/Atom.app/Contents/Resources/app.asar/src/space-pen-extensions.js:112:34)
  at HTMLDocument.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/space-pen/vendor/jquery.js:4681:9)
  at HTMLDocument.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/space-pen/vendor/jquery.js:4359:46)

```

### Commands

```
     -0:08.7.0 editor:add-selection-above (atom-pane.pane.active)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "auto-update-packages",
      "SFTP-deployment",
      "symbols-view"
    ]
  }
}
```

### Installed Packages

```coffee
# User
advanced-new-file, vundefined
atom-jshint, v2.0.0
atom-ternjs, v0.6.4
atom-yeoman, v0.3.11
file-icons, v1.5.8
linter, v1.0.2
linter-csslint, v0.0.13
linter-htmlhint, v0.0.16
linter-jshint, v0.1.6
linter-less, v2.0.0
linter-scss-lint, v1.0.4
linter-xmllint, v0.0.6
minimap, v4.10.0
remote-sync, v3.1.2
terminal-status, v1.6.8
trailing-spaces, v0.3.2

# Dev
No dev packages
```

**Comment by alanhouser** [comment]
Same issue here. 

[Enter steps to reproduce below:]

1. Right click folder > download folder
2. ...

**Atom Version**: 1.0.0
**System**: Mac OS X 10.10.3
**Thrown From**: [remote-sync](https://github.com/yongkangchen/remote-sync) package, v3.1.2


### Stack Trace

Uncaught TypeError: Cannot read property 'downloadFolder' of undefined

```
At /Users/alanhouser/.atom/packages/remote-sync/index.coffee:64

TypeError: Cannot read property 'downloadFolder' of undefined
  at handleEvent (/Users/alanhouser/.atom/packages/remote-sync/index.coffee:64:29)
  at atom-workspace.disposables.add.atom.commands.add.remote-sync:download-folder (/Users/alanhouser/.atom/packages/remote-sync/index.coffee:78:44)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:156:19)
  at [object Object].jQuery.fn.trigger (/Applications/Atom.app/Contents/Resources/app.asar/src/space-pen-extensions.js:64:23)
  at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:75:67)
  at emitTwo (events.js:87:13)
  at EventEmitter.emit (events.js:169:7)
  at EventEmitter.ipc.sendSync (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/ipc.js:21:31)
  at BrowserWindow.RemoteMemberFunction [as emit] (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:110:29)
  at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/context-menu-manager.js:170:31)
  at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:150:33)
  at HTMLDocument.handler (/Applications/Atom.app/Contents/Resources/app.asar/src/space-pen-extensions.js:112:34)
  at HTMLDocument.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/space-pen/vendor/jquery.js:4681:9)
  at HTMLDocument.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/space-pen/vendor/jquery.js:4359:46)

```

### Commands

```
  7x -3:25.1.0 core:select-right (atom-text-editor.editor.is-focused)
     -3:16.3.0 core:move-down (atom-text-editor.editor.is-focused)
  2x -3:16 core:move-left (atom-text-editor.editor.is-focused)
  7x -3:15.3.0 core:select-left (atom-text-editor.editor.is-focused)
     -3:08.0 core:move-down (atom-text-editor.editor.is-focused)
  7x -3:04.1.0 core:move-left (atom-text-editor.editor.is-focused)
  2x -2:34.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:38 core:paste (atom-text-editor.editor.is-focused)
     -1:29.4.0 core:save (atom-text-editor.editor.is-focused)
     -1:02.3.0 core:copy (div.package-readme.native-key-bindings)
     -0:52.9.0 command-palette:toggle (div.package-readme.native-key-bindings)
     -0:51.6.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -0:50.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:20.2.0 command-palette:toggle (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:16.3.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -0:13.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ],
    "disabledPackages": [
      "livereload",
      "change-case",
      "atom-alignment",
      "SFTP-deployment",
      "remote-edit"
    ]
  },
  "remote-sync": {}
}
```

### Installed Packages

```coffee
# User
remote-sync, v3.1.2

# Dev
No dev packages
```

**Comment by alanhouser** [comment]
Hey @dinoDachi why was this issue closed?

**Comment by lmdelgallego** [comment]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.19
**System**: Unknown Windows Version
**Thrown From**: [remote-sync](https://github.com/yongkangchen/remote-sync) package, v3.1.2


### Stack Trace

Uncaught TypeError: Cannot read property 'downloadFolder' of undefined

```
At /C:/Users/LuisMiguel/.atom/packages/remote-sync/index.coffee:64

TypeError: Cannot read property 'downloadFolder' of undefined
  at handleEvent (C:\Users\LuisMiguel\.atom\packages\remote-sync\index.coffee:64:29)
  at atom-workspace.disposables.add.atom.commands.add.remote-sync:download-folder (C:\Users\LuisMiguel\.atom\packages\remote-sync\index.coffee:78:44)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\LuisMiguel\AppData\Local\atom\app-1.0.19\resources\app.asar\src\command-registry.js:245:29)
  at CommandRegistry.handleCommandEvent (C:\Users\LuisMiguel\AppData\Local\atom\app-1.0.19\resources\app.asar\src\command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\LuisMiguel\AppData\Local\atom\app-1.0.19\resources\app.asar\src\command-registry.js:145:19)
  at [object Object].jQuery.fn.trigger (C:\Users\LuisMiguel\AppData\Local\atom\app-1.0.19\resources\app.asar\src\space-pen-extensions.js:64:23)
  at EventEmitter.<anonymous> (C:\Users\LuisMiguel\AppData\Local\atom\app-1.0.19\resources\app.asar\src\window-event-handler.js:75:67)
  at emitTwo (events.js:87:13)
  at EventEmitter.emit (events.js:172:7)
  at EventEmitter.ipc.sendSync (C:\Users\LuisMiguel\AppData\Local\atom\app-1.0.19\resources\atom.asar\renderer\api\lib\ipc.js:21:31)
  at BrowserWindow.RemoteMemberFunction [as emit] (C:\Users\LuisMiguel\AppData\Local\atom\app-1.0.19\resources\atom.asar\renderer\api\lib\remote.js:140:29)
  at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (C:\Users\LuisMiguel\AppData\Local\atom\app-1.0.19\resources\app.asar\src\context-menu-manager.js:170:31)
  at HTMLDocument.<anonymous> (C:\Users\LuisMiguel\AppData\Local\atom\app-1.0.19\resources\app.asar\src\window-event-handler.js:157:33)
  at HTMLDocument.handler (C:\Users\LuisMiguel\AppData\Local\atom\app-1.0.19\resources\app.asar\src\space-pen-extensions.js:112:34)
  at HTMLDocument.jQuery.event.dispatch (C:\Users\LuisMiguel\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4681:9)
  at HTMLDocument.elemData.handle (C:\Users\LuisMiguel\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4359:46)

```

### Commands

```
     -9:50.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -9:02.7.0 remote-ftp:disconnect (div.text.native-key-bindings)
     -8:57.9.0 remote-ftp:toggle (div.text.native-key-bindings)
     -6:45.6.0 remote-edit:browse (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -4:44.4.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  2x -4:43.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -3:38.1.0 timecop:view (div.settings-view.pane-item)
     -1:22.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  5x -1:21.7.0 core:paste (atom-text-editor.editor.is-focused)
     -0:28.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:26.4.0 core:save (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "monokai"
    ]
  },
  "remote-sync": {
    "logToConsole": true
  }
}
```

### Installed Packages

```coffee
# User
color-picker, v2.0.13
file-icons, v1.6.11
jquery-snippets, v11.0.0
minimap, v4.13.4
monokai, v0.18.0
pigments, v0.18.0
remote-edit, v1.8.21
Remote-FTP, v0.7.8
remote-sync, v3.1.2
travis-ci-status, v0.18.0

# Dev
No dev packages
```

**Comment by thiagodebastos** [comment]
Same issue here guys

**Comment by ubani** [comment]
On OS X it helps to restart Atom.
