### ISSUE TITLE
Uncaught Error: [remote-sync] invalid transport: undefined in /Users/jesus/path/to/project/.remote-sync.json

### ISSUE THREAD

**Issue by jesusjjf** [yongkangchen/remote-sync#170]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.0
**System**: Mac OS X 10.10.4
**Thrown From**: [remote-sync](https://github.com/yongkangchen/remote-sync) package, v3.1.2

### Stack Trace

Uncaught Error: [remote-sync] invalid transport: undefined in /Users/jesus/path/to/project/.remote-sync.json

```
At /Users/jesus/.atom/packages/remote-sync/lib/RemoteSync.coffee:104

Error: [remote-sync] invalid transport: undefined in /Users/jesus/path/to/project/.remote-sync.json
  at RemoteSync.createTransport (/Users/jesus/.atom/packages/remote-sync/lib/RemoteSync.coffee:104:17)
  at RemoteSync.getTransport (/Users/jesus/.atom/packages/remote-sync/lib/RemoteSync.coffee:110:19)
  at RemoteSync.uploadFile (/Users/jesus/.atom/packages/remote-sync/lib/RemoteSync.coffee:70:37)
  at handleEvent (/Users/jesus/.atom/packages/remote-sync/index.coffee:38:14)
  at atom-workspace.disposables.add.atom.commands.add.remote-sync:upload-file (/Users/jesus/.atom/packages/remote-sync/index.coffee:76:40)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
  at CommandRegistry.handleCommandEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/command-registry.js:156:19)
  at [object Object].jQuery.fn.trigger (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/space-pen-extensions.js:64:23)
  at EventEmitter.<anonymous> (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:75:67)
  at emitTwo (events.js:87:13)
  at EventEmitter.emit (events.js:169:7)
  at EventEmitter.ipc.sendSync (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/ipc.js:21:31)
  at BrowserWindow.RemoteMemberFunction [as emit] (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:110:29)
  at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/context-menu-manager.js:170:31)
  at HTMLDocument.<anonymous> (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:150:33)
  at HTMLDocument.handler (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/space-pen-extensions.js:112:34)
  at HTMLDocument.jQuery.event.dispatch (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/space-pen/vendor/jquery.js:4681:9)
  at HTMLDocument.elemData.handle (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/space-pen/vendor/jquery.js:4359:46)

```

### Commands

```
     -0:55.4.0 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -0:55.1.0 editor:select-to-end-of-line (atom-text-editor.editor.is-focused)
     -0:52.2.0 core:paste (atom-text-editor.editor.is-focused)
     -0:51.9.0 core:save (atom-text-editor.editor.is-focused)
     -0:50.6.0 core:close (atom-text-editor.editor.is-focused)
     -0:15.1.0 core:save (atom-text-editor.editor.is-focused)
  7x -0:08.9.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:07.6.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:07.4.0 core:select-down (atom-text-editor.editor.is-focused)
     -0:07.1.0 editor:select-to-end-of-line (atom-text-editor.editor.is-focused)
     -0:05.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:05.5.0 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -0:05.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:05.0 core:save (atom-text-editor.editor.is-focused)
     -0:04.3.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:04.3.0 core:cancel (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store",
      ".idea",
      ".sublime",
      ".sass-cache",
      "node_modules"
    ],
    "disabledPackages": [
      "background-tips",
      "welcome",
      "whitespace",
      "toggle-quotes",
      "package-generator",
      "open-on-github",
      "open-in-browser",
      "link",
      "image-view",
      "dev-live-reload",
      "deprecation-cop"
    ]
  }
}
```

### Installed Packages

```coffee
# User
go-plus, v3.3.12
remote-sync, v3.1.2

# Dev
No dev packages
```

**Comment by TylerButh** [comment]
I had a similar error after editing the .remote-sync.json file manually.  The error went away when I used the Remote Sync -> Configure option by right clicking the project.

**Comment by yongkangchen** [comment]
The `transport ` in .remote-sync.json can only be `scp` or `ftp`.

**Comment by AdsonCicilioti** [comment]
Why closes @yongkangchen ?
@jesusgalvan show the code in your .remote-sync.json file, please!
