### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getWorkingDirectory' of null

### ISSUE THREAD

**Issue by fabriziovass** [yongkangchen/remote-sync#174]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.0
**System**: Mac OS X 10.10.3
**Thrown From**: [remote-sync](https://github.com/yongkangchen/remote-sync) package, v3.1.2

### Stack Trace

Uncaught TypeError: Cannot read property 'getWorkingDirectory' of null

```
At /Users/Fabrizio/.atom/packages/remote-sync/lib/RemoteSync.coffee:82

TypeError: Cannot read property 'getWorkingDirectory' of null
    at RemoteSync.uploadGitChange (/Users/Fabrizio/.atom/packages/remote-sync/lib/RemoteSync.coffee:136:32)
    at handleEvent (/Users/Fabrizio/.atom/packages/remote-sync/index.coffee:64:67)
    at atom-workspace.disposables.add.atom.commands.add.remote-sync:upload-git-change (/Users/Fabrizio/.atom/packages/remote-sync/index.coffee:135:18)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:156:19)
    at jQuery.fn.trigger (/Applications/Atom.app/Contents/Resources/app.asar/src/space-pen-extensions.js:64:23)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:75:67)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:169:7)
```

### Commands

```
     -0:07.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:06.8.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "solarized-light-syntax"
    ]
  },
  "remote-sync": {}
}
```

### Installed Packages

```coffee
# User
minimap, v4.10.0
pigments, v0.8.1
remote-sync, v3.1.2
wordpress-api, v1.2.1

# Dev
No dev packages
```

**Comment by ffflorian** [comment]
Got the same error when trying to upload folder change via scp.

**Comment by cjhmdm** [comment]
Same error here when selecting "Upload Folder Change" in Windows, so issue doesn't appear to be platform specific

**Comment by omouse** [comment]
Have the same issue in Atom 1.0.2 and remote-sync 3.1.2 on Mac OS X.

**Comment by Nico207** [comment]
Same issue 

1. Create a new directory
2. Choose "Upload folder change"

Windows 7 64bits French
atom : v1.0.0
remote-sync : v3.1.2

**Comment by MrRDJack** [comment]
Cannot use Upload folder change
Mac 10.11
atom v1.0.0
remote-sync: 3.1.2

**Comment by yongkangchen** [comment]
I guess you guys did not use git, but svn?

**Comment by yongkangchen** [comment]
svn is not support yet.

**Comment by rshakespear** [comment]
I have the same problem. I'm using GIT and on windows.
