### ISSUE TITLE
Uncaught TypeError: Arguments to path.join must be strings path.js

### ISSUE THREAD

**Issue by Bana0615** [yongkangchen/remote-sync#175]
This package keeps throwing this error:

Uncaught TypeError: Arguments to path.join must be strings
path.js:178
Hide Stack Trace
TypeError: Arguments to path.join must be strings
    at f (path.js:178:13)
    at Object.filter (native)
    at Object.win32.join (path.js:183:38)
    at ScpTransport.module.exports.ScpTransport.fetchFileTree (C:\Users\Andrew.Elbaneh\.atom\packages\remote-sync\lib\transports\ScpTransport.coffee:110:25)
    at Object.module.exports.run (C:\Users\Andrew.Elbaneh\.atom\packages\remote-sync\lib\commands\DownloadAllCommand.coffee:17:24)
    at RemoteSync.downloadFolder (C:\Users\Andrew.Elbaneh\.atom\packages\remote-sync\lib\RemoteSync.coffee:93:26)
    at handleEvent (C:\Users\Andrew.Elbaneh\.atom\packages\remote-sync\index.coffee:64:67)
    at atom-workspace.disposables.add.atom.commands.add.remote-sync:download-folder (C:\Users\Andrew.Elbaneh\.atom\packages\remote-sync\index.coffee:126:18)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Andrew.Elbaneh\AppData\Local\atom\app-1.0.0\resources\app.asar\src\command-registry.js:241:29)
    at CommandRegistry.handleCommandEvent (C:\Users\Andrew.Elbaneh\AppData\Local\atom\app-1.0.0\resources\app.asar\src\command-registry.js:3:61)

**Comment by hiddewie** [comment]
I also have this problem

**Comment by 3XE** [comment]
I had this issue as well as issues with a couple of other packages (e.g. auto-complete not working).

Fixed all by 'hard uninstalling' Atom, i.e.:
1) Uninstall Atom via control panel
2) Remove users/abc/.atom folder
3) Remove users/abc/appdata/local/atom folder -- you may, like me, have to reboot your PC to kill any zombie Atom processes that prevent you from doing this.

After reinstalling Atom and the required packages all worked fine.

**Comment by globexdesigns** [comment]
This happened to me when I forgot to configure the "Target Path". To fix it, I had to set the Target Path in my server's configuration and then Restart Atom.

It would be nice, if the error message was more helpful and if a restart wouldn't be needed.
