### ISSUE TITLE
Uncaught TypeError: Cannot read property 'diffFolder' of undefined

### ISSUE THREAD

**Issue by marcoslhc** [yongkangchen/remote-sync#176]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.0
**System**: Mac OS X 10.10.3
**Thrown From**: [remote-sync](https://github.com/yongkangchen/remote-sync) package, v3.1.2

### Stack Trace

Uncaught TypeError: Cannot read property 'diffFolder' of undefined

```
At /Users/marcoslh/.atom/packages/remote-sync/index.coffee:64

TypeError: Cannot read property 'diffFolder' of undefined
  at handleEvent (/Users/marcoslh/.atom/packages/remote-sync/index.coffee:64:29)
  at atom-workspace.disposables.add.atom.commands.add.remote-sync:diff-folder (/Users/marcoslh/.atom/packages/remote-sync/index.coffee:80:40)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
  at CommandRegistry.handleCommandEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/command-registry.js:156:19)
  at [object Object].jQuery.fn.trigger (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/space-pen-extensions.js:64:23)
  at EventEmitter.<anonymous> (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:75:67)
  at emitTwo (events.js:87:13)
  at EventEmitter.emit (events.js:169:7)
  at EventEmitter.ipc.sendSync (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/ipc.js:21:31)
  at BrowserWindow.RemoteMemberFunction [as emit] (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:110:29)
  at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/context-menu-manager.js:170:31)
  at HTMLDocument.<anonymous> (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:150:33)
  at HTMLDocument.handler (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/space-pen-extensions.js:112:34)
  at HTMLDocument.jQuery.event.dispatch (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/space-pen/vendor/jquery.js:4681:9)
  at HTMLDocument.elemData.handle (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/space-pen/vendor/jquery.js:4359:46)

```

### Commands

```
     -8:53 core:copy (atom-text-editor.editor.vim-mode.is-focused.visual-mode)
 11x -8:51.5.0 blur (atom-text-editor.editor.vim-mode.is-focused.visual-mode)
```

### Config

```json
{
  "core": {
    "themes": [
      "isotope-ui",
      "base16-tomorrow-dark-theme"
    ]
  },
  "remote-sync": {}
}
```

### Installed Packages

```coffee
# User
atom-django, v0.3.0
color-picker, v2.0.7
django-templates, v0.5.0
editorconfig, v1.0.1
emmet, v2.3.11
ex-mode, v0.5.1
git-log, v0.4.1
git-tab-status, v1.9.2
isotope-ui, v2.4.2
linter, v1.1.0
linter-flake8, v1.4.2
linter-jscs, v1.12.0
linter-jshint, v0.1.7
linter-python-pep8, v0.2.0
node-debugger, v1.1.0
pigments, v0.8.1
remote-sync, v3.1.2
vim-mode, v0.54.0

# Dev
No dev packages
```

**Comment by yongkangchen** [comment]
It sees that you try to diff a folder which is not belong to the project?
