### ISSUE TITLE
Uncaught TypeError: Cannot read property 'uploadFolder' of undefined

### ISSUE THREAD

**Issue by DSigmund** [yongkangchen/remote-sync#177]
C:\Users\sigmundd\.atom\packages\remote-sync\index.coffee:64
Hide Stack Trace
TypeError: Cannot read property 'uploadFolder' of undefined
  at handleEvent (C:\Users\sigmundd\.atom\packages\remote-sync\index.coffee:64:29)
  at atom-workspace.disposables.add.atom.commands.add.remote-sync:upload-folder (C:\Users\sigmundd\.atom\packages\remote-sync\index.coffee:75:42)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\sigmundd\AppData\Local\atom\app-1.0.0\resources\app.asar\src\command-registry.js:241:29)
  at C:\Users\sigmundd\AppData\Local\atom\app-1.0.0\resources\app.asar\src\command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (C:\Users\sigmundd\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\command-palette\lib\command-palette-view.js:159:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (C:\Users\sigmundd\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\atom-space-pen-views\lib\select-list-view.js:338:21)
  at space-pen-div.atom.commands.add.core:confirm (C:\Users\sigmundd\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\atom-space-pen-views\lib\select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\sigmundd\AppData\Local\atom\app-1.0.0\resources\app.asar\src\command-registry.js:241:29)
  at C:\Users\sigmundd\AppData\Local\atom\app-1.0.0\resources\app.asar\src\command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\sigmundd\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\sigmundd\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (C:\Users\sigmundd\AppData\Local\atom\app-1.0.0\resources\app.asar\src\window-event-handler.js:180:20)

**Comment by DSigmund** [comment]
Solved...  

How?
"uploadOnSave": true, IS REQUIRED!!!  

AND to update config: cmd + shift + p --> remote sync configure

**Comment by vringar** [comment]
How is that a fix?

**Comment by jforten19** [comment]
For me to correct this issue I unlocked the VM I had running for the box.  I'm using Oracle VM VirtualBox Manager to host a CentOS server.  I logged in to unlock it and Remote Sync > Upload Folder worked after that.
