### ISSUE TITLE
Uncaught Error: Unable to parse private key while generating public key (expected sequence)

### ISSUE THREAD

**Issue by swarajban** [yongkangchen/remote-sync#182]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.2
**System**: Mac OS X 10.10.3
**Thrown From**: [remote-sync](https://github.com/yongkangchen/remote-sync) package, v3.1.2

### Stack Trace

Uncaught Error: Unable to parse private key while generating public key (expected sequence)

```
At /Users/swaraj/.atom/packages/remote-sync/node_modules/ssh2/lib/Connection.js:511

Error: Unable to parse private key while generating public key (expected sequence)
  at Connection.connect (/Users/swaraj/.atom/packages/remote-sync/node_modules/ssh2/lib/Connection.js:511:15)
  at ScpTransport.module.exports.ScpTransport._getConnection (/Users/swaraj/.atom/packages/remote-sync/lib/transports/ScpTransport.coffee:125:16)
  at ScpTransport.module.exports.ScpTransport.upload (/Users/swaraj/.atom/packages/remote-sync/lib/transports/ScpTransport.coffee:24:6)
  at UploadListener.module.exports.UploadListener.uploadFile (/Users/swaraj/.atom/packages/remote-sync/lib/UploadListener.coffee:18:15)
  at q.process (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/async/lib/async.js:769:21)
  at process._tickCallback (node.js:357:13)

```

### Commands

```
  4x -0:02.2.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:01.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:01.1.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "zenburn"
    ],
    "disabledPackages": [
      "language-coffee-script-angular",
      "language-coffee-script-angular"
    ]
  },
  "remote-sync": {}
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.0
autocomplete-emojis, v2.2.2
autocomplete-paths, v1.0.2
autocomplete-php, v0.3.6
autocomplete-python, v0.5.1
autocomplete-sass, v0.1.0
language-chef, v0.5.0
language-docker, v1.1.3
language-gitignore, v0.2.0
language-nginx, v0.5.4
php-twig, v4.0.0
pretty-json, v0.4.1
preview, vundefined
project-manager, vundefined
remote-sync, v3.1.2
symbols-tree-view, v0.9.3
synced-sidebar, v0.4.0
wakatime, vundefined
zenburn, v3.0.0

# Dev
No dev packages
```

**Comment by yongkangchen** [comment]
There is something wrong with your key. You can try to google: `Uncaught Error: Unable to parse private key while generating public key` and see if there are some answers
