### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by rphodges** [yongkangchen/remote-sync#184]
[Enter steps to reproduce below:]

1. Just saved a file after selecting 'use agent' as an access method
2. ...

**Atom Version**: 1.0.2
**System**: Mac OS X 10.10.4
**Thrown From**: [remote-sync](https://github.com/yongkangchen/remote-sync) package, v3.1.2

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At buffer.js:483

TypeError: Cannot read property 'length' of undefined
    at Buffer.write (buffer.js:483:13)
    at Connection._authPK (/Users/ryan/.atom/packages/remote-sync/node_modules/ssh2/lib/Connection.js:1126:7)
    at /Users/ryan/.atom/packages/remote-sync/node_modules/ssh2/lib/Connection.js:1265:12
    at Socket.onclose (/Users/ryan/.atom/packages/remote-sync/node_modules/ssh2/lib/agent.js:187:7)
    at Socket.g (events.js:257:16)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:166:7)
    at Pipe.close (net.js:464:12)
```

### Commands

```
     -1:36.7.0 core:move-up (atom-text-editor.editor.mini.is-focused)
 11x -1:34.7.0 core:move-down (atom-text-editor.editor.mini.is-focused)
  2x -1:28.3.0 core:move-up (atom-text-editor.editor.mini.is-focused)
  6x -1:27.3.0 core:move-down (atom-text-editor.editor.mini.is-focused)
  3x -1:25.4.0 core:move-up (atom-text-editor.editor.mini.is-focused)
     -1:23.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:23.1.0 remote-sync:configure (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:50.8.0 fuzzy-finder:toggle-file-finder (ul.list-inline.tab-bar.inset-panel)
     -0:46.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:42.6.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:41.8.0 core:save (atom-text-editor.editor.is-focused)
     -0:18.9.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:16.7.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:16 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:16 remote-sync:configure (atom-text-editor.editor)
     -0:01.2.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "atom-light-syntax"
    ]
  },
  "remote-sync": {}
}
```

### Installed Packages

```coffee
# User
language-diff, v0.3.0
language-perl, v0.28.0
remote-atom, v1.2.6
remote-sync, v3.1.2
symbols-tree-view, v0.9.3
tab-control, v0.6.7
tasks, v2.2.0

# Dev
No dev packages
```

**Comment by yongkangchen** [comment]
I guess there are something wrong with your auth config
