### ISSUE TITLE
Uncaught TypeError: must start with number, buffer, array or string

### ISSUE THREAD

**Issue by gramimoss** [yongkangchen/remote-sync#185]
[Enter steps to reproduce below:]

1. created new folder
2. configured remote-sync with the linux server ( password based )
3. right-clicked and selected download folder.

**Atom Version**: 1.0.3
**System**: Microsoft Windows 10 Pro
**Thrown From**: [remote-sync](https://github.com/yongkangchen/remote-sync) package, v3.1.2

### Stack Trace

Uncaught TypeError: must start with number, buffer, array or string

```
At buffer.js:84

TypeError: must start with number, buffer, array or string
  at fromObject (buffer.js:84:11)
  at new Buffer (buffer.js:52:3)
  at onNEWKEYS (C:\Users\Graemem\.atom\packages\remote-sync\node_modules\ssh2\lib\Connection.js:2282:29)
  at Parser.<anonymous> (C:\Users\Graemem\.atom\packages\remote-sync\node_modules\ssh2\lib\Connection.js:123:5)
  at emitNone (events.js:67:13)
  at Parser.emit (events.js:163:7)
  at Parser.parsePacket (C:\Users\Graemem\.atom\packages\remote-sync\node_modules\ssh2\lib\Parser.js:468:12)
  at Parser.execute (C:\Users\Graemem\.atom\packages\remote-sync\node_modules\ssh2\lib\Parser.js:249:14)
  at Socket.<anonymous> (C:\Users\Graemem\.atom\packages\remote-sync\node_modules\ssh2\lib\Connection.js:523:18)
  at emitOne (events.js:77:13)
  at Socket.emit (events.js:166:7)
  at readableAddChunk (_stream_readable.js:146:16)
  at Socket.Readable.push (_stream_readable.js:109:10)
  at TCP.onread (net.js:517:20)

```

### Commands

```
     -6:22.1.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -6:18.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -6:18.3.0 settings-view:open (atom-text-editor.editor)
     -6:14 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -4:50.8.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -4:50 core:page-down (atom-text-editor.editor.mini.is-focused)
     -4:09.3.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -2:28.6.0 tree-view:remove (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  9x -0:52.4.0 core:backspace (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "atom-sync"
    ]
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-php, v0.3.6
preview-plus, v1.2.5
remote-sync, v3.1.2

# Dev
No dev packages
```

**Comment by tairun** [comment]
Same happens when trying to upload. _upload on save_ is enabled.

**Comment by yongkangchen** [comment]
It seems that something wrong with your key file?

**Comment by mgcrea** [comment]
Same here with `"useAgent": true,`

Key file is working file (it's loaded) and SSH works.

**Atom Version**: 1.3.3
**System**: Mac OS X 10.11.2
**Thrown From**: [remote-sync](https://github.com/yongkangchen/remote-sync) package, v3.5.0


### Stack Trace

Uncaught TypeError: must start with number, buffer, array or string

```
At buffer.js:139

TypeError: must start with number, buffer, array or string
    at fromObject (buffer.js:139:11)
    at new Buffer (buffer.js:58:10)
    at onNEWKEYS (/Users/olivier/.atom/packages/remote-sync/node_modules/ssh2/lib/Connection.js:2282:29)
    at Parser.<anonymous> (/Users/olivier/.atom/packages/remote-sync/node_modules/ssh2/lib/Connection.js:123:5)
    at emitNone (events.js:67:13)
    at Parser.emit (events.js:166:7)
    at Parser.parsePacket (/Users/olivier/.atom/packages/remote-sync/node_modules/ssh2/lib/Parser.js:468:12)
    at Parser.execute (/Users/olivier/.atom/packages/remote-sync/node_modules/ssh2/lib/Parser.js:249:14)
    at Socket.<anonymous> (/Users/olivier/.atom/packages/remote-sync/node_modules/ssh2/lib/Connection.js:523:18)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)
```

### Commands

```
     -9:32 core:copy (atom-text-editor.editor.is-focused)
     -9:29.7.0 core:paste (atom-text-editor.editor.is-focused)
 11x -8:54 find-and-replace:select-next (atom-text-editor.editor.is-focused)
     -1:06.5.0 editor:newline (atom-text-editor.editor.is-focused)
  2x -1:04.5.0 core:move-right (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:03.1.0 core:save (atom-text-editor.editor.is-focused)
     -0:56.7.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:53.7.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:53.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:53.3.0 remote-sync:configure (atom-text-editor.editor)
     -0:51.8.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:51.8.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:51.8.0 editor:indent (atom-text-editor.editor.is-focused)
  6x -0:44.4.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  2x -0:22.4.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "livereload",
      "markdown-writer",
      "terminal-plus",
      "atom-wallaby",
      "Termrk",
      "atom-typescript",
      "build",
      "remote-atom"
    ]
  }
}
```

### Installed Packages

```coffee
# User
.bin, vundefined
atom-beautify, v0.28.19
atom-ternjs, v0.12.2
autocomplete-paths, v1.0.2
color-picker, v2.0.14
file-icons, v1.6.13
language-arduino, v0.4.1
language-jade, v0.6.2
linter, v1.11.3
linter-cpplint, v1.0.1
linter-eslint, v5.2.7
linter-jshint, v1.2.2
linter-jsonlint, v1.1.4
markdown-preview-plus, v2.2.2
minimap, v4.19.0
minimap-find-and-replace, v4.4.0
minimap-git-diff, v4.1.8
minimap-selection, v4.3.1
mocha-test-runner, v0.4.6
project-manager, v2.7.1
react, v0.12.10
remote-sync, v3.5.0
tabs-to-spaces, v1.0.1

# Dev
No dev packages
```

**Comment by vlechemin** [comment]
Same issue here, it used to work on the old server (OpenSSH_6.0p1 Debian-4+deb7u2, OpenSSL 1.0.1e 11 Feb 2013) but not with the new one (OpenSSH_6.7p1 Debian-5, OpenSSL 1.0.1k 8 Jan 2015).
Anyone solved this?
Thanks!

**Comment by hidewak** [comment]
Works fine until I change my .remote-sync.json file (1 character) , since then I get the error below, haven't found a solution yet

1. ...
2. ...

**Atom Version**: 1.7.2
**System**: Mac OS X 10.11.4
**Thrown From**: [remote-sync](https://github.com/yongkangchen/remote-sync) package, v4.0.1


### Stack Trace

Uncaught TypeError: must start with number, buffer, array or string

```
At buffer.js:139

TypeError: must start with number, buffer, array or string
  at fromObject (buffer.js:139:11)
  at new Buffer (buffer.js:58:10)
  at onNEWKEYS (/Users/romain/.atom/packages/remote-sync/node_modules/ssh2/lib/Connection.js:2282:29)
  at Parser.<anonymous> (/Users/romain/.atom/packages/remote-sync/node_modules/ssh2/lib/Connection.js:123:5)
  at emitNone (events.js:67:13)
  at Parser.emit (events.js:166:7)
  at Parser.parsePacket (/Users/romain/.atom/packages/remote-sync/node_modules/ssh2/lib/Parser.js:468:12)
  at Parser.execute (/Users/romain/.atom/packages/remote-sync/node_modules/ssh2/lib/Parser.js:249:14)
  at Socket.<anonymous> (/Users/romain/.atom/packages/remote-sync/node_modules/ssh2/lib/Connection.js:523:18)
  at emitOne (events.js:77:13)
  at Socket.emit (events.js:169:7)
  at readableAddChunk (_stream_readable.js:146:16)
  at Socket.Readable.push (_stream_readable.js:110:10)
  at TCP.onread (net.js:523:20)

```

### Commands

```
     -3:18.9.0 application:add-project-folder (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -2:49.9.0 settings-view:install-packages-and-themes (div.nuclide-file-tree.focusable-panel.tree-view)
  5x -2:41.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
 10x -2:40 core:backspace (atom-text-editor.editor.mini.is-focused)
  2x -2:30.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  4x -0:52.7.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:46.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:09.5.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
     -0:05.2.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:04.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:03.1.0 core:save (atom-text-editor.editor.enable-nuclide-find-references.is-focused)
```

### Config

```json
{
  "core": {
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".flowconfig"
      ],
      "source.json": [
        ".arcconfig"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "disabledPackages": [
      "tree-view",
      "atom-sync"
    ]
  },
  "remote-sync": {}
}
```

### Installed Packages

```coffee
# User
haskell-grammar, v0.4.0
highlight-selected, v0.11.2
language-babel, v2.16.0
language-ini, v1.15.0
language-ocaml, v1.1.2
language-thrift, v1.0.2
nuclide, v0.127.0
php-twig, v4.0.0
remote-sync, v4.0.1
tool-bar, v0.4.0

# Dev
No dev packages
```

**Comment by mgcrea** [comment]
It looks like it is related to `useAgent: true`, do you have it in your config?
Updating SSH2 should fix it.

**Comment by stephenchaffins** [comment]
I do not have useAgent: true, and I have this same issue.

**Comment by haugli92** [comment]
Im also having this issue. It happen after i used `useAgent: true` on one server.

**Comment by haugli92** [comment]
Okey, after hours of debugging i finally found a solution that did work for me.

I run everything on **Ubuntu Server 14.04.4 LTS** with **OpenSSH_6.6.1p1**

Edit **/etc/ssh/sshd_config**

Try to find a line that looks like this:

`MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,hmac-ripemd160`

And comment it out like this:

`#MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,hmac-ripemd160`

Restart SSH

`service ssh restart`

I assume I added this line a while ago to harden my SSH security. If anyone have comments on why this should be there it would be fine, but now it commented out.

**Comment by mgcrea** [comment]
Real fix for me was to bump `ssh2` dep to `"^0.5"`.

`cd ~/.atom/packages/remote-sync; nano package.json; npm i`

**Comment by mgcrea** [comment]
@elistone just reintalled today and still got the error, could you please push a new release with the fix?

**Comment by elistone** [comment]
@mgcrea just pushed new version with latest PR's
