### ISSUE TITLE
Crash out when Removing project folder: `Uncaught TypeError: Cannot read property 'dispose' of undefined`

### ISSUE THREAD

**Issue by sixthcore** [yongkangchen/remote-sync#190]
If I remove a project folder ( which I do frequently as I am constantly switching. I find an error pop up: 

`Uncaught TypeError: Cannot read property 'dispose' of undefined`

This appears to sometimes clear on clicking the close X 

From time to time it seems to completely lock out Atom whereby I have to literally force quit atom and restart it, there after it seems to clear the tree and any other project folders. 

I am sure some one else has reported this issue before, and its really not that detrimental. The usefulness of Remote-Sync way out weighs the irritation :) just wanted to raise it.

**Comment by netmit** [comment]
Same problem here - not a major problem (unless I'm switching projects frequently) but does seem to leave the removed project folder in the tree and then have to restart Atom to clear it.

**Comment by Maelstrome26** [comment]
Same issue here. I regularly swap between projects and this hits me every single time.

**Comment by tairun** [comment]
Can confirm

**Comment by globexdesigns** [comment]
+1. Very frustrating issue.

**Comment by MyZeD** [comment]
Same here

**Comment by nexcode** [comment]
**Atom Version**: 1.0.19
**System**: Windows 10
**Thrown From**: [remote-sync](https://github.com/yongkangchen/remote-sync) package, v3.1.2


### Stack Trace

Uncaught TypeError: Cannot read property 'dispose' of undefined

```
At C:\Users\nexco\.atom\packages\remote-sync\index.coffee:43

TypeError: Cannot read property 'dispose' of undefined
    at initProject (C:\Users\nexco\.atom\packages\remote-sync\index.coffee:43:31)
    at C:\Users\nexco\.atom\packages\remote-sync\index.coffee:140:16
    at Emitter.module.exports.Emitter.emit (C:\Users\nexco\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
    at Project.module.exports.Project.removePath (C:\Users\nexco\AppData\Local\atom\app-1.0.19\resources\app.asar\src\project.js:311:22)
    at TreeView.module.exports.TreeView.removeProjectFolder (C:\Users\nexco\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\tree-view\lib\tree-view.js:1059:31)
    at space-pen-div.atom.commands.add.tree-view:remove-project-folder (C:\Users\nexco\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\tree-view\lib\tree-view.js:343:26)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\nexco\AppData\Local\atom\app-1.0.19\resources\app.asar\src\command-registry.js:245:29)
    at CommandRegistry.handleCommandEvent (C:\Users\nexco\AppData\Local\atom\app-1.0.19\resources\app.asar\src\command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\nexco\AppData\Local\atom\app-1.0.19\resources\app.asar\src\command-registry.js:145:19)
    at [object Object].jQuery.fn.trigger (C:\Users\nexco\AppData\Local\atom\app-1.0.19\resources\app.asar\src\space-pen-extensions.js:64:23)
```

### Commands

```
     -7:44.8.0 core:save (atom-text-editor.editor.is-focused)
  4x -7:40.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -7:32.6.0 core:move-right (atom-text-editor.editor.is-focused)
  2x -7:32.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -7:28.8.0 core:save (atom-text-editor.editor.is-focused)
  2x -7:21.7.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -7:17 core:save (atom-text-editor.editor.is-focused)
  3x -7:12.2.0 core:backspace (atom-text-editor.editor.is-focused)
  4x -7:10.6.0 core:save (atom-text-editor.editor.is-focused)
     -7:00.7.0 core:copy (atom-text-editor.editor.is-focused)
     -6:59.6.0 core:paste (atom-text-editor.editor.is-focused)
  5x -6:58.1.0 core:save (atom-text-editor.editor.is-focused)
     -6:49.6.0 core:copy (atom-text-editor.editor.is-focused)
     -6:48.6.0 core:paste (atom-text-editor.editor.is-focused)
 10x -6:47.9.0 core:save (atom-text-editor.editor.is-focused)
  2x -0:20.5.0 tree-view:remove (ol.tree-view.list-tree.has-collapsable-children.focusable-panel.full-menu)
```

### Config

```json
{
  "core": {},
  "remote-sync": {
    "difftoolCommand": "Meld"
  }
}
```

### Installed Packages

```coffee
# User
go-plus, v3.5.1
remote-sync, v3.1.2

# Dev
No dev packages
```

**Comment by rmondragon** [comment]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.19
**System**: Mac OS X 10.11
**Thrown From**: [remote-sync](https://github.com/yongkangchen/remote-sync) package, v3.1.2


### Stack Trace

Uncaught TypeError: Cannot read property 'dispose' of undefined

```
At /Users/Rolando/.atom/packages/remote-sync/index.coffee:26

TypeError: Cannot read property 'dispose' of undefined
    at initProject (/Users/Rolando/.atom/packages/remote-sync/index.coffee:26:29)
    at /Users/Rolando/.atom/packages/remote-sync/index.coffee:86:7
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
    at Project.module.exports.Project.removePath (/Applications/Atom.app/Contents/Resources/app.asar/src/project.js:311:22)
    at TreeView.module.exports.TreeView.removeProjectFolder (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tree-view/lib/tree-view.js:1059:31)
    at space-pen-div.atom.commands.add.tree-view:remove-project-folder (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tree-view/lib/tree-view.js:343:26)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:245:29)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:145:19)
    at [object Object].jQuery.fn.trigger (/Applications/Atom.app/Contents/Resources/app.asar/src/space-pen-extensions.js:64:23)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
remote-sync, v3.1.2

# Dev
No dev packages
```

**Comment by zp-j** [comment]
Same issue here:

```
TypeError: Cannot read property 'dispose' of undefined
  at initProject (/Users/zhipeng/.atom/packages/remote-sync/index.coffee:26:29)
  at /Users/zhipeng/.atom/packages/remote-sync/index.coffee:86:7
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Project.module.exports.Project.removePath (/Applications/Atom.app/Contents/Resources/app.asar/src/project.js:311:22)
  at TreeView.module.exports.TreeView.removeProjectFolder (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tree-view/lib/tree-view.js:1059:31)
  at space-pen-div.atom.commands.add.tree-view:remove-project-folder (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tree-view/lib/tree-view.js:343:26)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:245:29)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:145:19)
  at [object Object].jQuery.fn.trigger (/Applications/Atom.app/Contents/Resources/app.asar/src/space-pen-extensions.js:64:23)
  at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:75:67)
  at emitTwo (events.js:87:13)
  at EventEmitter.emit (events.js:172:7)
  at EventEmitter.ipc.sendSync (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/ipc.js:21:31)
  at BrowserWindow.RemoteMemberFunction [as emit] (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:140:29)
  at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/context-menu-manager.js:170:31)
  at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:157:33)
  at HTMLDocument.handler (/Applications/Atom.app/Contents/Resources/app.asar/src/space-pen-extensions.js:112:34)
  at HTMLDocument.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/space-pen/vendor/jquery.js:4681:9)
  at HTMLDocument.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/space-pen/vendor/jquery.js:4359:46)
```

**Comment by Nico207** [comment]
[Enter steps to reproduce below:]

When nothing is opened in Atom :
1. Menu "File"->"Open a file..."->Select a file, whatever the extention
2. Right clic on the opened file
3. Select "Remove project folder"

**Atom Version**: 1.0.19
**System**: Windows 7 64bits
**Thrown From**: [remote-sync](https://github.com/yongkangchen/remote-sync) package, v3.1.2


### Stack Trace

Uncaught TypeError: Cannot read property 'dispose' of undefined

```
At /C:/Users/<user>/.atom/packages/remote-sync/index.coffee:43

TypeError: Cannot read property 'dispose' of undefined
    at initProject (C:\Users\<user>\.atom\packages\remote-sync\index.coffee:26:29)
    at C:\Users\<user>\.atom\packages\remote-sync\index.coffee:86:7
    at Emitter.module.exports.Emitter.emit (C:\Users\<user>\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
    at Project.module.exports.Project.removePath (C:\Users\<user>\AppData\Local\atom\app-1.0.19\resources\app.asar\src\project.js:311:22)
    at TreeView.module.exports.TreeView.removeProjectFolder (C:\Users\<user>\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\tree-view\lib\tree-view.js:1059:31)
    at space-pen-div.atom.commands.add.tree-view:remove-project-folder (C:\Users\<user>\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\tree-view\lib\tree-view.js:343:26)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\<user>\AppData\Local\atom\app-1.0.19\resources\app.asar\src\command-registry.js:245:29)
    at CommandRegistry.handleCommandEvent (C:\Users\<user>\AppData\Local\atom\app-1.0.19\resources\app.asar\src\command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\<user>\AppData\Local\atom\app-1.0.19\resources\app.asar\src\command-registry.js:145:19)
    at [object Object].jQuery.fn.trigger (C:\Users\<user>\AppData\Local\atom\app-1.0.19\resources\app.asar\src\space-pen-extensions.js:64:23)
```

### Commands

```
     -0:32.2.0 core:close (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {},
  "remote-sync": {
    "difftoolCommand": "C:\\Program Files (x86)\\WinMerge\\WinMergeU.exe"
  }
}
```

### Installed Packages

```coffee
# User
atom-yii2, v0.3.1
autoclose-html, v0.19.0
autocomplete-php, v0.3.7
color-picker, v2.0.13
file-icons, v1.6.10
keyboard-localization, v1.4.9
minimap, v4.13.4
minimap-bookmarks, v0.1.0
minimap-codeglance, v0.4.2
minimap-find-and-replace, v4.3.1
minimap-git-diff, v4.1.8
pigments, v0.17.1
remote-sync, v3.1.2

# Dev
No dev packages
```

**Comment by Alagaros** [comment]
Same issue here.

**Comment by yongkangchen** [comment]
Duplicate with #143
