### ISSUE TITLE
Error trying sync

### ISSUE THREAD

**Issue by chrisaandes** [yongkangchen/remote-sync#194]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.15
**System**: Unknown Windows Version
**Thrown From**: [remote-sync](https://github.com/yongkangchen/remote-sync) package, v3.1.2

### Stack Trace

Uncaught Error: Cannot find module 'minimatch'

```
At C:\Users\Christian España\AppData\Local\atom\app-1.0.15\resources\app.asar\src\pane.js:809

Error: Cannot find module 'minimatch'
  at Module._resolveFilename (module.js:334:15)
  at Function.Module._resolveFilename (C:\Users\Christian España\AppData\Local\atom\app-1.0.15\resources\app.asar\src\module-cache.js:383:52)
  at Function.Module._load (module.js:284:25)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Host.isIgnore (C:\Users\Christian España\.atom\packages\remote-sync\lib\RemoteSync.coffee:40:20)
  at RemoteSync.isIgnore (C:\Users\Christian España\.atom\packages\remote-sync\lib\RemoteSync.coffee:46:18)
  at RemoteSync.uploadFile (C:\Users\Christian España\.atom\packages\remote-sync\lib\RemoteSync.coffee:64:16)
  at C:\Users\Christian España\.atom\packages\remote-sync\index.coffee:101:20
  at Emitter.module.exports.Emitter.emit (C:\Users\Christian España\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
  at TextBuffer.module.exports.TextBuffer.saveAs (C:\Users\Christian España\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1035:20)
  at TextBuffer.module.exports.TextBuffer.save (C:\Users\Christian España\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1002:19)
  at TextEditor.module.exports.TextEditor.save (C:\Users\Christian España\AppData\Local\atom\app-1.0.15\resources\app.asar\src\text-editor.js:584:26)
  at Pane.module.exports.Pane.saveItem (C:\Users\Christian España\AppData\Local\atom\app-1.0.15\resources\app.asar\src\pane.js:547:18)
  at Pane.module.exports.Pane.saveActiveItem (C:\Users\Christian España\AppData\Local\atom\app-1.0.15\resources\app.asar\src\pane.js:530:19)
  at Workspace.module.exports.Workspace.saveActivePaneItem (C:\Users\Christian España\AppData\Local\atom\app-1.0.15\resources\app.asar\src\workspace.js:609:35)
  at atom-workspace.atom.commands.add.core:save (C:\Users\Christian España\AppData\Local\atom\app-1.0.15\resources\app.asar\src\workspace-element.js:293:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Christian España\AppData\Local\atom\app-1.0.15\resources\app.asar\src\command-registry.js:245:29)
  at C:\Users\Christian España\AppData\Local\atom\app-1.0.15\resources\app.asar\src\command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\Christian España\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\Christian España\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (C:\Users\Christian España\AppData\Local\atom\app-1.0.15\resources\app.asar\src\window-event-handler.js:184:20)

```

### Commands

```
     -5:35.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  6x -4:39.2.0 editor:newline (atom-text-editor.editor.is-focused)
  9x -4:36.1.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -4:31.3.0 editor:newline (atom-text-editor.editor.is-focused)
     -4:30.1.0 core:select-up (atom-text-editor.editor.is-focused)
     -4:28.8.0 core:move-down (atom-text-editor.editor.is-focused)
     -4:28.2.0 core:save (atom-text-editor.editor.is-focused)
  5x -2:22.7.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -2:21.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:11.5.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:11.5.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:11.5.0 editor:indent (atom-text-editor.editor.is-focused)
     -0:10.9.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:10.9.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:10.9.0 editor:indent (atom-text-editor.editor.is-focused)
     -0:07.1.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ],
    "disabledPackages": [
      "SFTP-deployment",
      "atom-beautify",
      "linter-php"
    ]
  },
  "remote-sync": {}
}
```

### Installed Packages

```coffee
# User
Remote-FTP, v0.7.2
remote-sync, v3.1.2

# Dev
No dev packages
```

**Comment by yongkangchen** [comment]
Duplicate with #195
