### ISSUE TITLE
Uncaught Error: Cannot find module 'minimatch'

### ISSUE THREAD

**Issue by c42759** [yongkangchen/remote-sync#195]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.15
**System**: Microsoft Windows 10 Enterprise
**Thrown From**: [remote-sync](https://github.com/yongkangchen/remote-sync) package, v3.1.2

### Stack Trace

Uncaught Error: Cannot find module 'minimatch'

```
At module.js:336

Error: Cannot find module 'minimatch'
    at Module._resolveFilename (module.js:334:15)
    at Function.Module._resolveFilename (C:\Users\Critec - João\AppData\Local\atom\app-1.0.15\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:284:25)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Object.module.exports.run (C:\Users\Critec - João\.atom\packages\remote-sync\lib\commands\DownloadAllCommand.coffee:11:21)
    at RemoteSync.downloadFolder (C:\Users\Critec - João\.atom\packages\remote-sync\lib\RemoteSync.coffee:93:26)
    at handleEvent (C:\Users\Critec - João\.atom\packages\remote-sync\index.coffee:64:67)
    at atom-workspace.disposables.add.atom.commands.add.remote-sync:download-folder (C:\Users\Critec - João\.atom\packages\remote-sync\index.coffee:126:18)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Critec - João\AppData\Local\atom\app-1.0.15\resources\app.asar\src\command-registry.js:245:29)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "one-light-ui",

**Comment by nexcode** [comment]
**Atom Version**: 1.0.19
**System**: Unknown Windows Version
**Thrown From**: [remote-sync](https://github.com/yongkangchen/remote-sync) package, v3.1.2


### Stack Trace

Uncaught Error: Cannot find module 'minimatch'

```
At module.js:336

Error: Cannot find module 'minimatch'
  at Module._resolveFilename (module.js:334:15)
  at Function.Module._resolveFilename (C:\Users\Олег\AppData\Local\atom\app-1.0.19\resources\app.asar\src\module-cache.js:383:52)
  at Function.Module._load (module.js:284:25)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.module.exports.run (C:\Users\Олег\.atom\packages\remote-sync\lib\commands\DownloadAllCommand.coffee:7:17)
  at RemoteSync.downloadFolder (C:\Users\Олег\.atom\packages\remote-sync\lib\RemoteSync.coffee:55:17)
  at handleEvent (C:\Users\Олег\.atom\packages\remote-sync\index.coffee:38:14)
  at atom-workspace.disposables.add.atom.commands.add.remote-sync:download-folder (C:\Users\Олег\.atom\packages\remote-sync\index.coffee:78:44)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Олег\AppData\Local\atom\app-1.0.19\resources\app.asar\src\command-registry.js:245:29)
  at CommandRegistry.handleCommandEvent (C:\Users\Олег\AppData\Local\atom\app-1.0.19\resources\app.asar\src\command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\Олег\AppData\Local\atom\app-1.0.19\resources\app.asar\src\command-registry.js:145:19)
  at [object Object].jQuery.fn.trigger (C:\Users\Олег\AppData\Local\atom\app-1.0.19\resources\app.asar\src\space-pen-extensions.js:64:23)
  at EventEmitter.<anonymous> (C:\Users\Олег\AppData\Local\atom\app-1.0.19\resources\app.asar\src\window-event-handler.js:75:67)
  at emitTwo (events.js:87:13)
  at EventEmitter.emit (events.js:172:7)
  at EventEmitter.ipc.sendSync (C:\Users\Олег\AppData\Local\atom\app-1.0.19\resources\atom.asar\renderer\api\lib\ipc.js:21:31)
  at BrowserWindow.RemoteMemberFunction [as emit] (C:\Users\Олег\AppData\Local\atom\app-1.0.19\resources\atom.asar\renderer\api\lib\remote.js:140:29)
  at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (C:\Users\Олег\AppData\Local\atom\app-1.0.19\resources\app.asar\src\context-menu-manager.js:170:31)
  at HTMLDocument.<anonymous> (C:\Users\Олег\AppData\Local\atom\app-1.0.19\resources\app.asar\src\window-event-handler.js:157:33)
  at HTMLDocument.handler (C:\Users\Олег\AppData\Local\atom\app-1.0.19\resources\app.asar\src\space-pen-extensions.js:112:34)
  at HTMLDocument.jQuery.event.dispatch (C:\Users\Олег\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4681:9)
  at HTMLDocument.elemData.handle (C:\Users\Олег\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4359:46)

```

### Commands

```
     -1:43 core:backspace (atom-text-editor#remote-sync.difftoolCommand.editor.mini.is-focused)
  3x -1:20.1.0 core:paste (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {},
  "remote-sync": {
    "difftoolCommand": "Meld"
  }
}
```

### Installed Packages

```coffee
# User
go-plus, v3.5.1
remote-sync, v3.1.2

# Dev
No dev packages
```

**Comment by yongkangchen** [comment]
There are something wrong with install, please try to reinstall this package or atom.
