### ISSUE TITLE
Uncaught Error: [remote-sync] invalid transport: undefined in /Users/eriksvedin/Documents/Project...

### ISSUE THREAD

**Issue by ErikSvedin** [yongkangchen/remote-sync#196]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.16
**System**: Mac OS X 10.10.4
**Thrown From**: [remote-sync](https://github.com/yongkangchen/remote-sync) package, v3.1.2

### Stack Trace

Uncaught Error: [remote-sync] invalid transport: undefined in /Users/eriksvedin/Documents/Projects/forstahand/.remote-sync.json

```
At /Users/eriksvedin/.atom/packages/remote-sync/lib/RemoteSync.coffee:176

Error: [remote-sync] invalid transport: undefined in /Users/eriksvedin/Documents/Projects/forstahand/.remote-sync.json
  at RemoteSync.createTransport (/Users/eriksvedin/.atom/packages/remote-sync/lib/RemoteSync.coffee:104:17)
  at RemoteSync.getTransport (/Users/eriksvedin/.atom/packages/remote-sync/lib/RemoteSync.coffee:110:19)
  at RemoteSync.uploadFile (/Users/eriksvedin/.atom/packages/remote-sync/lib/RemoteSync.coffee:70:37)
  at handleEvent (/Users/eriksvedin/.atom/packages/remote-sync/index.coffee:38:14)
  at atom-workspace.disposables.add.atom.commands.add.remote-sync:upload-file (/Users/eriksvedin/.atom/packages/remote-sync/index.coffee:76:40)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:245:29)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:145:19)
  at [object Object].jQuery.fn.trigger (/Applications/Atom.app/Contents/Resources/app.asar/src/space-pen-extensions.js:64:23)
  at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:75:67)
  at emitTwo (events.js:87:13)
  at EventEmitter.emit (events.js:172:7)
  at EventEmitter.ipc.sendSync (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/ipc.js:21:31)
  at BrowserWindow.RemoteMemberFunction [as emit] (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:140:29)
  at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/context-menu-manager.js:170:31)
  at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:157:33)
  at HTMLDocument.handler (/Applications/Atom.app/Contents/Resources/app.asar/src/space-pen-extensions.js:112:34)
  at HTMLDocument.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/space-pen/vendor/jquery.js:4681:9)
  at HTMLDocument.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/space-pen/vendor/jquery.js:4359:46)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "projectHome": "/Documents/Projects",
    "disabledPackages": [
      "SFTP-deployment",
      "remote-edit"
    ],
    "ignoredNames": [
      "*.pyc"
    ]
  },
  "remote-sync": {}
}
```

### Installed Packages

```coffee
# User
.bin, vundefined
Remote-FTP, v0.7.1
atom-typescript, v4.6.9
auto-detect-indentation, v0.4.2
autoclose-html, v0.18.0
color-picker, v2.0.4
emmet, v2.3.10
linter, v1.0.6
php-twig, v4.0.0
pigments, v0.11.0
remote-sync, v3.1.2

# Dev
No dev packages
```

**Comment by yongkangchen** [comment]
please check `/Users/eriksvedin/Documents/Projects/forstahand/.remote-sync.json` and make sure `transport` is `ftp` or `scp`
