### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '/Users/david.fallas/.ssh/id_rsa.pub'

### ISSUE THREAD

**Issue by DFallas** [yongkangchen/remote-sync#206]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.19
**System**: Mac OS X 10.10.5
**Thrown From**: [remote-sync](https://github.com/yongkangchen/remote-sync) package, v3.1.2

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '/Users/david.fallas/.ssh/id_rsa.pub'

```
At fs.js:549

Error: ENOENT: no such file or directory, open '/Users/david.fallas/.ssh/id_rsa.pub'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:137:20)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:384:29)
    at ScpTransport.module.exports.ScpTransport._getConnection (/Users/davidfallas/.atom/packages/remote-sync/lib/transports/ScpTransport.coffee:121:23)
    at ScpTransport.module.exports.ScpTransport.upload (/Users/davidfallas/.atom/packages/remote-sync/lib/transports/ScpTransport.coffee:24:6)
    at UploadListener.module.exports.UploadListener.uploadFile (/Users/davidfallas/.atom/packages/remote-sync/lib/UploadListener.coffee:18:15)
    at q.process (/Users/davidfallas/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/async/lib/async.js:769:21)
    at doNTCallback0 (node.js:416:9)
```

### Commands

```
     -0:15.2.0 application:add-project-folder (atom-text-editor.editor.is-focused)
     -0:00.7.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {},
  "remote-sync": {}
}
```

### Installed Packages

```coffee
# User
remote-sync, v3.1.2

# Dev
No dev packages
```

**Comment by yongkangchen** [comment]
Does `/Users/david.fallas/.ssh/id_rsa.pub` exist ?

**Comment by rdewolff** [comment]
I have the same issue. Tried with userAgent but nothing happens. File doesn't get uploaded or downloaded.

**Comment by rdewolff** [comment]
Any know issue or workaround?

**Comment by DFallas** [comment]
Hi well that seems to be my SSH key not sure which is the issue it's
causing...
