### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by DomWeldon** [yongkangchen/remote-sync#211]
Hi 

I'm getting the following error on 14.04, also having problems on my Windows installation. Any suggestions, or is this a bug?

Uncaught TypeError: undefined is not a function

**Atom Version**: 0.156.0
**System**: linux 3.13.0-53-generic
**Thrown From**: [remote-sync](https://github.com/yongkangchen/remote-sync) package, v3.3.0

### Steps To Reproduce

1. ...
2. ...

### Stack Trace

```
At /home/domweldon/.atom/packages/remote-sync/index.coffee:16

TypeError: undefined is not a function
  at getEventPath (/home/domweldon/.atom/packages/remote-sync/index.coffee:16:46)
  at atom-workspace.configure (/home/domweldon/.atom/packages/remote-sync/index.coffee:50:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:243:29)
  at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/share/atom/resources/app/src/command-registry.js:156:19)
  at [object Object].jQuery.fn.trigger (/usr/share/atom/resources/app/src/space-pen-extensions.js:64:23)
  at Ipc.<anonymous> (/usr/share/atom/resources/app/src/window-event-handler.js:70:67)
  at Ipc.emit (events.js:110:17)
  at process.<anonymous> (/usr/share/atom/resources/atom/renderer/api/lib/ipc.js:22:29)
  at process.emit (events.js:118:17)
  at Ipc.sendSync (/usr/share/atom/resources/atom/renderer/api/lib/ipc.js:39:29)
  at Ipc.sendChannelSync (/usr/share/atom/resources/atom/renderer/api/lib/ipc.js:47:28)
  at BrowserWindow.RemoteMemberFunction [as emit] (/usr/share/atom/resources/atom/renderer/api/lib/remote.js:110:29)
  at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (/usr/share/atom/resources/app/src/context-menu-manager.js:169:33)
  at HTMLDocument.<anonymous> (/usr/share/atom/resources/app/src/window-event-handler.js:138:33)
  at HTMLDocument.handler (/usr/share/atom/resources/app/src/space-pen-extensions.js:112:34)
  at HTMLDocument.jQuery.event.dispatch (/usr/share/atom/resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at HTMLDocument.elemData.handle (/usr/share/atom/resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)

```

/cc @atom/core

**Comment by yongkangchen** [comment]
You should upgrade your atom.
