### ISSUE TITLE
Uncaught TypeError: _ref.split is not a function

### ISSUE THREAD

**Issue by shaynem** [yongkangchen/remote-sync#215]
1. Added uploadMirrors   -- works fine without the uploadMirrors
```json
{
  "transport": "ftp",
  "hostname": "ipaddress",
  "port": 22,
  "username": "username",
  "password": "password",
  "target": "/path/to",
  "uploadOnSave": true,
  "ignore": [
    ".git/**",
		"sftp-config.json",
		".remote-sync.json"
  ],
  "uploadMirrors":[
    {
	  "transport": "scp",
          "hostname": "ipaddress",
          "port": 22,
          "username": "username",
          "password": "password",
          "target": "/path/to",
          "uploadOnSave": true,
          "ignore": [
          ".git /**",
		"sftp-config.json",
		".remote-sync.json"
        ]
   }
]
}
```
**Atom Version**: 1.2.0
**System**: Mac OS X 10.10.5
**Thrown From**: [remote-sync](https://github.com/yongkangchen/remote-sync) package, v3.4.0

### Stack Trace

Uncaught TypeError: _ref.split is not a function

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:825

TypeError: _ref.split is not a function
    at RemoteSync.initIgnore (/Users/shayne/.atom/packages/remote-sync/lib/RemoteSync.coffee:33:27)
    at RemoteSync.getUploadMirrors (/Users/shayne/.atom/packages/remote-sync/lib/RemoteSync.coffee:119:10)
    at RemoteSync.uploadFile (/Users/shayne/.atom/packages/remote-sync/lib/RemoteSync.coffee:71:5)
    at /Users/shayne/.atom/packages/remote-sync/index.coffee:111:20
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
    at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1035:20)
    at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1002:19)
    at TextEditor.module.exports.TextEditor.save (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:557:26)
    at Pane.module.exports.Pane.saveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:530:18)
    at Pane.module.exports.Pane.saveActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:513:19)
```

### Commands

```
     -0:09.7.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "bububad"
    ],
    "disabledPackages": [
      "SFTP-deployment"
    ]
  }
}
```

### Installed Packages

```coffee
# User
bububad, v0.1.0
highlight-line, v0.11.0
highlight-selected, v0.11.1
language-batchfile, v0.4.0
remote-sync, v3.4.0

# Dev
No dev packages
```

**Comment by yongkangchen** [comment]
you should use `".git/**", ` instead of `".git /**", `, which should not contain a space between `".git` and `/**`

**Comment by Sajonara** [comment]
As it seems, this works, if you leave away the second "ignore" option. Both or all of the mirrors will use the "ignore" option inherited by the parent element. Tried it, worked.

**Comment by enoversum** [comment]
Well, @yongkangchen , I have the same message when it ignores `".git/**"`, as is the default.
