### ISSUE TITLE
Uncaught TypeError: Cannot read property 'toString' of undefined

### ISSUE THREAD

**Issue by xale94** [yongkangchen/remote-sync#220]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.2.4
**System**: Unknown Windows Version
**Thrown From**: [remote-sync](https://github.com/yongkangchen/remote-sync) package, v3.5.0

### Stack Trace

Uncaught TypeError: Cannot read property 'toString' of undefined

```
At C:\Users\fran\.atom\packages\remote-sync\node_modules\ssh2\lib\Parser.js:721

TypeError: Cannot read property 'toString' of undefined
    at Parser.hmacVerify (C:\Users\fran\.atom\packages\remote-sync\node_modules\ssh2\lib\Parser.js:721:47)
    at Parser.execute (C:\Users\fran\.atom\packages\remote-sync\node_modules\ssh2\lib\Parser.js:224:18)
    at Socket.<anonymous> (C:\Users\fran\.atom\packages\remote-sync\node_modules\ssh2\lib\Connection.js:523:18)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)
```

### Commands

```
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
atom-blue-chat, v1.23.0
atom-jade, v0.3.0
atom-pair, v2.0.10
color-picker, v2.0.13
csslint, v1.1.4
docblockr, v0.7.3
file-icons, v1.6.12
highlight-selected, v0.11.1
jshint, v1.8.3
linter-jade, v0.3.2
minimap, v4.16.2
pigments, v0.19.0
remote-edit, v1.8.22
remote-sync, v3.5.0
w3c-validation, v0.2.0

# Dev
No dev packages
```

**Comment by elistone** [comment]
@xale94 is this still an issue?

**Comment by elistone** [comment]
There has been no response to this ticket as such it will now be closed.
If the issue still exists please reply and we will look into it.
