### ISSUE TITLE
Cannot read property 'uploadGitChange' of undefined

### ISSUE THREAD

**Issue by matthewjrallen** [yongkangchen/remote-sync#222]
1. Trying to upload files. All give errors.

**Atom Version**: 1.2.4
**System**: Mac OS X 10.11.1
**Thrown From**: [remote-sync](https://github.com/yongkangchen/remote-sync) package, v3.5.0

### Stack Trace

Uncaught TypeError: Cannot read property 'uploadGitChange' of undefined

```
At /Users/matt/.atom/packages/remote-sync/index.coffee:42

TypeError: Cannot read property 'uploadGitChange' of undefined
    at handleEvent (/Users/matt/.atom/packages/remote-sync/index.coffee:42:3)
    at atom-workspace.disposables.add.atom.commands.add.remote-sync:upload-git-change (/Users/matt/.atom/packages/remote-sync/index.coffee:92:46)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:159:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
    at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:533:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:356:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:99:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
  5x -4:20.3.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -3:38.5.0 remote-sync:diff-file (li.file.entry.list-item.status-added.selected)
     -2:09.5.0 command-palette:toggle (div.package-detail.panels-item)
     -1:54.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:47.5.0 remote-sync:upload-git-change (span.name.icon.icon-repo)
  3x -1:12.6.0 core:page-up (div.package-detail.panels-item)
     -0:29.4.0 command-palette:toggle (button.btn.btn-default.icon.icon-link-external)
     -0:26.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:26.2.0 remote-sync:configure (button.btn.btn-default.icon.icon-link-external)
     -0:22.1.0 command-palette:toggle (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:18.7.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:13.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:10.3.0 command-palette:toggle (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
 18x -0:08.3.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:01.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:01.2.0 remote-sync:upload-git-change (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Config

```json
{
  "core": {
    "themes": [
      "native-ui",
      "batman-syntax"
    ],
    "disabledPackages": [
      "wrap-guide",
      "autoflow"
    ]
  },
  "remote-sync": {}
}
```

### Installed Packages

```coffee
# User
atom-minify, v0.6.2
autoclose-html, v0.19.0
batman-syntax, v1.0.1
color-picker, v2.0.13
file-icons, v1.6.12
highlight-line, v0.11.0
less-than-slash, v0.11.1
minimap, v4.16.2
native-ui, v0.9.0
pigments, v0.19.0
project-manager, v2.6.5
remote-sync, v3.5.0
sync-settings, v0.6.0

# Dev
No dev packages
```

**Comment by elistone** [comment]
@matthewjrallen Are you still having this issue?

**Comment by elistone** [comment]
There has been no response to this ticket as such it will now be closed.
If the issue still exists please reply and we will look into it.
