### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by josemoises** [yongkangchen/remote-sync#226]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.175.0
**System**: Unknown Windows Version
**Thrown From**: [remote-sync](https://github.com/yongkangchen/remote-sync) package, v3.1.2

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /c:/Users/moises.chavez/.atom/packages/remote-sync/index.coffee:147

TypeError: undefined is not a function
  at c:\Users\moises.chavez\.atom\packages\remote-sync\index.coffee:91:52
  at Emitter.module.exports.Emitter.emit (c:\Users\moises.chavez\AppData\Local\atom\app-0.175.0\resources\app\node_modules\service-hub\node_modules\event-kit\lib\emitter.js:82:11)
  at TextBuffer.module.exports.TextBuffer.saveAs (c:\Users\moises.chavez\AppData\Local\atom\app-0.175.0\resources\app\node_modules\text-buffer\lib\text-buffer.js:974:20)
  at TextBuffer.module.exports.TextBuffer.save (c:\Users\moises.chavez\AppData\Local\atom\app-0.175.0\resources\app\node_modules\text-buffer\lib\text-buffer.js:958:19)
  at TextEditor.module.exports.TextEditor.save (c:\Users\moises.chavez\AppData\Local\atom\app-0.175.0\resources\app\src\text-editor.js:617:26)
  at Pane.module.exports.Pane.saveItem (c:\Users\moises.chavez\AppData\Local\atom\app-0.175.0\resources\app\src\pane.js:538:16)
  at Pane.module.exports.Pane.saveItems (c:\Users\moises.chavez\AppData\Local\atom\app-0.175.0\resources\app\src\pane.js:565:28)
  at PaneContainer.module.exports.PaneContainer.saveAll (c:\Users\moises.chavez\AppData\Local\atom\app-0.175.0\resources\app\src\pane-container.js:245:28)
  at Workspace.module.exports.Workspace.saveAll (c:\Users\moises.chavez\AppData\Local\atom\app-0.175.0\resources\app\src\workspace.js:671:33)
  at atom-workspace.atom.commands.add.window:save-all (c:\Users\moises.chavez\AppData\Local\atom\app-0.175.0\resources\app\src\workspace-element.js:277:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (c:\Users\moises.chavez\AppData\Local\atom\app-0.175.0\resources\app\src\command-registry.js:243:29)
  at CommandRegistry.handleCommandEvent (c:\Users\moises.chavez\AppData\Local\atom\app-0.175.0\resources\app\src\command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (c:\Users\moises.chavez\AppData\Local\atom\app-0.175.0\resources\app\src\command-registry.js:156:19)
  at Ipc.<anonymous> (c:\Users\moises.chavez\AppData\Local\atom\app-0.175.0\resources\app\src\window-event-handler.js:65:30)
  at Ipc.emit (events.js:107:17)
  at process.<anonymous> (c:\Users\moises.chavez\AppData\Local\atom\app-0.175.0\resources\atom\renderer\api\lib\ipc.js:22:29)
  at process.emit (events.js:110:17)

```

### Commands

```
     -9:55.4 core:confirm (atom-text-editor.editor.mini)
  3x -9:34.8 core:save (atom-text-editor.editor)
  4x -7:50.3 core:confirm (atom-text-editor.editor.mini)
     -1:34.1 core:backspace (atom-text-editor.editor)
  2x -0:00.0 window:save-all (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "remote-sync": {}
}
```

### Installed Packages

```coffee
# User
remote-sync, v3.1.2

# Dev
No dev packages
```

/cc @atom/core

**Comment by elistone** [comment]
@josemoises Are you still having this issue?

**Comment by elistone** [comment]
There has been no response to this ticket as such it will now be closed.
If the issue still exists please reply and we will look into it.
