### ISSUE TITLE
Uncaught TypeError: Cannot read property 'downloadFolder' of undefined

### ISSUE THREAD

**Issue by thiagodebastos** [yongkangchen/remote-sync#233]
[Enter steps to reproduce below:]
1. Right click folder > download folder
2. ...

**Atom Version**: 1.3.2
**System**: Mac OS X 10.11.2
**Thrown From**: [remote-sync](https://github.com/yongkangchen/remote-sync) package, v3.5.0
### Stack Trace

Uncaught TypeError: Cannot read property 'downloadFolder' of undefined

```
At /Users/thiago/.atom/packages/remote-sync/index.coffee:42

TypeError: Cannot read property 'downloadFolder' of undefined
    at handleEvent (/Users/thiago/.atom/packages/remote-sync/index.coffee:42:3)
    at atom-workspace.disposables.add.atom.commands.add.remote-sync:download-folder (/Users/thiago/.atom/packages/remote-sync/index.coffee:89:44)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:183:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
    at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
     -0:52.7.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:52.7.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:51.5.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  2x -0:48 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:42.9.0 editor:select-to-first-character-of-line (atom-text-editor.editor.mini.is-focused)
     -0:28.8.0 core:copy (div.package-readme.native-key-bindings)
     -0:28.1.0 command-palette:toggle (div.package-readme.native-key-bindings)
     -0:27 core:paste (atom-text-editor.editor.mini.is-focused)
     -0:26.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:24.1.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:23.6.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -0:23.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:11.1.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:05.4.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:04.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:04.6.0 remote-sync:download-folder (atom-text-editor.editor)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "wrap-guide",
      "copy-as-rtf",
      "highlight-column",
      "w3c-validation",
      "css-specificity",
      "minimap-highlight-selected",
      "minimap-git-diff",
      "minimap-find-and-replace",
      "minimap-bookmarks",
      "linter-eslint",
      "jslint",
      "minimap",
      "svg-preview",
      "metrics",
      "method-separator"
    ],
    "ignoredNames": [
      "node_modules",
      ".DS_Store",
      ".git",
      "_brief"
    ],
    "themes": [
      "native-ui",
      "tomorrow-night-eighties-syntax"
    ]
  },
  "remote-sync": {}
}
```
### Installed Packages

``` coffee
# User
Remote-FTP, v0.7.15
Stylus, v1.2.1
Sublime-Style-Column-Selection, v1.3.0
atom-alignment, v0.12.1
atom-beautify, v0.28.19
atom-handlebars, v1.3.0
atom-html-preview, v0.1.13
atom-jade, v0.3.0
atom-jshint, v2.0.0
build, v0.52.0
color-picker, v2.0.14
editorconfig, v1.2.2
emmet, v2.3.17
file-icons, v1.6.13
file-types, v0.5.1
jquery-snippets, v11.0.0
language-javascript-jsx, v0.3.7
language-nunjucks, v2.0.0
language-svg, v0.9.0
linter, v1.11.3
linter-haml, v1.0.0
linter-handlebars, v2.3.1
linter-jade, v0.3.2
linter-stylint, v2.0.1
meteor-api, v2.20.0
native-ui, v0.11.0
pigments, v0.19.5
project-manager, v2.6.5
remote-sync, v3.5.0
tomorrow-night-eighties-syntax, v0.11.0
tree-view-git-branch, v0.0.6
wakatime, v5.0.2

# Dev
No dev packages
```

**Comment by thiagodebastos** [comment]
Note: The issue goes away by quitting and reloading Atom..

**Comment by elistone** [comment]
@thiagodebastos Are you still having this issue?

**Comment by bigscaryduck** [comment]
Had the same error. Restarted Atom fresh and the error was no longer there. Steps to recreate:

1. 1. Create a new empty folder
2. Open the newly created folder in Atom
3. Create new file using Atom and add all the remote-sync settings
4. Save new file as ".remote-sync.json" in the new folder
5. Right click on the Folder header in Atom a under the "Remote Sync" sub-menu click on "Download Folder"

**Comment by Ducatel** [comment]
This issue append when you create the `.remote-sync.json` and try to upload (by file, folder, etc....) directly without any atom restart.

--> Work well when you restart your atom.

**Comment by jorijnsmit** [comment]
Note that you are suppose to save the .remote-sync.json file in the same directory as the folder you are trying to download is in.

It helped me to configure via the menu (RIght Click folder -> Remote Sync -> Configure) to see where the config file goes...

**Comment by xemasiv** [comment]
Thank you.

**Comment by thiagodebastos** [comment]
I'm cleaning up some old issues. I assume this was fixed by:
https://github.com/yongkangchen/remote-sync/issues/233#issuecomment-250431762
