### ISSUE TITLE
Uncaught TypeError: Cannot read property 'buffer' of undefined

### ISSUE THREAD

**Issue by lalitindoria** [yongkangchen/remote-sync#235]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.3.2
**System**: Ubuntu 14.04.3
**Thrown From**: [remote-sync](https://github.com/yongkangchen/remote-sync) package, v3.5.0

### Stack Trace

Uncaught TypeError: Cannot read property 'buffer' of undefined

```
At /home/karuppayya/.atom/packages/remote-sync/node_modules/ssh2/lib/SFTP/SFTPv3.js:1151

TypeError: Cannot read property 'buffer' of undefined
    at SFTP._readString (/home/karuppayya/.atom/packages/remote-sync/node_modules/ssh2/lib/SFTP/SFTPv3.js:1151:61)
    at SFTP._parse (/home/karuppayya/.atom/packages/remote-sync/node_modules/ssh2/lib/SFTP/SFTPv3.js:1018:31)
    at ChannelStream.<anonymous> (/home/karuppayya/.atom/packages/remote-sync/node_modules/ssh2/lib/SFTP/SFTPv3.js:49:12)
    at emitOne (events.js:77:13)
    at ChannelStream.emit (events.js:169:7)
    at ChannelStream.emit (/home/karuppayya/.atom/packages/remote-sync/node_modules/ssh2/lib/Channel.js:640:12)
    at Parser.<anonymous> (/home/karuppayya/.atom/packages/remote-sync/node_modules/ssh2/lib/Channel.js:95:20)
    at emitOne (events.js:77:13)
    at Parser.emit (events.js:169:7)
    at Parser.parsePacket (/home/karuppayya/.atom/packages/remote-sync/node_modules/ssh2/lib/Parser.js:607:12)
    at Parser.execute (/home/karuppayya/.atom/packages/remote-sync/node_modules/ssh2/lib/Parser.js:249:14)
    at Socket.<anonymous> (/home/karuppayya/.atom/packages/remote-sync/node_modules/ssh2/lib/Connection.js:523:18)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)
```

### Commands

```
     -1:48.7.0 core:select-left (atom-text-editor.editor.is-focused)
     -1:45 core:save (atom-text-editor.editor.is-focused)
     -1:26.7.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -1:25.6.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -1:24.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -1:20 command-palette:toggle (atom-text-editor.editor.is-focused)
     -1:06.5.0 core:paste (atom-text-editor.editor.mini.is-focused)
 14x -1:05.4.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:54.9.0 remote-sync:configure (atom-text-editor.editor)
  8x -0:45.9.0 core:move-left (atom-text-editor.editor.mini.is-focused)
     -0:34.5.0 command-palette:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
  2x -0:28.1.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:10.6.0 command-palette:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:02.9.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:02.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:02.5.0 remote-sync:download-folder (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Config

```json
{
  "core": {},
  "remote-sync": {}
}
```

### Installed Packages

```coffee
# User
laravel, v0.7.0
remote-atom, v1.3.9
remote-sync, v3.5.0

# Dev
No dev packages
```

**Comment by elistone** [comment]
@lalitindoria Are you still having this issue?

**Comment by lalitindoria** [comment]
@elistone Haven't tried this lately, will let you know if I get this again :)
