### ISSUE TITLE
Uncaught TypeError: Cannot read property 'downloadFolder' of undefined

### ISSUE THREAD

**Issue by heubergen** [yongkangchen/remote-sync#241]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.4.1
**System**: Mac OS X 10.11.4
**Thrown From**: [remote-sync](https://github.com/yongkangchen/remote-sync) package, v3.5.0

### Stack Trace

Uncaught TypeError: Cannot read property 'downloadFolder' of undefined

```
At /Users/patrickalbrecht/.atom/packages/remote-sync/index.coffee:42

TypeError: Cannot read property 'downloadFolder' of undefined
    at handleEvent (/Users/patrickalbrecht/.atom/packages/remote-sync/index.coffee:42:3)
    at atom-workspace.disposables.add.atom.commands.add.remote-sync:download-folder (/Users/patrickalbrecht/.atom/packages/remote-sync/index.coffee:89:44)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1019:28)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
    at EventEmitter.ipc.sendSync (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/ipc.js:21:31)
    at BrowserWindow.RemoteMemberFunction [as emit] (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:143:29)
    at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/context-menu-manager.js:156:33)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentContextmenu (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:250:47)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -0:00.7.0 remote-sync:download-folder (span.name.icon.icon-file-directory)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "remote-sync": {}
}
```

### Installed Packages

```coffee
# User
remote-sync, v3.5.0

# Dev
No dev packages
```
I know that the error was already reported with #167 but there the issue is closed without any comment.

**Comment by elistone** [comment]
There is an issue open for this, see #233 and give it a thumbs up.
Closing.
