### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '/Users/moonnshinwoo/PhpstormProjects/ft...

### ISSUE THREAD

**Issue by chocoma87** [yongkangchen/remote-sync#243]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.4.1
**System**: Mac OS X 10.11.3
**Thrown From**: [remote-sync](https://github.com/yongkangchen/remote-sync) package, v3.5.0

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/Users/moonnshinwoo/PhpstormProjects/ftp_test/.remote-sync.json'

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:829

Error: ENOENT: no such file or directory, lstat '/Users/moonnshinwoo/PhpstormProjects/ftp_test/.remote-sync.json'
    at Error (native)
    at fs.lstatSync (fs.js:844:18)
    at Object.fs.lstatSync (ATOM_SHELL_ASAR.js:189:16)
    at Object.realpathSync (fs.js:1454:21)
    at Object.fs.realpathSync (ATOM_SHELL_ASAR.js:262:29)
    at /Users/moonnshinwoo/.atom/packages/remote-sync/index.coffee:109:44
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1067:27)
    at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1037:19)
    at TextEditor.module.exports.TextEditor.save (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:602:26)
    at Pane.module.exports.Pane.saveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:534:18)
    at Pane.module.exports.Pane.saveActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:517:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:643:35)
    at atom-workspace.commandRegistry.add.core:save (/Applications/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:173:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -2:10.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -2:10.8.0 remote-sync:configure (div.package-detail.panels-item)
     -2:05.7.0 tree-view:move (span.name.icon.icon-file-text)
     -2:05.2.0 core:move-left (atom-text-editor.editor.mini.is-focused)
     -2:04.8.0 core:move-right (atom-text-editor.editor.mini.is-focused)
     -2:04.2.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -2:03.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -2:01.8.0 core:close (atom-text-editor.editor.is-focused)
     -1:57.5.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  7x -1:53.6.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -1:47.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:47.3.0 remote-sync:download-file (atom-text-editor.editor)
     -0:22.3.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:21.4.0 core:save (atom-text-editor.editor.is-focused)
     -0:05.9.0 core:close (atom-text-editor.editor.is-focused)
     -0:00.6.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {},
  "remote-sync": {}
}
```

### Installed Packages

```coffee
# User
remote-sync, v3.5.0

# Dev
No dev packages
```

**Comment by yongkangchen** [comment]
It seems that your config file is missing?
