### ISSUE TITLE
Failed to load the remote-sync package

### ISSUE THREAD

**Issue by vincenicoara** [yongkangchen/remote-sync#245]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.4.3
**System**: Mac OS X 10.11.2
**Thrown From**: [remote-sync](https://github.com/yongkangchen/remote-sync) package, v3.5.0

### Stack Trace

Failed to load the remote-sync package

```
At Cannot find module 'fs-plus'

Error: Cannot find module 'fs-plus'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/Users/Vince/Downloads/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (/Users/Vince/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/Vince/.atom/packages/remote-sync/index.coffee:1:6)
    at Object.<anonymous> (/Users/Vince/.atom/packages/remote-sync/index.coffee:1:1)
    at Module._compile (/Users/Vince/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Users/Vince/Downloads/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Users/Vince/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/Users/Vince/Downloads/Atom.app/Contents/Resources/app.asar/src/package.js:722:27)
    at /Users/Vince/Downloads/Atom.app/Contents/Resources/app.asar/src/package.js:117:28
    at Package.module.exports.Package.measure (/Users/Vince/Downloads/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at Package.module.exports.Package.load (/Users/Vince/Downloads/Atom.app/Contents/Resources/app.asar/src/package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/Users/Vince/Downloads/Atom.app/Contents/Resources/app.asar/src/package-manager.js:443:14)
    at PackageManager.module.exports.PackageManager.loadPackages (/Users/Vince/Downloads/Atom.app/Contents/Resources/app.asar/src/package-manager.js:393:14)
    at AtomEnvironment.module.exports.AtomEnvironment.startEditorWindow (/Users/Vince/Downloads/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:684:21)
    at module.exports (/Users/Vince/Downloads/Atom.app/Contents/Resources/app.asar/src/initialize-application-window.js:28:10)
    at setupWindow (file:///Users/Vince/Downloads/Atom.app/Contents/Resources/app.asar/static/index.js:86:5)
    at window.onload (file:///Users/Vince/Downloads/Atom.app/Contents/Resources/app.asar/static/index.js:41:9)
```

### Commands

```
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
remote-sync, v3.5.0

# Dev
No dev packages
```

**Comment by yongkangchen** [comment]
It seems that something wrong with your install.
You can try reinstall this package

**Comment by mikkame** [comment]
I also encountered the same bug
```
Cannot find module 'fs-plus'
Hide Stack Trace
Error: Cannot find module 'fs-plus'
  at Module._resolveFilename (module.js:336:15)
  at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
  at Function.Module._load (module.js:286:25)
  at Module.require (module.js:365:17)
  at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
  at Object.<anonymous> (/Users/mikami/.atom/packages/remote-sync/index.coffee:1:6)
  at Object.<anonymous> (/Users/mikami/.atom/packages/remote-sync/index.coffee:1:1)
  at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
  at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
  at Module.load (module.js:355:32)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
  at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:720:27)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:116:28
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
  at Package.module.exports.Package.load (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:106:12)
```

System: Mac OS X 10.11.1
Atom Version: 1.6.2
 remote-syn: v4.0.0

**Comment by yongkangchen** [comment]
It seems that you install remote-sync package via terminal? If so, did you run `apm install` in remote-sync package folder?

**Comment by mikkame** [comment]
I'm sorry, I do not remember. Maybe, with apm install.(```apm install remote-sync // home dir```)
However, after installation, about one month was working normally.

Also, I'm using the "auto-update-packages"
It might have caused the defect in the automatic update Maybe.



It began to work in the re-installation.
Thank you!
