### ISSUE TITLE
Uncaught Error: [remote-sync] invalid transport: undefined in /Users/vaibhavchauhan/x/.remote-syn...

### ISSUE THREAD

**Issue by vaibhav-rbs** [yongkangchen/remote-sync#249]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.5.3
**System**: Mac OS X 10.11.3
**Thrown From**: [remote-sync](https://github.com/yongkangchen/remote-sync) package, v3.5.0

### Stack Trace

Uncaught Error: [remote-sync] invalid transport: undefined in /Users/vaibhavchauhan/x/.remote-sync.json

```
At /Users/vaibhavchauhan/.atom/packages/remote-sync/lib/RemoteSync.coffee:119

Error: [remote-sync] invalid transport: undefined in /Users/vaibhavchauhan/x/.remote-sync.json
    at RemoteSync.createTransport (/Users/vaibhavchauhan/.atom/packages/remote-sync/lib/RemoteSync.coffee:119:17)
    at RemoteSync.getTransport (/Users/vaibhavchauhan/.atom/packages/remote-sync/lib/RemoteSync.coffee:125:19)
    at RemoteSync.uploadFile (/Users/vaibhavchauhan/.atom/packages/remote-sync/lib/RemoteSync.coffee:84:37)
    at handleEvent (/Users/vaibhavchauhan/.atom/packages/remote-sync/index.coffee:46:14)
    at atom-workspace.disposables.add.atom.commands.add.remote-sync:upload-file (/Users/vaibhavchauhan/.atom/packages/remote-sync/index.coffee:85:40)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Users/vaibhavchauhan/Downloads/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/Users/vaibhavchauhan/Downloads/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Users/vaibhavchauhan/Downloads/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/Users/vaibhavchauhan/Downloads/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1019:28)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
    at EventEmitter.ipc.sendSync (/Users/vaibhavchauhan/Downloads/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/ipc.js:21:31)
    at BrowserWindow.RemoteMemberFunction [as emit] (/Users/vaibhavchauhan/Downloads/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:143:29)
    at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (/Users/vaibhavchauhan/Downloads/Atom.app/Contents/Resources/app.asar/src/context-menu-manager.js:156:33)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentContextmenu (/Users/vaibhavchauhan/Downloads/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:250:47)
    at HTMLDocument.<anonymous> (/Users/vaibhavchauhan/Downloads/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
  2x -0:06.7.0 core:save (atom-text-editor.editor.is-focused)
     -0:00.7.0 remote-sync:upload-file (li.file.entry.list-item.selected)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
remote-sync, v3.5.0

# Dev
No dev packages
```

**Comment by yongkangchen** [comment]
I think you did not set your transport type in .remote-sync.json
see https://github.com/yongkangchen/remote-sync/blob/master/README.md
