### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '/Users/MrRD/Desktop/.remote-sync.json'

### ISSUE THREAD

**Issue by MrRDJack** [yongkangchen/remote-sync#273]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.7.2
**System**: Mac OS X 10.11.5
**Thrown From**: [remote-sync](https://github.com/yongkangchen/remote-sync) package, v4.0.1
### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/Users/MrRD/Desktop/.remote-sync.json'

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:1002

Error: ENOENT: no such file or directory, lstat '/Users/MrRD/Desktop/.remote-sync.json'
    at Error (native)
    at fs.lstatSync (fs.js:887:18)
    at Object.fs.lstatSync (ATOM_SHELL_ASAR.js:229:16)
    at Object.realpathSync (fs.js:1532:21)
    at Object.fs.realpathSync (ATOM_SHELL_ASAR.js:304:29)
    at /Users/MrRD/.atom/packages/remote-sync/index.coffee:116:44
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1104:27)
    at TextEditor.module.exports.TextEditor.saveAs (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:666:26)
    at Pane.module.exports.Pane.saveItemAs (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:742:16)
    at Pane.module.exports.Pane.saveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:726:21)
    at Pane.module.exports.Pane.saveActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:701:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:684:35)
    at atom-workspace.commandRegistry.add.core:save (/Applications/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:214:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
     -3:46.1.0 tree-view:remove (span.name.icon.icon-file-text)
     -3:37.4.0 fuzzy-finder:toggle-file-finder (ul.list-inline.tab-bar.inset-panel)
     -3:35.1.0 core:close (atom-text-editor.editor.is-focused)
     -3:33.9.0 application:new-file (atom-text-editor.editor.is-focused)
  2x -3:08.5.0 core:paste (atom-text-editor.editor.is-focused)
     -2:45.4.0 editor:newline (atom-text-editor.editor.is-focused)
     -2:45.2.0 core:paste (atom-text-editor.editor.is-focused)
     -2:44.8.0 core:save (atom-text-editor.editor.is-focused)
  2x -2:21 core:paste (atom-text-editor.editor.is-focused)
     -1:18.3.0 core:save (atom-text-editor.editor.is-focused)
     -0:56.7.0 core:select-all (atom-text-editor.editor.is-focused)
     -0:56.2.0 core:copy (atom-text-editor.editor.is-focused)
     -0:07.8.0 application:new-file (atom-text-editor.editor.is-focused)
  5x -0:06.3.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:05.2.0 core:paste (atom-text-editor.editor.is-focused)
     -0:04.6.0 core:save (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "Remote-FTP"
    ]
  },
  "remote-sync": {}
}
```
### Installed Packages

``` coffee
# User
remote-sync, v4.0.1
terminal-plus, v0.14.5

# Dev
No dev packages
```

**Comment by daverickdunn** [comment]
After a good deal of investigation, I'm fairly certain this was caused by an issue with the core node 'fs' module used in Electron 1.3.x and earlier. It's difficult to pinpoint exactly where the versions match up as the release notes for Electron and Atom are limited to only a few versions back. However, this issue was prevalent across many Atom packages at the time, and appears to be fixed since Atom 1.19.x (which included an upgrade from Electron 1.3.x to 1.6.x).
