### ISSUE TITLE
Uncaught Error: [remote-sync] invalid transport: undefined in .remote-sync.json

### ISSUE THREAD

**Issue by IvanGanev** [yongkangchen/remote-sync#285]
Hi! The first time everything worked well - the files were downloaded without errors. But now it gives an error. Yes, the same monitor file animation worked, and now does not. I, of course, a lot of times restarted the Atom. Upload On Save is not working the same.

[Enter steps to reproduce below:]
1. Right click main project folder
2. Folder Upload (or Upload Folder Change)

**Atom Version**: 1.7.4
**System**: Mac OS X 10.11.5
**Thrown From**: [remote-sync](https://github.com/yongkangchen/remote-sync) package, v4.1.2
### Stack Trace

Uncaught Error: [remote-sync] invalid transport: undefined in /Users/ivanganev/Documents/project/Ganev ru/bootstrap_less/.remote-sync.json

```
At /Users/ivanganev/.atom/packages/remote-sync/lib/RemoteSync.coffee:252

Error: [remote-sync] invalid transport: undefined in /Users/ivanganev/Documents/project/Ganev ru/bootstrap_less/.remote-sync.json
    at RemoteSync.createTransport (/Users/ivanganev/.atom/packages/remote-sync/lib/RemoteSync.coffee:252:17)
    at RemoteSync.getTransport (/Users/ivanganev/.atom/packages/remote-sync/lib/RemoteSync.coffee:258:19)
    at RemoteSync.uploadFile (/Users/ivanganev/.atom/packages/remote-sync/lib/RemoteSync.coffee:107:37)
    at /Users/ivanganev/.atom/packages/remote-sync/lib/RemoteSync.coffee:241:8
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/fs-plus/lib/fs-plus.js:399:17
    at FSReqWrap.oncomplete (fs.js:82:15)
```
### Commands

```
     -0:47.2.0 remote-sync:upload-git-change (span.name.icon.icon-repo)
     -0:05.6.0 remote-sync:upload-folder (span.name.icon.icon-repo)
     -0:00.9.0 remote-sync:upload-git-change (span.name.icon.icon-repo)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "atom-compile-less",
      "less-compiler",
      "atom-less",
      "minimap",
      "pigments",
      "remote-edit"
    ],
    "themes": [
      "one-light-ui",
      "gruvbox-plus-syntax"
    ]
  },
  "remote-sync": {
    "logToConsole": true
  }
}
```
### Installed Packages

``` coffee
# User
css-snippets, v0.9.0
file-icons, v1.7.12
gruvbox-plus-syntax, v1.2.1
less-autocompile, v1.0.0
remote-sync, v4.1.2
source-preview-less, v0.1.3

# Dev
No dev packages
```

**Comment by elistone** [comment]
Can you check that in `.remote-sync.json` there is a `transport` type set and it is set to be `scp` or `ftp`

**Comment by joe-tofu** [comment]
I've got the same problem while trying to upload files. 

**Error**
`/Users/USER/.atom/packages/remote-sync/lib/RemoteSync.coffee:252`
`Error: [remote-sync] invalid transport: undefined in /Users/jmayer/wowitmoves/_WEBDEV/eat-this.local/wp-content/themes/eat-this-v3.5/.remote-sync.json
    at RemoteSync.createTransport (/Users/jmayer/.atom/packages/remote-sync/lib/RemoteSync.coffee:249:7)
    at RemoteSync.getTransport (/Users/jmayer/.atom/packages/remote-sync/lib/RemoteSync.coffee:257:5)
    at RemoteSync.uploadFile (/Users/jmayer/.atom/packages/remote-sync/lib/RemoteSync.coffee:107:37)
    at handleEvent (/Users/jmayer/.atom/packages/remote-sync/index.coffee:46:14)
    at atom-workspace.disposables.add.atom.commands.add.remote-sync:upload-file (/Users/jmayer/.atom/packages/remote-sync/index.coffee:95:40)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1106:28)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:340:25)
    at emitThree (events.js:97:13)
    at EventEmitter.emit (events.js:175:7)`

**.remote-sync.json**
`{
  "transport": "ftp",
  "hostname": "SERVERHOSTNAME",
  "port": 21,
  "username": "USER",
  "password": "PASS",
  "target": "TARGET",
  "ignore": [
    ".remote-sync.json",
    ".git/**",
  ],
  "watch":[
    "style.css",
  ]
}
`

**Comment by daverickdunn** [comment]
Thanks. This was a misleading error caused by the JSON in the config file being invalid, (usually a missing comma, etc.). The error was being suppressed, but now it's being displayed with commit: https://github.com/yongkangchen/remote-sync/commit/770f9267ae2639f98275f94e729d5d61ff2e1ebe
