### ISSUE TITLE
Uncaught TypeError: Cannot read property 'uploadGitChange' of undefined

### ISSUE THREAD

**Issue by MrRDJack** [yongkangchen/remote-sync#291]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.6
**Thrown From**: [remote-sync](https://github.com/yongkangchen/remote-sync) package, v4.1.2

### Stack Trace

Uncaught TypeError: Cannot read property 'uploadGitChange' of undefined

```
At /Users/MrRD/.atom/packages/remote-sync/index.coffee:42

TypeError: Cannot read property 'uploadGitChange' of undefined
    at handleEvent (/Users/MrRD/.atom/packages/remote-sync/index.coffee:42:3)
    at atom-workspace.disposables.add.atom.commands.add.remote-sync:upload-git-change (/Users/MrRD/.atom/packages/remote-sync/index.coffee:102:46)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1106:28)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:340:25)
    at emitThree (events.js:97:13)
    at EventEmitter.emit (events.js:175:7)
```

### Commands

```
  5x -1:13.3.0 tree-view:toggle (ul.list-inline.tab-bar.inset-panel)
     -0:36.7.0 tree-view:remove (li.file.entry.list-item.selected)
     -0:00.5.0 remote-sync:upload-git-change (span.name.icon.icon-file-directory)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ]
  },
  "remote-sync": {}
}
```

### Installed Packages

```coffee
# User
Remote-FTP, v0.8.3
remote-sync, v4.1.2
terminal-plus, v0.14.5

# Dev
No dev packages
```

**Comment by elistone** [comment]
@MrRDJack Can you check you have setup your `.remote-sync.json`

**Comment by elistone** [comment]
There has been no response to this ticket as such it will now be closed.
If the issue still exists please reply and we will look into it.

**Comment by myslide** [comment]
I ran into these error, since I renamed my folder outside of Atom.  The solution:
Within the <userdir>\.atom\storage\application.json change the "initialPaths" accordingly.

**Comment by lucasbrynte** [comment]
I got this error when using remote-sync for the first time on a new project, by creating a .remote-sync.json file in the existing project. Closing & reopening the project does however resolve it.
