### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '~/.ssh/id_rsa.pub'

### ISSUE THREAD

**Issue by pestrov** [yongkangchen/remote-sync#293]
[Enter steps to reproduce below:]

1. Enter a non-existent folder in the 'Keyfile path'
2. Try Diff Folder

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.5
**Thrown From**: [remote-sync](https://github.com/yongkangchen/remote-sync) package, v4.1.2

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '~/.ssh/id_rsa.pub'

```
At fs.js:584

Error: ENOENT: no such file or directory, open '~/.ssh/id_rsa.pub'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:159:20)
    at Object.fs.readFileSync (fs.js:431:33)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:427:29)
    at ScpTransport.module.exports.ScpTransport._getConnection (/Users/nikitapestrov/.atom/packages/remote-sync/lib/transports/ScpTransport.coffee:154:23)
    at ScpTransport.module.exports.ScpTransport.fetchFileTree (/Users/nikitapestrov/.atom/packages/remote-sync/lib/transports/ScpTransport.coffee:113:6)
    at Object.module.exports.run (/Users/nikitapestrov/.atom/packages/remote-sync/lib/commands/DownloadAllCommand.coffee:12:15)
    at RemoteSync.downloadFolder (/Users/nikitapestrov/.atom/packages/remote-sync/lib/RemoteSync.coffee:85:17)
    at RemoteSync.diffFolder (/Users/nikitapestrov/.atom/packages/remote-sync/lib/RemoteSync.coffee:283:6)
    at handleEvent (/Users/nikitapestrov/.atom/packages/remote-sync/index.coffee:46:14)
    at atom-workspace.disposables.add.atom.commands.add.remote-sync:diff-folder (/Users/nikitapestrov/.atom/packages/remote-sync/index.coffee:101:40)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1106:28)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:340:25)
    at emitThree (events.js:97:13)
    at EventEmitter.emit (events.js:175:7)
```

### Commands

```
     -2:39.1.0 editor:newline (atom-text-editor.editor.is-focused)
  2x -2:38.6.0 core:save (atom-text-editor.editor.is-focused)
     -2:00.9.0 remote-sync:diff-folder (span.name.icon.icon-file-directory)
  2x -1:46.2.0 remote-sync:configure (div.header.list-item)
     -1:23.3.0 core:save (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -1:18.2.0 remote-sync:diff-folder (div.header.list-item)
     -1:03.5.0 remote-sync:configure (span.name.icon.icon-file-directory)
     -1:01.1.0 core:cut (atom-text-editor.editor.mini.is-focused)
     -1:00.6.0 core:move-right (atom-text-editor.editor.mini.is-focused)
     -1:00.2.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:58.7.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -0:51.2.0 remote-sync:diff-folder (div.header.list-item)
     -0:26.9.0 remote-sync:configure (div.header.list-item)
  5x -0:17.7.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:05.0 core:save (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -0:00.5.0 remote-sync:diff-folder (div.header.list-item)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
autocomplete-python, v1.7.2
linter, v1.11.4
linter-pep8, v1.3.0
react, v0.15.0
remote-sync, v4.1.2

# Dev
No dev packages
```

**Comment by kehd07** [comment]
It worked for me:
* Don't use ~ 
* Use absolute path

* Don't use ~/.ssh/id_rsa.pub
* Use ~/.ssh/id_rsa

**Comment by elistone** [comment]
There has been no response to this ticket as such it will now be closed.
If the issue still exists please reply and we will look into it.
