### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '/home/zalan/atom:'

### ISSUE THREAD

**Issue by Miztah87** [yongkangchen/remote-sync#307]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Linux Mint
**Thrown From**: [remote-sync](https://github.com/yongkangchen/remote-sync) package, v4.1.2

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/home/zalan/atom:'

```
At ATOM_SHELL_ASAR.js:0

Error: ENOENT: no such file or directory, lstat '/home/zalan/atom:'
    at Error (native)
    at fs.lstatSync (fs.js:887:18)
    at Object.fs.lstatSync (ATOM_SHELL_ASAR.js:229:16)
    at Object.realpathSync (fs.js:1532:21)
    at Object.fs.realpathSync (ATOM_SHELL_ASAR.js:304:29)
    at atom-workspace.configure (/home/zalan/.atom/packages/remote-sync/index.coffee:56:20)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/atom/resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/opt/atom/resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/opt/atom/resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/opt/atom/resources/app.asar/src/atom-environment.js:1106:28)
    at EventEmitter.outerCallback (/opt/atom/resources/app.asar/src/application-delegate.js:340:25)
    at emitThree (events.js:97:13)
    at EventEmitter.emit (events.js:175:7)
```

### Commands

```
     -0:01.0 remote-sync:configure (span.name.icon.icon-file-directory)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "remote-edit"
    ],
    "themes": [
      "one-light-ui",
      "one-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
emmet, v2.4.3
jshint, v1.8.5
remote-sync, v4.1.2

# Dev
No dev packages
```

**Comment by elistone** [comment]
Have you created your configure file?
