### ISSUE TITLE
Uncaught TypeError: this.queue.resume is not a function

### ISSUE THREAD

**Issue by fullpipe** [yongkangchen/remote-sync#321]
[Enter steps to reproduce below:]

1. update package to v4.1.3
2. ...

**Atom Version**: 1.10.2
**Electron Version**: 0.37.8
**System**: Mac OS X 10.11.6
**Thrown From**: [remote-sync](https://github.com/yongkangchen/remote-sync) package, v4.1.3

### Stack Trace

Uncaught TypeError: this.queue.resume is not a function

```
At /Users/fullpipe/.atom/packages/remote-sync/lib/UploadListener.coffee:26

TypeError: this.queue.resume is not a function
    at UploadListener.module.exports.UploadListener.handleAction (/Users/fullpipe/.atom/packages/remote-sync/lib/UploadListener.coffee:26:12)
    at UploadListener.module.exports.UploadListener.handleSave (/Users/fullpipe/.atom/packages/remote-sync/lib/UploadListener.coffee:8:6)
    at RemoteSync.uploadFile (/Users/fullpipe/.atom/packages/remote-sync/lib/RemoteSync.coffee:177:17)
    at handleEvent (/Users/fullpipe/.atom/packages/remote-sync/index.coffee:80:67)
    at atom-workspace.disposables.add.atom.commands.add.remote-sync:upload-file (/Users/fullpipe/.atom/packages/remote-sync/index.coffee:149:18)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:183:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
    at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -0:52 editor:toggle-line-comments (atom-text-editor.editor.is-focused)
     -0:42.4.0 editor:outdent-selected-rows (atom-text-editor.editor.is-focused)
     -0:41.1.0 core:backspace (atom-text-editor.editor.is-focused)
 15x -0:38.3.0 core:move-left (atom-text-editor.editor.is-focused)
  2x -0:32.4.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:31.9.0 editor:select-to-end-of-line (atom-text-editor.editor.is-focused)
     -0:31.5.0 core:copy (atom-text-editor.editor.is-focused)
     -0:31.2.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:30.1.0 core:paste (atom-text-editor.editor.is-focused)
  3x -0:29.5.0 core:move-left (atom-text-editor.editor.is-focused)
  8x -0:28.8.0 core:select-left (atom-text-editor.editor.is-focused)
  2x -0:26.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:04.5.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:02.2.0 editor:delete-to-beginning-of-line (atom-text-editor.editor.mini.is-focused)
     -0:00.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:00.1.0 remote-sync:upload-file (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "emmet-snippets-compatibility",
      "vim-mode",
      "package-js-generator",
      "atom-gpg"
    ],
    "excludeVcsIgnoredPaths": false,
    "packagesWithKeymapsDisabled": []
  },
  "remote-sync": {}
}
```

### Installed Packages

```coffee
# User
atom-autocomplete-php, v0.19.4 (active)
atom-beautify, v0.29.13 (active)
atom-typescript, v10.1.7 (active)
auto-detect-indentation, v1.2.0 (active)
autocomplete-clang, v0.10.0 (active)
autocomplete-go, v1.2.0 (active)
autocomplete-php, v0.3.7 (active)
builder-go, v1.0.1 (active)
coffee-compile, v0.22.0 (active)
cucumber, v0.5.0 (active)
docblockr, v0.8.5 (active)
emmet, v2.4.3 (active)
file-icons, v1.7.19 (active)
fonts, v1.6.0 (active)
git-plus, v5.17.1 (active)
git-time-machine, v1.5.3 (inactive)
go-config, v1.2.4 (active)
go-debug, v0.1.22 (active)
go-get, v2.0.0 (active)
go-plus, v4.2.0 (active)
godoc, v1.0.0 (active)
gofmt, v1.2.0 (active)
gometalinter-linter, v1.2.1 (active)
gorename, v1.1.0 (active)
highlight-selected, v0.11.2 (active)
language-crontab, v0.2.1 (active)
language-docker, v1.1.7 (active)
language-ini, v1.16.0 (active)
language-nginx, v0.6.2 (active)
linter, v1.11.16 (active)
linter-docker, v0.1.2 (active)
linter-php, v1.2.0 (active)
lipsum, v0.1.0 (inactive)
merge-conflicts, v1.4.4 (active)
minimap, v4.25.0 (active)
minimap-bookmarks, v0.4.2 (active)
minimap-git-diff, v4.3.1 (active)
minimap-highlight-selected, v4.4.0 (active)
minimap-selection, v4.4.0 (active)
navigator-godef, v1.1.0 (active)
nucleus-dark-ui, v0.10.4 (inactive)
php-cs-fixer, v2.5.9 (active)
php-test, v0.0.0 (inactive)
php-twig, v4.0.0 (active)
remote-sync, v4.1.3 (active)
tester-go, v1.1.0 (active)
typograph, v0.2.0 (active)
vim-mode, v0.65.1 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.5.0 (active)
one-light-ui, v1.5.0 (inactive)
one-dark-syntax, v1.3.0 (active)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.3 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (active)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
find-and-replace, v0.201.0 (active)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.2 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.65.0 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.100.2 (active)
timecop, v0.33.2 (active)
tree-view, v0.208.2 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by Yopai** [comment]
Hi, was this error corrected ? I got the same error with the last version of remote-sync (4.1.5)

**Comment by fullpipe** [comment]
Hi, as I remember, I simply reinstall package and it helped
