### ISSUE TITLE
Cannot find module 'randomatic'

### ISSUE THREAD

**Issue by pjehan** [yongkangchen/remote-sync#323]
Steps to reproduce below:

1. Open the app

**Atom Version**: 1.7.4
**System**: Ubuntu 16.04.1
**Thrown From**: [remote-sync](https://github.com/yongkangchen/remote-sync) package, v4.1.3

### Stack Trace

Failed to activate the remote-sync package

```
At Cannot find module 'randomatic'

Error: Cannot find module 'randomatic'
    at Module._resolveFilename (module.js:338:15)
    at Function.Module._resolveFilename (/usr/share/atom/resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/pierre/.atom/packages/remote-sync/lib/RemoteSync.coffee:4:13)
    at Object.<anonymous> (/home/pierre/.atom/packages/remote-sync/lib/RemoteSync.coffee:1:1)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at initProject (/home/pierre/.atom/packages/remote-sync/index.coffee:37:19)
    at Object.module.exports.activate (/home/pierre/.atom/packages/remote-sync/index.coffee:93:5)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:183:20)
    at /usr/share/atom/resources/app.asar/src/package.js:156:32
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:92:15)
    at /usr/share/atom/resources/app.asar/src/package.js:149:26
    at Package.module.exports.Package.activate (/usr/share/atom/resources/app.asar/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:538:21)
    at /usr/share/atom/resources/app.asar/src/package-manager.js:519:29
    at Config.module.exports.Config.transactAsync (/usr/share/atom/resources/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/usr/share/atom/resources/app.asar/src/package-manager.js:514:19)
    at PackageManager.module.exports.PackageManager.activate (/usr/share/atom/resources/app.asar/src/package-manager.js:497:46)
    at /usr/share/atom/resources/app.asar/src/atom-environment.js:754:28
```

### Commands

```
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
auto-indent, v0.5.0
autocomplete-php, v0.3.7
color-picker, v2.2.2
docblockr, v0.8.5
emmet, v2.4.3
file-icons, v1.7.19
linter, v1.11.16
linter-php, v1.2.0
merge-conflicts, v1.4.4
minimap, v4.25.0
php-cs-fixer, v2.5.9
pigments, v0.35.1
remote-sync, v4.1.3
terminal-plus, v0.14.5

# Dev
No dev packages
```

**Comment by pjehan** [comment]
Downloading the package manually and adding the 'randomatic' package with following command fixed the issue:
`npm install --save randomatic`

**Comment by elistone** [comment]
Added the missing dependency

**Comment by TheoAbiel** [comment]
Thanks @pjehan ! Your solution did the trick for me! Glad to hear that you have added the missing dependency @elistone !
