### ISSUE TITLE
q.drain is not a function

### ISSUE THREAD

**Issue by willgdjones** [yongkangchen/remote-sync#391]
Have a new error as of this morning.

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.2
**Thrown From**: [remote-sync](https://github.com/yongkangchen/remote-sync) package 4.1.5

### Stack Trace

Uncaught TypeError: q.drain is not a function

```
At /Users/fonz/.atom/packages/remote-sync/node_modules/fs-plus/node_modules/async/lib/async.js:909

TypeError: q.drain is not a function
    at /packages/remote-sync/node_modules/fs-plus/node_modules/async/lib/async.js:909:23
    at /packages/remote-sync/node_modules/fs-plus/node_modules/async/lib/async.js:44:16
    at /packages/remote-sync/node_modules/fs-plus/lib/fs-plus.js:438:24
    at FSReqWrap.oncomplete (fs.js:123:15)
```

### Commands

```
     -2:38.4.0 remote-sync:upload-folder (div.header.list-item.project-root-header)
     -2:27.1.0 core:cancel (a.stack-toggle)
     -2:18 remote-sync:diff-folder (div.header.list-item.project-root-header)
  5x -2:15.2.0 core:save (input.hidden-input)
  2x -2:05.2.0 editor:newline (input.hidden-input)
     -2:04.7.0 core:save (input.hidden-input)
     -2:00.8.0 core:backspace (input.hidden-input)
     -1:56.8.0 editor:newline (input.hidden-input)
  6x -1:56.5.0 core:save (input.hidden-input)
     -1:29.1.0 editor:newline (input.hidden-input)
  2x -1:28.9.0 core:save (input.hidden-input)
     -1:23.5.0 remote-sync:configure (div.header.list-item.project-root-header)
  2x -1:14.7.0 core:save (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -1:00.4.0 remote-sync:download-folder (div.header.list-item.project-root-header)
     -0:24.8.0 core:save (ol.tree-view.list-tree.has-collapsable-children.focusable-panel.full-menu)
     -0:19.4.0 remote-sync:upload-folder (div.header.list-item.project-root-header)
```

### Non-Core Packages

```
linter-python-pep8 0.2.0 
remote-atom 1.3.10 
remote-sync 4.1.5 
tabs-to-spaces 1.0.3 
```

**Comment by dschwen** [comment]
Duplicate of #374
