### ISSUE TITLE
Uncaught Error: [remote-sync] invalid transport: undefined in ~/project/.remote-sync.json

### ISSUE THREAD

**Issue by ryan-ajmadison** [yongkangchen/remote-sync#415]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.2 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: [remote-sync](https://github.com/yongkangchen/remote-sync) package 4.1.5

### Stack Trace

Uncaught Error: [remote-sync] invalid transport: undefined in /Users/ryan.wilson/project/.remote-sync.json

```
At /Users/ryan.wilson/.atom/packages/remote-sync/lib/RemoteSync.coffee:256

Error: [remote-sync] invalid transport: undefined in /Users/ryan.wilson/project/.remote-sync.json
    at RemoteSync.createTransport (/packages/remote-sync/lib/RemoteSync.coffee:256:17)
    at RemoteSync.getTransport (/packages/remote-sync/lib/RemoteSync.coffee:262:19)
    at RemoteSync.uploadFile (/packages/remote-sync/lib/RemoteSync.coffee:108:37)
    at /packages/remote-sync/lib/RemoteSync.coffee:146:17)
    at emitOne (events.js:96:13)
    at FSWatcher.emit (events.js:188:7)
    at /packages/remote-sync/node_modules/chokidar/index.js:191:15)
    at FSWatcher._emit (/packages/remote-sync/node_modules/chokidar/index.js:233:5)
    at /packages/remote-sync/node_modules/chokidar/lib/fsevents-handler.js:204:14)
    at addOrChange (/packages/remote-sync/node_modules/chokidar/lib/fsevents-handler.js:210:7)
    at /packages/remote-sync/node_modules/chokidar/lib/fsevents-handler.js:236:16)
    at filteredListener (/packages/remote-sync/node_modules/chokidar/lib/fsevents-handler.js:58:7)
    at /packages/remote-sync/node_modules/chokidar/lib/fsevents-handler.js:83:11
    at Array.forEach (native)
    at /packages/remote-sync/node_modules/chokidar/lib/fsevents-handler.js:82:34)
    at emitThree (events.js:116:13)
    at FSEvents.emit (events.js:194:7)
    at /packages/remote-sync/node_modules/fsevents/fsevents.js:47:11)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
```

### Commands

```
     -8:43.2.0 core:cut (input.hidden-input)
     -8:41.5.0 core:paste (input.hidden-input)
     -8:29.6.0 core:confirm (input.hidden-input)
     -7:21.4.0 tree-view:remove-project-folder (span.name.icon.icon-file-directory)
     -7:01.1.0 tree-view:add-file (span.name.icon.icon-repo)
  4x -6:54.3.0 core:confirm (input.hidden-input)
     -6:43 tree-view:remove-project-folder (span.name.icon.icon-repo)
     -6:35.1.0 application:add-project-folder (atom-workspace.workspace.scrollbars-visible-always.theme-monokai.theme-one-dark-ui)
     -3:24.6.0 core:save (input.hidden-input)
  2x -3:16 tree-view:add-file (span.name.icon.icon-file-directory)
  2x -3:02.8.0 core:confirm (input.hidden-input)
     -2:48.5.0 core:paste (input.hidden-input)
  2x -2:46.9.0 core:save (input.hidden-input)
     -0:26.2.0 core:undo (input.hidden-input)
     -0:22.7.0 core:redo (input.hidden-input)
     -0:21.8.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-typescript 11.0.3 
language-haml 0.24.5 
monokai 0.24.0 
monokai-blackboard 0.3.0 
remote-sync 4.1.5 
```

**Comment by ryan-ajmadison** [comment]
I also can't see the .remote-sync.json file in the treeview anymore, it just disappeared. I tried removing from terminal and creating a new file, but still can't see it.
