### ISSUE TITLE
Failed to load the remote-sync package

### ISSUE THREAD

**Issue by MCStreetguy** [yongkangchen/remote-sync#453]
**Whenever I start Atom, it shows up a FatalError Notification with the following message:**
> Failed to load the remote-sync package
> Unexpected token } in JSON at position 11178 in /Users/maximilianschmidt/.atom/packages/remote-sync/package.json

### Stack Trace:
> SyntaxError: Unexpected token } in JSON at position 11178
    at JSON.parse (<anonymous>)
    at parseObject (/Applications/Atom.app/Contents/Resources/app/node_modules/season/lib/cson.js:58:25)
    at parseContentsSync (/Applications/Atom.app/Contents/Resources/app/node_modules/season/lib/cson.js:72:22)
    at Object.readFileSync (/Applications/Atom.app/Contents/Resources/app/node_modules/season/lib/cson.js:184:20)
    at PackageManager.loadPackageMetadata (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:843:33)
    at PackageManager.loadAvailablePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:586:29)
    at config.transact (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:530:20)
    at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app/src/config.js:342:22)
    at PackageManager.loadPackages (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:528:23)
    at /Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:821:34
  at /Users/maximilianschmidt/.atom/packages/remote-sync/package.json:1:1

### Steps to reproduce:
1. Start Atom

### Installed Packages:
> Community Packages (18) /Users/maximilianschmidt/.atom/packages
├── atom-typescript@11.0.10
├── auto-indent@0.5.0
├── auto-softwrap@1.0.1 (disabled)
├── autoclose-html@0.23.0
├── autoupdate-packages@1.3.1
├── busy-signal@1.4.3
├── editorconfig@2.2.2
├── emmet@2.4.3
├── file-icons@2.1.13
├── intentions@1.1.5
├── language-typoscript2@1.4.0
├── linter@2.2.0
├── linter-ui-default@1.6.10
├── minimap@4.29.7
├── project-manager@3.3.5
├── remote-sync
├── snippet-injector@1.5.3
└── sort-lines@0.18.0

**Comment by daverickdunn** [comment]
That's kinda strange, have you been changing anything manually in the .atom folder? That file gets updated automatically by apm, and other than that it hasn't been changed in over a year, so I suspect this is in fact an apm/npm issue.

You should try uninstalling and reinstalling remote-sync. I imagine that will resolve it. If it still happens after that, then please attach the file: `/Users/maximilianschmidt/.atom/packages/remote-sync/package.json`.

Cheers.

**Comment by MCStreetguy** [comment]
I did not manipulate any files manually. I'm developing packages myself, therefore I know about the sensitivity of such files.
I'll try the reinstall tomorrow and inform you if i encounter further problems.
