### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, stat '/Volumes/HDD/_Sites/fdgl.fr/wp-content/t...

### ISSUE THREAD

**Issue by DSGND** [yongkangchen/remote-sync#457]
[Enter steps to reproduce:]

1. Try to watch a folder and all its files and subfolders

**Atom**: 1.22.0 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.13.1
**Thrown From**: [remote-sync](https://github.com/yongkangchen/remote-sync) package 4.1.8

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, stat '/Volumes/HDD/_Sites/fdgl.fr/wp-content/themes/flatsome/*.*'

```
At fs.js:912

Error: ENOENT: no such file or directory, stat '/Volumes/HDD/_Sites/fdgl.fr/wp-content/themes/flatsome/*.*'
    at fs.statSync (fs.js:912:18)
    at Object.fs.statSync (ELECTRON_ASAR.js:280:16)
    at RemoteSync.isDirectory (/packages/remote-sync/lib/RemoteSync.coffee:201:23)
    at RemoteSync.monitorFile (/packages/remote-sync/lib/RemoteSync.coffee:135:42)
    at /packages/remote-sync/lib/RemoteSync.coffee:226:13
```

### Commands

```
     -9:46.7.0 core:copy (input.hidden-input)
     -9:43.6.0 core:paste (input.hidden-input)
     -9:42.3.0 editor:newline (input.hidden-input)
     -9:41.9.0 core:save (input.hidden-input)
     -1:35.3.0 remote-sync:configure (span.name.icon.icon-file-directory)
     -1:23.8.0 core:backspace (input.hidden-input)
     -0:27.7.0 remote-sync:configure (span.name.icon.icon-file-directory)
```

### Non-Core Packages

```
atom-browsersync 0.2.0 
atom-css-comb 3.3.1 
atom-material-ui 2.0.6 
atom-zurb-foundation 2.1.0 
busy-signal 1.4.3 
emmet 2.4.3 
git-plus 7.10.0 
highlight-line 0.12.0 
highlight-selected 0.13.1 
intentions 1.1.5 
linter 2.2.0 
linter-csslint 2.0.0 
linter-phpmd 2.0.0 
linter-sass-lint 1.8.3 
linter-ui-default 1.6.10 
minimap 4.29.7 
minimap-highlight-selected 4.6.1 
newbound-dark-syntax 1.1.0 
pigments 0.40.2 
pretty-json 1.6.4 
remote-sync 4.1.8 
sass-autocompile 0.13.3 
string-encoder 0.1.0 
wordpress-dictionary 4.4.0 
```

**Comment by daverickdunn** [comment]
Hi, thanks for the info. This is an ongoing issue that I hoped was recently resolved, I haven't been able to reproduce it, so it's been hard to figure out. Can you please provide a little more information about the folder structure you're using?

Specifically, could you post your **.remote-sync.json** and could you please check there are no symbolic links contained in that path? 

```
ls -la /Volumes
ls -la /Volumes/HDD
ls -la /Volumes/HDD/_Sites
# etc...
```
Thanks!

**Comment by berteh** [comment]
I had similar issue when my project directory had symlinks to volumes with restrictive user access rights.
solved by moving target directory in home folder (no rights issue). but i guess a good configuration of volumes mount options should solve it too.
