### ISSUE TITLE
Uncaught ReferenceError: error is not defined

### ISSUE THREAD

**Issue by prassanna-ravishankar** [yongkangchen/remote-sync#458]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.22.0 x64
**Electron**: 1.6.15
**OS**: elementary OS
**Thrown From**: [remote-sync](https://github.com/yongkangchen/remote-sync) package 4.1.8

### Stack Trace

Uncaught ReferenceError: error is not defined

```
At /home/prassanna/.atom/packages/remote-sync/lib/model/host.coffee:17

ReferenceError: error is not defined
    at /packages/remote-sync/lib/model/host.coffee:17:7)
    at Object.configure (/packages/remote-sync/lib/RemoteSync.coffee:320:16)
    at HTMLElement.configure (/packages/remote-sync/index.coffee:58:14)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:381:36)
    at CommandRegistry.dispatch (/usr/share/atom/resources/app/src/command-registry.js:266:23)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/usr/share/atom/resources/app/src/atom-environment.js:1388:34)
    at EventEmitter.outerCallback (/usr/share/atom/resources/app/src/application-delegate.js:348:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
  2x -3:15.1.0 core:confirm (input.hidden-input)
  4x -2:20.7.0 core:backspace (input.hidden-input)
     -2:18.4.0 core:confirm (input.hidden-input)
  2x -2:17.3.0 core:backspace (input.hidden-input)
     -2:16 core:confirm (input.hidden-input)
     -1:32.9.0 application:add-project-folder (div.header.list-item.project-root-header)
     -1:22.4.0 remote-sync:upload-folder (span.name.icon.icon-file-directory)
     -0:51.9.0 tree-view:add-file (span.name.icon.icon-file-directory)
  4x -0:50 core:backspace (input.hidden-input)
     -0:37.8.0 core:confirm (input.hidden-input)
     -0:20.4.0 remote-sync:configure (span.name.icon.icon-file-directory)
```

### Non-Core Packages

```
Hydrogen 2.0.1 
remote-sync 4.1.8 
```

**Comment by daverickdunn** [comment]
Any more info on this?
