### ISSUE TITLE
Uncaught Error: Unexpected packet before version

### ISSUE THREAD

**Issue by holyhope** [yongkangchen/remote-sync#460]
[Enter steps to reproduce:]

1. Configure remote-sync with the a user not available (www-data for example)
2. Try to upload
3. An error occurs

**Atom**: 1.22.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.13.1
**Thrown From**: [remote-sync](https://github.com/yongkangchen/remote-sync) package 4.1.8

### Stack Trace

Uncaught Error: Unexpected packet before version

```
At events.js:160

Error: Unexpected packet before version
    at SFTPStream._transform (/packages/remote-sync/node_modules/ssh2-streams/lib/sftp.js:304:27)
    at SFTPStream.Transform._read (_stream_transform.js:167:10)
    at SFTPStream._read (/packages/remote-sync/node_modules/ssh2-streams/lib/sftp.js:181:15)
    at SFTPStream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:332:12)
    at writeOrBuffer (_stream_writable.js:318:5)
    at SFTPStream.Writable.write (_stream_writable.js:245:11)
    at Channel.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at Channel.emit (events.js:188:7)
    at Channel.Readable.read (_stream_readable.js:381:10)
    at flow (_stream_readable.js:761:34)
    at resume_ (_stream_readable.js:743:3)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
     -0:48.8.0 remote-sync:upload-folder (span.name.icon.icon-file-directory)
```

### Non-Core Packages

```
docker 0.8.0 
remote-sync 4.1.8 
wordpress-api 1.2.2 
wordpress-suite 1.2.0 
```

**Comment by daverickdunn** [comment]
Has this happened more than once?

**Comment by eTorAken** [comment]
Hi,

It started happening to me today:
- Atom: 1.23.3 x64
- OS: Windows 10
- remote-sync : v4.1.8

And happens 100% of the time.

**Comment by avindra** [comment]
Whoever is having this issue, log in to your box via regular ssh first.

If you're seeing random text coming into your terminal, that is most likely your problem.

Figure out what's causing it and stop it (checking for rogue `echo` statements in the `.bash*` files is a good start)
