### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, stat '~/github/vertica-installer/scriptsretent...

### ISSUE THREAD

**Issue by lzomlot** [yongkangchen/remote-sync#464]
[Enter steps to reproduce:]

1. Add file to "watch Automatically" while configuring the remote settings
2. As work around: I have to put forward slash in front of the file name to work: "/file_name" as opposed to "file_name".

**Atom**: 1.23.0 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.13.2
**Thrown From**: [remote-sync](https://github.com/yongkangchen/remote-sync) package 4.1.8

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, stat '/Users/user/github/vertica-installer/scriptsretention_policy_util.sh'

```
At fs.js:912

Error: ENOENT: no such file or directory, stat '/Users/user/github/vertica-installer/scriptsretention_policy_util.sh'
    at fs.statSync (fs.js:912:18)
    at Object.fs.statSync (ELECTRON_ASAR.js:280:16)
    at RemoteSync.isDirectory (/packages/remote-sync/lib/RemoteSync.coffee:201:23)
    at RemoteSync.monitorFile (/packages/remote-sync/lib/RemoteSync.coffee:135:42)
    at /packages/remote-sync/lib/RemoteSync.coffee:226:13
```

### Commands

```
     -3:32.7.0 core:move-up (input.hidden-input)
  3x -3:32.3.0 core:move-down (input.hidden-input)
     -3:17.8.0 core:save (input.hidden-input)
     -3:09.0 core:undo (input.hidden-input)
     -2:38.4.0 key-binding-resolver:toggle (input.hidden-input)
     -2:37.4.0 editor:consolidate-selections (input.hidden-input)
     -2:37.4.0 core:cancel (input.hidden-input)
     -2:36.6.0 settings-view:open (input.hidden-input)
  2x -1:52.6.0 remote-sync:configure (span.name.icon.icon-file-directory)
     -1:29.3.0 core:backspace (input.hidden-input)
     -0:40.5.0 remote-sync:configure (div.header.list-item)
 11x -0:23.2.0 core:backspace (input.hidden-input)
     -0:21.2.0 core:paste (input.hidden-input)
     -0:20.3.0 core:undo (input.hidden-input)
     -0:19.3.0 core:paste (input.hidden-input)
     -0:18 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
Atom-Bash-Snippets 0.0.3 
atom-clock 0.1.15 
autocomplete-bash-builtins 0.3.5 
autocomplete-java 1.2.7 
autocomplete-java-minus 0.14.0 
autocomplete-python 1.10.5 
busy 0.7.0 
busy-signal 1.4.3 
comment-headers 2.15.0 
file-header 1.13.8 
goto 1.8.3 
goto-definition 1.3.4 
intentions 1.1.5 
java-classpath-registry 0.4.0 
java-import-wiz 0.5.0 
java-importer 1.4.1 
java-plus 0.1.0 
language-docker 1.1.8 
language-gradle 0.0.5 
language-latex 1.1.1 
language-markdown 0.25.1 
latex 0.49.0 
linter 2.2.0 
linter-flake8 2.3.0 
linter-javac 1.9.4 
linter-python 3.1.2 
linter-shellcheck 1.4.6 
linter-ui-default 1.6.10 
merge-conflicts 1.4.5 
on-save 2.0.2 
process-palette 0.16.0 
python-tools 0.6.9 
remote-edit 1.9.0 
remote-sync 4.1.8 
run-command 0.5.0 
Sublime-Style-Column-Selection 1.7.4 
terminal-plus 0.14.5 
todo-show 2.1.0 
tomatimer 1.2.3 
```

**Comment by sijpkes** [comment]
This is a duplicate of #457
