### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, stat '/Volumes/PEGASUS/MAIN_DOCUMENTS/workspac...

### ISSUE THREAD

**Issue by sijpkes** [yongkangchen/remote-sync#469]
[Enter steps to reproduce:]

1. Right-click project -> select Remote Sync -> Configure
2. Put a nonexistent watch file in Watch Automatically and click **Save**

**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.13.2
**Thrown From**: [remote-sync](https://github.com/yongkangchen/remote-sync) package 4.1.8

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, stat '/Volumes/PEGASUS/MAIN_DOCUMENTS/workspace/bb_apegremote/*'

```
At fs.js:912

Error: ENOENT: no such file or directory, stat '/Volumes/PEGASUS/MAIN_DOCUMENTS/workspace/bb_apegremote/*'
    at fs.statSync (fs.js:912:18)
    at Object.fs.statSync (ELECTRON_ASAR.js:280:16)
    at RemoteSync.isDirectory (/packages/remote-sync/lib/RemoteSync.coffee:201:23)
    at RemoteSync.monitorFile (/packages/remote-sync/lib/RemoteSync.coffee:135:42)
    at /packages/remote-sync/lib/RemoteSync.coffee:226:13
```

### Commands

```
     -3:58.9.0 application:add-project-folder (input.hidden-input)
     -3:19 tree-view:add-folder (span.name.icon.icon-file-directory)
     -3:17 core:confirm (input.hidden-input)
     -2:57.7.0 remote-sync:configure (span.name.icon.icon-file-directory)
 14x -2:50.9.0 core:backspace (input.hidden-input)
     -0:33.6.0 remote-sync:configure (span.name.icon.icon-file-directory)
```

### Non-Core Packages

```
git-plus 7.10.0 
language-apache 1.8.0 
remote-atom 1.3.11 
remote-sync 4.1.8 
```

**Comment by sijpkes** [comment]
Sorry duplicate of Issue #464
