### ISSUE TITLE
Atom 1.41.1 incompatible

### ISSUE THREAD

**Issue by HernanLencinas** [yongkangchen/remote-sync#508]
After update to Atom 1.41.1 reported 1 bug on remote-sync package.
Tried to uninstall and reinstall but keep installing for ever without success.

**Comment by dennisboris** [comment]
> After update to Atom 1.41.1 reported 1 bug on remote-sync package.
> Tried to uninstall and reinstall but keep installing for ever without success.

I'm having the same issue on Atom 1.41.1.

**Comment by fabio-craq** [comment]
Same problem here! Atom 1.41.0 on mac os catalina

**Comment by dennisboris** [comment]
After some investigation i found the problem. It appears only to be happening when running MacOS Catalina. 

**The fix is simple:**
1. Open your terminal application.
2. Install Xcode using: `xcode-select --install`
3. In Atom click and rebuild the package.
4. Restart Atom.

**Comment by thenatsky** [comment]
> Same problem here! Atom 1.41.0 on mac os catalina

me too.  It complains that Xcode is not available (which it isn't - but command line tools is installed!).
`gyp: No Xcode or CLT version detected!
gyp ERR! configure error 
gyp gypERR!  ERR! configure errorstack 
 Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp gypERR!  ERR!stack  Error: `gyp` failed with exit code: 1
Systemgyp Darwin 19.0.0
 ERR! stack     at ChildProcess.onCpExit (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stackgyp     at ChildProcess.emit (events.js:182:13)
gyp  ERR!ERR!  stackcommand     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
 "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Users/$user/.atom/packages/remote-sync/node_modules/fsevents/lib/binding/Release/electron-v4.2-darwin-x64/fse.node" "--module_name=fse" "--module_path=/Users/$user/.atom/packages/remote-sync/node_modules/fsevents/lib/binding/Release/electron-v4.2-darwin-x64" "--python=/Applications/Atom.app/Contents/Resources/app/apm/bin/python-interceptor.sh"
gyp ERR! cwd /Users/$user/.atom/packages/remote-sync/node_modules/fsevents
gyp ERR! node -v v10.2.1
gyp ERR! node-gyp -vgyp v3.7.0
 gypERR!  ERR!System  Darwin 19.0.0
not ok 
gyp ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Users/$user/.atom/packages/remote-sync/node_modules/fsevents/lib/binding/Release/electron-v4.2-darwin-x64/fse.node" "--module_name=fse" "--module_path=/Users/$user/.atom/packages/remote-sync/node_modules/fsevents/lib/binding/Release/electron-v4.2-darwin-x64" "--python=/Applications/Atom.app/Contents/Resources/app/apm/bin/python-interceptor.sh"
gyp ERR! cwd /Users/$user/.atom/packages/remote-sync/node_modules/fsevents
gyp ERR! node -v v10.2.1
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/Applications/Atom.app/Contents/Resources/app/apm/bin/node /Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/$user/.atom/packages/remote-sync/node_modules/fsevents/lib/binding/Release/electron-v4.2-darwin-x64/fse.node --module_name=fse --module_path=/Users/$user/.atom/packages/remote-sync/node_modules/fsevents/lib/binding/Release/electron-v4.2-darwin-x64 --python=/Applications/Atom.app/Contents/Resources/app/apm/bin/python-interceptor.sh' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/$user/.atom/packages/remote-sync/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:961:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
node-pre-gyp ERR! System Darwin 19.0.0
node-pre-gyp ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Users/$user/.atom/packages/remote-sync/node_modules/fsevents/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/$user/.atom/packages/remote-sync/node_modules/fsevents
node-pre-gyp ERR! node -v v10.2.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.36
node-pre-gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fsevents@1.1.2 install: `node install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the fsevents@1.1.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/$user/.atom/.apm/_logs/2019-11-04T00_05_38_964Z-debug.log
`

**Comment by HernanLencinas** [comment]
Works for me.
Thank you.

**Comment by pistoletpierre** [comment]
For anyone else who was still having problems after trying https://github.com/yongkangchen/remote-sync/issues/508#issuecomment-548750935: check your SSH private key that you're using. Mine was wrapped between "-----BEGIN OPENSSH PRIVATE KEY-----" and "-----END OPENSSH PRIVATE KEY-----". The ssh2-streams node lib doesn't currently support that right now. 
<img width="974" alt="image" src="https://user-images.githubusercontent.com/6157706/68179609-8c750a00-ff5e-11e9-8efa-837b94fe6cef.png">

It's a known issue: https://github.com/mscdex/ssh2-streams/issues/100

Edit: trying it with another key whose header is -----BEGIN RSA PRIVATE KEY-----, it works no problem.
