### ISSUE TITLE
Uncaught TypeError: The "path" argument must be of type string. Received type undefined

### ISSUE THREAD

**Issue by Mabelliaw** [yongkangchen/remote-sync#517]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.49.0 x64
**Electron**: 5.0.13
**OS**: Mac OS X 10.11.6
**Thrown From**: [remote-sync](https://github.com/yongkangchen/remote-sync) package 4.1.8

### Stack Trace

Uncaught TypeError: The "path" argument must be of type string. Received type undefined

```
At internal/validators.js:105

TypeError [ERR_INVALID_ARG_TYPE] [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:105:11)
    at Object.join (path.js:1037:7)
    at FtpTransport.module.exports.FtpTransport.fetchFileTree (/packages/remote-sync/lib/transports/FtpTransport.coffee:91:23)
    at Object.run (/packages/remote-sync/lib/commands/DownloadAllCommand.coffee:12:15)
    at RemoteSync.downloadFolder (/packages/remote-sync/lib/RemoteSync.coffee:86:17)
    at handleEvent (/packages/remote-sync/index.coffee:46:14)
    at /packages/remote-sync/index.coffee:108:44)
    at CommandRegistry.handleCommandEvent (/Users/Owner/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:11:349781)
    at CommandRegistry.dispatch (/Users/Owner/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:11:348256)
    at AtomEnvironment.dispatchContextMenuCommand (/Users/Owner/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:1:726039)
    at EventEmitter.t (/Users/Owner/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:1:734045)
    at EventEmitter.emit (events.js:194:13)
```

### Commands

```
  2x -9:45.7.0 core:paste (input.hidden-input)
     -9:12.5.0 core:backspace (input.hidden-input)
     -8:45.8.0 core:paste (input.hidden-input)
     -5:15.5.0 remote-sync:download-folder (div.header.list-item.project-root-header)
     -5:06.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
     -0:13.1.0 remote-sync:download-folder (span.name.icon.icon-file-directory)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-live-server 2.3.0 
atom-ternjs 0.20.0 
autoclose-html 0.23.0 
csslint 1.2.0 
emmet 2.4.3 
language-ejs 0.4.0 
pigments 0.40.2 
remote-sync 4.1.8 
```

**Comment by Mabelliaw** [comment]
i have issue in regards to download my file.

**Comment by Xitee1** [comment]
I had the same problem with the remote sync plugin. Then I noticed that I haven't set a path in the configuration.
Everything works for me now. I hope i could help someone
