### ISSUE TITLE
Uncaught TypeError: Converting circular structure to JSON    --> starting at object with constru...

### ISSUE THREAD

**Issue by balakrishna211221** [yongkangchen/remote-sync#520]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.52.0 x64
**Electron**: 6.1.12
**OS**: Microsoft Windows 10 Home Single Language
**Thrown From**: [remote-sync](https://github.com/yongkangchen/remote-sync) package 4.1.8

### Stack Trace

Uncaught TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'MessagePanelView'
    |     property '0' -> object with constructor 'HTMLDivElement'
    --- property 'spacePenView' closes the circle

```
At C:\Users\BALU\.atom\packages\remote-sync\lib\model\host.coffee:41

TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'MessagePanelView'
    |     property '0' -> object with constructor 'HTMLDivElement'
    --- property 'spacePenView' closes the circle
    at JSON.stringify (<anonymous>)
    at Host.module.exports.Host.saveJSON (/packages/remote-sync/lib/model/host.coffee:41:35)
    at ConfigView.module.exports.ConfigView.confirm (/packages/remote-sync/lib/view/host-view.coffee:137:11)
    at /packages/ftp-remote-edit-plus/node_modules/space-pen/lib/space-pen.js:220:36)
    at HTMLButtonElement.dispatch (/packages/ftp-remote-edit-plus/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLButtonElement.elemData.handle (/packages/ftp-remote-edit-plus/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -8:27.8.0 remote-ftp:sync-with-local (span.name.icon.icon-file-directory)
     -8:27.8.0 remote-ftp:connect (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -8:18.9.0 remote-sync:upload-folder (span.name.icon.icon-file-directory)
     -8:10.4.0 core:move-right (input.hidden-input)
     -8:10 core:backspace (input.hidden-input)
  3x -7:48 remote-sync:upload-folder (span.name.icon.icon-file-directory)
  3x -6:20.2.0 remote-sync:configure (div.header.list-item.project-root-header)
     -4:42.4.0 remote-sync:upload-git-change (span.name.icon.icon-file-directory)
     -4:31.8.0 remote-sync:configure (div.header.list-item.project-root-header)
     -4:18.7.0 tree-view:remove (div.tool-panel.tree-view)
     -4:11.1.0 remote-sync:configure (span.name.icon.icon-file-directory)
  2x -3:38.2.0 core:backspace (input.hidden-input)
  2x -3:35.4.0 core:move-down (input.hidden-input)
     -1:59.1.0 core:confirm (input.hidden-input)
     -1:10.2.0 remote-sync:configure (span.name.icon.icon-file-directory)
     -0:31.2.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
ftp-remote-edit-plus 1.2.0 
remote-ftp 2.2.4 
Remote-SSH 0.11.0 
remote-sync 4.1.8 
```

**Comment by AyalaResearch** [comment]
don't know what this is, the auto-bug reporter took me here. I will try a couple things and see how i can work around it. i will report back if i figure something out.

**Comment by trimrd** [comment]
Same problem, any news?

**Comment by jayib** [comment]
I'm having the same problem.  I have set up remote sync on two other projects with no difficulty.  Now it fails on every new project.  Seems completely random.  Any progress at all?

**Comment by jayib** [comment]
I was having this same problem.  Windows 10.  First two projects were configured for remote sync with no difficulty.  Then any new project caused this error.  I restarted the application and it worked again.  Strange.

**Comment by ashah976** [comment]
same problem, Windows 11
First one added to workspace was okay 
Uncaught TypeError: Converting circular structure to JSON --> starting at object with constructor 'MessagePanelView' | property '0' -> object with constructor 'HTMLDivElement' --- property 'spacePenView' closes the circle
