### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, stat '~/SRC/somedir/someproject/*.*'

### ISSUE THREAD

**Issue by mklarsen** [yongkangchen/remote-sync#528]
[Enter steps to reproduce:]

1. Trying to setup-watch-folder
2. "whats everything trying with "*" as parameter, single file like index.html works fine

**Atom**: 1.57.0 x64
**Electron**: 9.4.4
**OS**: macOS 11.4
**Thrown From**: [remote-sync](https://github.com/yongkangchen/remote-sync) package 4.1.8

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, stat '/Users/martin.k.larsen/SRC/somedir/someproject/*.*'

```
At internal/fs/utils.js:220

Error: ENOENT: no such file or directory, stat '/Users/martin.k.larsen/SRC/somedir/someproject/*.*'
    at statSync (fs.js:915:3)
    at Object.fs.statSync (electron/js2c/asar.js:278:27)
    at RemoteSync.isDirectory (/packages/remote-sync/lib/RemoteSync.coffee:201:23)
    at RemoteSync.monitorFile (/packages/remote-sync/lib/RemoteSync.coffee:135:42)
    at /packages/remote-sync/lib/RemoteSync.coffee:226:13
```

### Commands

```
     -1:26.5.0 core:save (input.hidden-input)
     -1:24.7.0 core:backspace (input.hidden-input)
     -1:24.3.0 core:save (input.hidden-input)
  2x -1:19.3.0 remote-sync:upload-folder (span.name.icon.icon-file-directory)
  2x -0:39.2.0 core:save (input.hidden-input)
     -0:37.9.0 core:backspace (input.hidden-input)
     -0:37.5.0 editor:consolidate-selections (input.hidden-input)
     -0:37.5.0 core:cancel (input.hidden-input)
     -0:37 core:save (input.hidden-input)
     -0:13.8.0 core:undo (input.hidden-input)
     -0:13.2.0 core:move-down (input.hidden-input)
     -0:12.9.0 core:move-right (input.hidden-input)
  3x -0:12.7.0 core:move-up (input.hidden-input)
  3x -0:12.2.0 core:move-right (input.hidden-input)
     -0:07.8.0 core:backspace (input.hidden-input)
     -0:06.8.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
Atom-SFTP-sync 2.0.1 
remote-sync 4.1.8 
```

**Comment by mklarsen** [comment]
bad response / support
