### ISSUE TITLE
Uncaught TypeError: Cannot read property 'quit' of undefined

### ISSUE THREAD

**Issue by Zakkai** [yongkangchen/remote-sync#72]
Uncaught TypeError: Cannot read property 'quit' of undefined

**Atom Version**: 0.155.0
**System**: Mac OS X 10.9.5
**Thrown From**: [remote-sync](https://github.com/yongkangchen/remote-sync) package, v2.3.1

### Steps To Reproduce

1. Try to Download All from a remote host, using FTP

### Stack Trace

```
At /Users/Atticus/.atom/packages/remote-sync/lib/transports/FtpTransport.coffee:12

TypeError: Cannot read property 'quit' of undefined
  at ScpTransport.module.exports.ScpTransport.dispose (/Users/Atticus/.atom/packages/remote-sync/lib/transports/FtpTransport.coffee:12:22)
  at /Users/Atticus/.atom/packages/remote-sync/lib/RemoteSync.coffee:176:19
  at fs.js:295:14
  at Object.oncomplete (fs.js:93:15)

```

/cc @atom/core

**Comment by hanoc** [comment]
I've just got this error on save using FTP:

**.remote-sync.json**

    {
      "transport": "ftp",
      "uploadOnSave": true,
      "hostname": "xxxx",
      "port": "21",
      "target": "a wrong target directory",
      "ignore": [
        ".git/**"
      ],
      "username": "xxxx",
      "password": "xxxx"
    }
    

**stack trace**

    /Users/miquel/.atom/packages/remote-sync/lib/transports/FtpTransport.coffee:12

    TypeError: Cannot read property 'quit' of undefined
      at ScpTransport.module.exports.ScpTransport.dispose (/Users/miquel/.atom/packages/remote-sync/lib/transports/FtpTransport.coffee:12:22)
      at /Users/miquel/.atom/packages/remote-sync/lib/RemoteSync.coffee:176:19
      at fs.js:295:14
      at Object.oncomplete (fs.js:93:15)


**atom -v**

    0.169.0

**apm list --installed --bare**

    Sublime-Style-Column-Selection@1.1.3
    atom-ctags@2.5.5
    auto-detect-indentation@0.3.0
    auto-indent@0.1.0
    autocomplete-plus@1.1.0
    autocomplete-snippets@0.3.2
    color-picker@1.2.6
    git-tab-status@1.3.0
    highlight-selected@0.7.0
    linter@0.9.1
    merge-conflicts@1.2.8
    minimap@3.5.4
    minimap-find-and-replace@3.1.0
    minimap-git-diff@3.1.0
    minimap-highlight-selected@3.1.0
    minimap-selection@3.1.0
    notebook@0.4.0
    preview-tabs@0.1.6
    project-manager@1.14.1
    remember-session@0.5.1
    remote-sync@2.3.1
    seti-syntax@0.2.1
    seti-ui@0.5.1
    starred-package-installer@0.1.0
    symbol-gen@0.1.8
    term2@0.9.4


completely closing and openning atom got me the following error on save:

    Error: Can't create directory: Permission denied



That's when I checked my config and discovered that the target directory was wrong.
Changed that to the correct one, saved and sync uploaded the file correctly.

I'm not sure if it's related. I can not reproduce it now. If I change back to a wrong ftp config it does just display the error.

**Comment by visualcookie** [comment]
This issue is still persistent.

Here my config:
```
{
  "transport": "ftp",
  "uploadOnSave": true,
  "hostname": "dev.xxx.eu",
  "target": "/test.xxx.dev.xxx.eu",
  "ignore": [
    ".git/**",
    ".gitignore",
    ".backend.json",
    ".remote-sync.json",
    "COMMIT_EDITMSG/**"
  ],
  "username": "xxx",
  "password": "xxx"
}
```

**Comment by hax** [comment]
same problem when I save `.remote-sync.json` while uploading.

> /Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:759
> 
> TypeError: Cannot read property 'quit' of undefined
  at FtpTransport.module.exports.FtpTransport.dispose (/Users/hax/.atom/packages/remote-sync/lib/transports/FtpTransport.coffee:12:22)
  at RemoteSync.dispose (/Users/hax/.atom/packages/remote-sync/lib/RemoteSync.coffee:50:18)
  at reload (/Users/hax/.atom/packages/remote-sync/index.coffee:41:29)
  at /Users/hax/.atom/packages/remote-sync/index.coffee:98:24
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1016:20)
  at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:998:19)
  at TextEditor.module.exports.TextEditor.save (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:578:26)
  at Pane.module.exports.Pane.saveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:523:18)
  at Pane.module.exports.Pane.saveActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:506:19)
  at Workspace.module.exports.Workspace.saveActivePaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:585:35)
  at atom-workspace.atom.commands.add.core:save (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace-element.js:317:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:177:20)

**Comment by bradleyflood** [comment]
Same issue

My config:
```
{
  "transport": "ftp",
  "hostname": "10.0.10.2",
  "port": "22",
  "username": "x",
  "target": "/home/x/public_html_design",
  "ignore": [
    ".git/**"
  ],
  "uploadOnSave": true,
  "password": "xxx"
}
```

**Comment by pgendron** [comment]
Same here...

Config:{
  "transport": "ftp",
  "uploadOnSave": true,
  "hostname": "xxx",
  "port": "21",
  "target": "/",
  "ignore": [
      ".git/**"
  ],
  "username": "xxxx",
  "password": "xxxxi"
}

**Comment by brolaugh** [comment]
Got the same error when I had edited <code>.remote-sync.json</code> and saved the file.
.remote-sync.json{
  "transport": "ftp",
  "hostname": "31.22.4.135",
  "port": "21",</p>
  "username": "xxxxx",
  "password": "xxxxxx",
  "target": "/",
  "ignore": [
    ".git/**",
    ".git",
    "TODO",
    "*config.php"
  ],
  "uploadOnSave": true
}

**Comment by Fudge0952** [comment]
Confirming that I have the same issue D:

**Steps to reproduce:** Whenever the file is saved

**Version:** 1.0.2

**System:** Windows 8.1 64 bit

**Thrown from:** remote-sync 3.1.2

**Error**:

Uncaught TypeError: Cannot read property 'quit' of undefined

**My .response-sync.json file**:
```
{
    "transport": "ftp",
    "uploadOnSave": true,
    "hostname": "ftp.xxx",
    "port": 21,
    "username": "xxx",
    "password": "xxx",
    "target": "/public_html/",
    "ignore": [
        ".git/**",
        "certs/**"
    ]
}
```

**Stack Trace**:
```
C:\Users\Tim\AppData\Local\atom\app-1.0.2\resources\app.asar\src\pane.js:774
Hide Stack Trace
TypeError: Cannot read property 'quit' of undefined
  at FtpTransport.module.exports.FtpTransport.dispose (C:\Users\Tim\.atom\packages\remote-sync\lib\transports\FtpTransport.coffee:12:22)
  at RemoteSync.dispose (C:\Users\Tim\.atom\packages\remote-sync\lib\RemoteSync.coffee:50:18)
  at reload (C:\Users\Tim\.atom\packages\remote-sync\index.coffee:41:29)
  at C:\Users\Tim\.atom\packages\remote-sync\index.coffee:98:24
  at Emitter.module.exports.Emitter.emit (C:\Users\Tim\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
  at TextBuffer.module.exports.TextBuffer.saveAs (C:\Users\Tim\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:996:20)
  at TextBuffer.module.exports.TextBuffer.save (C:\Users\Tim\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:978:19)
  at TextEditor.module.exports.TextEditor.save (C:\Users\Tim\AppData\Local\atom\app-1.0.2\resources\app.asar\src\text-editor.js:579:26)
  at Pane.module.exports.Pane.saveItem (C:\Users\Tim\AppData\Local\atom\app-1.0.2\resources\app.asar\src\pane.js:535:18)
  at Pane.module.exports.Pane.saveActiveItem (C:\Users\Tim\AppData\Local\atom\app-1.0.2\resources\app.asar\src\pane.js:518:19)
  at Workspace.module.exports.Workspace.saveActivePaneItem (C:\Users\Tim\AppData\Local\atom\app-1.0.2\resources\app.asar\src\workspace.js:592:35)
  at atom-workspace.atom.commands.add.core:save (C:\Users\Tim\AppData\Local\atom\app-1.0.2\resources\app.asar\src\workspace-element.js:311:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Tim\AppData\Local\atom\app-1.0.2\resources\app.asar\src\command-registry.js:241:29)
  at C:\Users\Tim\AppData\Local\atom\app-1.0.2\resources\app.asar\src\command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\Tim\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\Tim\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (C:\Users\Tim\AppData\Local\atom\app-1.0.2\resources\app.asar\src\window-event-handler.js:177:20)
```

**Comment by Nico207** [comment]
**Steps to reproduce :**
1. open .remote-sync.json
2. save the file

**Atom Version**: 1.0.18
**System**: Windows 7 64bits (french version)
**Thrown From**: [remote-sync](https://github.com/yongkangchen/remote-sync) package, v3.1.2


### Stack Trace

Uncaught TypeError: Cannot read property 'quit' of undefined

```
At C:\Users\<USER>\AppData\Local\atom\app-1.0.18\resources\app.asar\src\pane.js:809

TypeError: Cannot read property 'quit' of undefined
    at FtpTransport.module.exports.FtpTransport.dispose (C:\Users\<USER>\.atom\packages\remote-sync\lib\transports\FtpTransport.coffee:12:22)
    at RemoteSync.dispose (C:\Users\<USER>\.atom\packages\remote-sync\lib\RemoteSync.coffee:50:18)
    at reload (C:\Users\<USER>\.atom\packages\remote-sync\index.coffee:41:29)
    at C:\Users\<USER>\.atom\packages\remote-sync\index.coffee:98:24
    at Emitter.module.exports.Emitter.emit (C:\Users\<USER>\AppData\Local\atom\app-1.0.18\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
    at TextBuffer.module.exports.TextBuffer.saveAs (C:\Users\<USER>\AppData\Local\atom\app-1.0.18\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1037:20)
    at TextBuffer.module.exports.TextBuffer.save (C:\Users\<USER>\AppData\Local\atom\app-1.0.18\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1004:19)
    at TextEditor.module.exports.TextEditor.save (C:\Users\<USER>\AppData\Local\atom\app-1.0.18\resources\app.asar\src\text-editor.js:584:26)
    at Pane.module.exports.Pane.saveItem (C:\Users\<USER>\AppData\Local\atom\app-1.0.18\resources\app.asar\src\pane.js:547:18)
    at Pane.module.exports.Pane.saveActiveItem (C:\Users\<USER>\AppData\Local\atom\app-1.0.18\resources\app.asar\src\pane.js:530:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (C:\Users\<USER>\AppData\Local\atom\app-1.0.18\resources\app.asar\src\workspace.js:609:35)
    at atom-workspace.atom.commands.add.core:save (C:\Users\<USER>\AppData\Local\atom\app-1.0.18\resources\app.asar\src\workspace-element.js:293:30)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\<USER>\AppData\Local\atom\app-1.0.18\resources\app.asar\src\command-registry.js:245:29)
    at C:\Users\<USER>\AppData\Local\atom\app-1.0.18\resources\app.asar\src\command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\<USER>\AppData\Local\atom\app-1.0.18\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:524:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\<USER>\AppData\Local\atom\app-1.0.18\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:347:22)
```

### Commands

```
     -6:45.4.0 core:paste (atom-text-editor.editor.is-focused)
     -6:42.9.0 core:save (atom-text-editor.editor.is-focused)
  2x -6:38.2.0 core:paste (atom-text-editor.editor.is-focused)
     -6:36.6.0 core:save (atom-text-editor.editor.is-focused)
     -6:35.1.0 core:paste (atom-text-editor.editor.is-focused)
     -6:34.3.0 editor:move-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -6:34.1.0 core:delete (atom-text-editor.editor.is-focused)
     -6:32.8.0 core:save (atom-text-editor.editor.is-focused)
     -6:17.4.0 core:paste (atom-text-editor.editor.is-focused)
     -6:16.5.0 core:save (atom-text-editor.editor.is-focused)
     -0:45.6.0 editor:newline (atom-text-editor.editor.is-focused)
  2x -0:44.7.0 core:move-left (atom-text-editor.editor.is-focused)
  2x -0:42.5.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:16.2.0 core:save (atom-text-editor.editor.is-focused)
  2x -0:06.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:05.2.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {},
  "remote-sync": {
    "difftoolCommand": "C:\\Program Files (x86)\\WinMerge\\WinMergeU.exe"
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.14
autoclose-html, v0.19.0
autocomplete-php, v0.3.7
color-picker, v2.0.12
file-icons, v1.6.9
keyboard-localization, v1.4.8
minimap, v4.13.4
minimap-bookmarks, v0.1.0
minimap-codeglance, v0.4.2
minimap-find-and-replace, v4.3.0
minimap-git-diff, v4.1.8
pigments, v0.15.0
remote-sync, v3.1.2

# Dev
No dev packages
```

**Comment by matthewjrallen** [comment]
Ive got the same issue

[Enter steps to reproduce below:]

1. Make a change to ```.remote-sync.json```
2. Error happens when i save

**Atom Version**: 1.2.4
**System**: Mac OS X 10.11.1
**Thrown From**: [remote-sync](https://github.com/yongkangchen/remote-sync) package, v3.5.0


### Stack Trace

Uncaught TypeError: Cannot read property 'quit' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:825

TypeError: Cannot read property 'quit' of undefined
    at FtpTransport.module.exports.FtpTransport.dispose (/Users/matt/.atom/packages/remote-sync/lib/transports/FtpTransport.coffee:12:22)
    at RemoteSync.dispose (/Users/matt/.atom/packages/remote-sync/lib/RemoteSync.coffee:50:18)
    at reload (/Users/matt/.atom/packages/remote-sync/index.coffee:49:29)
    at /Users/matt/.atom/packages/remote-sync/index.coffee:110:24
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
    at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1035:20)
    at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1002:19)
    at TextEditor.module.exports.TextEditor.save (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:557:26)
    at Pane.module.exports.Pane.saveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:530:18)
    at Pane.module.exports.Pane.saveActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:513:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:631:35)
    at atom-workspace.commandRegistry.add.core:save (/Applications/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:173:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:533:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:356:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:99:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -7:52.7.0 core:copy (atom-text-editor.editor.is-focused)
     -7:45.9.0 core:paste (atom-text-editor.editor.is-focused)
  2x -7:43.1.0 editor:indent-selected-rows (atom-text-editor.editor.is-focused)
  2x -7:38 find-and-replace:show (atom-text-editor.editor.is-focused)
     -7:36.7.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -7:36.7.0 core:cancel (atom-text-editor.editor.mini.is-focused)
  6x -7:36 find-and-replace:select-next (atom-text-editor.editor.is-focused)
     -7:31.3.0 core:move-right (atom-text-editor.editor.is-focused.autocomplete-active)
  7x -7:30.6.0 core:delete (atom-text-editor.editor.is-focused)
     -7:25.3.0 core:save (atom-text-editor.editor.is-focused.autocomplete-active)
  2x -6:59.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -6:58.2.0 core:save (atom-text-editor.editor.is-focused)
     -6:30.6.0 remote-sync:upload-git-change (span.name.icon.icon-repo)
     -1:47.5.0 remote-sync:upload-folder (span.name.icon.icon-file-directory)
     -0:26.6.0 remote-sync:upload-file (span.name.icon.icon-file-text)
     -0:02.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "native-ui",
      "batman-syntax"
    ],
    "disabledPackages": [
      "wrap-guide",
      "autoflow"
    ]
  },
  "remote-sync": {}
}
```

### Installed Packages

```coffee
# User
atom-minify, v0.6.2
autoclose-html, v0.19.0
batman-syntax, v1.0.1
color-picker, v2.0.13
file-icons, v1.6.12
highlight-line, v0.11.0
less-than-slash, v0.11.1
minimap, v4.16.2
native-ui, v0.9.0
pigments, v0.19.0
project-manager, v2.6.5
remote-sync, v3.5.0
sync-settings, v0.6.0

# Dev
No dev packages
```

# My Remote Sync Config
```json
{
  "transport": "ftp",
  "hostname": "*****",
  "port": 21,
  "username": "*****",
  "password": "*****",
  "target": "*****",
  "ignore": [
    ".remote-sync.json",
    ".git/**",
    "node_modules",
    ".DS_Store"
  ]
}
```
