### ISSUE TITLE
Uncaught TypeError: Arguments to path.join must be strings

### ISSUE THREAD

**Issue by acorbi** [yongkangchen/remote-sync#77]
Uncaught TypeError: Arguments to path.join must be strings

**Atom Version**: 0.161.0
**System**: Mac OS X 10.10.1
**Thrown From**: [remote-sync](https://github.com/yongkangchen/remote-sync) package, v2.3.1

### Steps To Reproduce

1. ...
2. ...

### Stack Trace

```
At path.js:384

TypeError: Arguments to path.join must be strings
  at Object.exports.join (path.js:384:15)
  at ScpTransport.module.exports.ScpTransport.upload (/Users/alexcorbi/.atom/packages/remote-sync/lib/transports/ScpTransport.coffee:16:27)
  at UploadListener.module.exports.UploadListener.uploadFile (/Users/alexcorbi/.atom/packages/remote-sync/lib/UploadListener.coffee:18:15)
  at q.process (/Applications/Atom.app/Contents/Resources/app/node_modules/async/lib/async.js:769:21)
  at process._tickCallback (node.js:378:11)
  at Ipc.sendSync (/Applications/Atom.app/Contents/Resources/atom/renderer/api/lib/ipc.js:39:29)
  at Ipc.sendChannelSync (/Applications/Atom.app/Contents/Resources/atom/renderer/api/lib/ipc.js:47:28)
  at BrowserWindow.RemoteMemberFunction [as emit] (/Applications/Atom.app/Contents/Resources/atom/renderer/api/lib/remote.js:110:29)
  at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (/Applications/Atom.app/Contents/Resources/app/src/context-menu-manager.js:169:33)
  at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:138:33)
  at HTMLDocument.handler (/Applications/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:112:34)
  at HTMLDocument.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at HTMLDocument.elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)

```

/cc @atom/core

**Comment by hanoc** [comment]
I've been able to reproduce this error by not specifying a "Target directory" in the new configration dialog.
The resulting .remote-sync.json ends up without target as you expected.

Setting a target makes it work.

**Comment by pyrokinetiq** [comment]
Might be worthwhile making `/` the default `target` to prevent this error happening when one is not specified
