### ISSUE TITLE
Uncaught TypeError: Cannot read property 'download' of undefined

### ISSUE THREAD

**Issue by ThingsCore** [yongkangchen/remote-sync#90]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.179.0
**System**: Microsoft Windows 8.1
**Thrown From**: [remote-sync](https://github.com/yongkangchen/remote-sync) package, v2.4.0

### Stack Trace

Uncaught TypeError: Cannot read property 'download' of undefined

```
At /C:/Users/Convasys/.atom/packages/remote-sync/lib/RemoteSync.coffee:112

TypeError: Cannot read property 'download' of undefined
  at atom-workspace.<anonymous> (C:\Users\Convasys\.atom\packages\remote-sync\lib\RemoteSync.coffee:72:21)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Convasys\AppData\Local\atom\app-0.179.0\resources\app\src\command-registry.js:243:29)
  at CommandRegistry.handleCommandEvent (C:\Users\Convasys\AppData\Local\atom\app-0.179.0\resources\app\src\command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\Convasys\AppData\Local\atom\app-0.179.0\resources\app\src\command-registry.js:156:19)
  at [object Object].jQuery.fn.trigger (C:\Users\Convasys\AppData\Local\atom\app-0.179.0\resources\app\src\space-pen-extensions.js:64:23)
  at EventEmitter.<anonymous> (C:\Users\Convasys\AppData\Local\atom\app-0.179.0\resources\app\src\window-event-handler.js:70:67)
  at EventEmitter.emit (events.js:119:17)
  at EventEmitter.ipc.sendSync (C:\Users\Convasys\AppData\Local\atom\app-0.179.0\resources\atom\renderer\api\lib\ipc.js:21:31)
  at BrowserWindow.RemoteMemberFunction [as emit] (C:\Users\Convasys\AppData\Local\atom\app-0.179.0\resources\atom\renderer\api\lib\remote.js:110:29)
  at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (C:\Users\Convasys\AppData\Local\atom\app-0.179.0\resources\app\src\context-menu-manager.js:169:33)
  at HTMLDocument.<anonymous> (C:\Users\Convasys\AppData\Local\atom\app-0.179.0\resources\app\src\window-event-handler.js:143:33)
  at HTMLDocument.handler (C:\Users\Convasys\AppData\Local\atom\app-0.179.0\resources\app\src\space-pen-extensions.js:112:34)
  at HTMLDocument.jQuery.event.dispatch (C:\Users\Convasys\AppData\Local\atom\app-0.179.0\resources\app\node_modules\space-pen\vendor\jquery.js:4681:9)
  at HTMLDocument.elemData.handle (C:\Users\Convasys\AppData\Local\atom\app-0.179.0\resources\app\node_modules\space-pen\vendor\jquery.js:4359:46)

```

### Commands

```
     -2:51.4 pane:reopen-closed-item (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "atom-light-syntax"
    ]
  },
  "remote-sync": {}
}
```

### Installed Packages

```coffee
# User
remote-sync, v2.4.0

# Dev
No dev packages
```

**Comment by yongkangchen** [comment]
I guess your transport setting is not `scp` or `sftp` or `ftp`?

**Comment by ThingsCore** [comment]
I was using SFTP . But certainly it may not be issue at all.
