### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by mykeylynx** [yongkangchen/remote-sync#93]
Uncaught TypeError: undefined is not a function

**Atom Version**: 0.155.0
**System**: Mac OS X 10.9.5
**Thrown From**: [remote-sync](https://github.com/yongkangchen/remote-sync) package, v2.4.0

### Steps To Reproduce

1. ...
2. ...

### Stack Trace

```
At /Users/contra06b/.atom/packages/remote-sync/lib/view/StatusView.coffee:17

TypeError: undefined is not a function
  at StatusView.module.exports.StatusView.attach (/Users/contra06b/.atom/packages/remote-sync/lib/view/StatusView.coffee:17:17)
  at StatusView.attach (/Users/contra06b/.atom/packages/remote-sync/lib/view/StatusView.coffee:1:1)
  at StatusView.module.exports.StatusView.initialize (/Users/contra06b/.atom/packages/remote-sync/lib/view/StatusView.coffee:12:6)
  at StatusView.View (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/lib/space-pen.js:145:25)
  at new StatusView (/Users/contra06b/.atom/packages/remote-sync/lib/view/StatusView.coffee:5:3)
  at Object.module.exports.activate (/Users/contra06b/.atom/packages/remote-sync/lib/RemoteSync.coffee:33:18)
  at doActive (/Users/contra06b/.atom/packages/remote-sync/index.coffee:20:16)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/emissary/lib/emitter.js:85:24
  at Project.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/emissary/lib/emitter.js:118:15)
  at Project.module.exports.Project.setPaths (/Applications/Atom.app/Contents/Resources/app/src/project.js:210:12)
  at Ipc.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:38:25)
  at Ipc.emit (events.js:110:17)
  at process.<anonymous> (/Applications/Atom.app/Contents/Resources/atom/renderer/api/lib/ipc.js:22:29)
  at process.emit (events.js:118:17)

```

/cc @atom/core

**Comment by mykeylynx** [comment]
I always said I don't know is not an answer!

**Comment by DevBlood** [comment]
The emissary module is missing, try this from a terminal:

cd /Applications/Atom.app/Contents/Resources/app.asar.unpacked
npm install emissary

That solved the problem for me.

**Comment by brocknessmonster** [comment]
Any ideas how to fix in Windows?

**Comment by yongkangchen** [comment]
please update the package to the latest and try again
