### ISSUE TITLE
Uncaught TypeError: Cannot read property 'fetchFileTree' of undefined

### ISSUE THREAD

**Issue by kevinjosephjohn** [yongkangchen/remote-sync#94]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.181.0
**System**: Mac OS X 10.10.1
**Thrown From**: [remote-sync](https://github.com/yongkangchen/remote-sync) package, v2.4.0

### Stack Trace

Uncaught TypeError: Cannot read property 'fetchFileTree' of undefined

```
At /Users/Kevin/.atom/packages/remote-sync/lib/commands/DownloadAllCommand.coffee:12

TypeError: Cannot read property 'fetchFileTree' of undefined
  at Object.module.exports.run (/Users/Kevin/.atom/packages/remote-sync/lib/commands/DownloadAllCommand.coffee:12:14)
  at download (/Users/Kevin/.atom/packages/remote-sync/lib/RemoteSync.coffee:131:15)
  at atom-workspace.<anonymous> (/Users/Kevin/.atom/packages/remote-sync/lib/RemoteSync.coffee:45:7)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app/node_modules/command-palette/lib/command-palette-view.js:120:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
  at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:176:20)

```

### Commands

```
     -32:10.3 application:new-file (atom-pane.pane.active)
  2x -31:24.5 core:paste (atom-text-editor.editor.is-focused)
 12x -31:08.7 core:backspace (atom-text-editor.editor.is-focused)
  2x -30:51.3 core:save (atom-text-editor.editor.is-focused)
     -30:16.3 command-palette:toggle (atom-text-editor.editor.is-focused)
     -30:09.7 remote-sync:reload-config (atom-text-editor.editor.is-focused)
     -30:03.7 command-palette:toggle (atom-text-editor.editor.is-focused)
     -30:01.5 core:confirm (atom-text-editor.editor.mini)
     -30:01.5 remote-sync:download-all (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store"
    ]
  },
  "remote-sync": {}
}
```

### Installed Packages

```coffee
# User
linter, v0.11.1
minimap, v4.2.3
project-manager, v1.15.5
remote-sync, v2.4.0

# Dev
No dev packages
```

**Comment by yongkangchen** [comment]
I guess your transport setting is not `scp` or `sftp` or `ftp`?
