### ISSUE TITLE
Uncaught TypeError: Cannot read property 'upload' of undefined

### ISSUE THREAD

**Issue by reggi** [yongkangchen/remote-sync#99]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.186.0
**System**: Mac OS X 10.10.2
**Thrown From**: [remote-sync](https://github.com/yongkangchen/remote-sync) package, v2.4.0

### Stack Trace

Uncaught TypeError: Cannot read property 'upload' of undefined

```
At /Users/thomas/.atom/packages/remote-sync/lib/UploadListener.coffee:18

TypeError: Cannot read property 'upload' of undefined
  at UploadListener.module.exports.UploadListener.uploadFile (/Users/thomas/.atom/packages/remote-sync/lib/UploadListener.coffee:18:14)
  at q.process (/Applications/Atom.app/Contents/Resources/app/node_modules/async/lib/async.js:769:21)
  at process._tickCallback (node.js:364:11)

```

### Commands

```
     -0:01.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store"
    ],
    "excludeVcsIgnoredPaths": false,
    "disabledPackages": [
      "wrap-guide",
      "autocomplete",
      "autosave",
      "background-tips",
      "bookmarks",
      "jsformat",
      "language-jsx"
    ],
    "themes": [
      "atom-dark-ui",
      "monokai"
    ]
  },
  "remote-sync": {}
}
```

### Installed Packages

```coffee
# User
autocomplete-paths, v0.9.1
autocomplete-plus, v1.1.0
autocomplete-plus-async, v0.22.0
language-ejs, v0.1.0
language-liquid, v0.2.0
monokai, v0.9.0
react, v0.7.8
remote-sync, v2.4.0

# Dev
No dev packages
```

**Comment by yongkangchen** [comment]
Please check `transport` in your .remote-sync.json, make sure it is `scp` or `sftp` or `ftp`
